### ISSUE TITLE
Graph - Access Point details

### ISSUE THREAD

**Issue by smarcu** [VREMSoftwareDevelopment/WifiAnalyzer#1]
Hi, I appreciate the amazing work you have done so far with the app,

I would suggest a small addition to the application:
On graph would be nice to have Access Point details.
When touching a specific chart, highlight and show details.

**Comment by VREMSoftwareDevelopment** [comment]
Current release V1.0.3.234
Channel and Time graph have an Access Point details popup.
This is fixed in the next release.

**Comment by smarcu** [comment]
Great, thanks!
