### ISSUE TITLE
Feature request: Contrasting colors for WEP, WPS, and open

### ISSUE THREAD

**Issue by Techwolf** [VREMSoftwareDevelopment/WiFiAnalyzer#100]
On the Access Points list screen/window, the line that has the lock icon and text for security info, please make an option to colorize WEP, WPS, and open to different colors. This is so one can quickly see what access points are open, WEP, and WPS without have to stare and parse the line of text. This would be helpful when walking around looking for open points.

**Comment by VREMSoftwareDevelopment** [comment]
Currently security filter option allows to choose which AP is available in the Access Points list, which will help  when walking around looking for open points. 
When we don't have an opportunity or plan to implement a feature, we encourage developers to fork the project and submit your changes back.

Thank you,
The VREM Development Team

**Comment by VREMSoftwareDevelopment** [comment]
Moved to #117
