### ISSUE TITLE
Feature request: Contrasting colors for 2.5GHz and 5GHz channels.

### ISSUE THREAD

**Issue by Techwolf** [VREMSoftwareDevelopment/WiFiAnalyzer#101]
On the Access Point list screen/window, please make the channel numbers for 2.5 and 5 a different color. This so one can see what band they are without haveing to parse the channel number in there brain.

**Comment by VREMSoftwareDevelopment** [comment]
On the Access Point list there is a frequency displayed in MHz beside the channel number.
When we don't have an opportunity or plan to implement a feature, we encourage developers to fork the project and submit your changes back.

Thank you,
The VREM Development Team

**Comment by VREMSoftwareDevelopment** [comment]
Moved to #117
