### ISSUE TITLE
Distance 

### ISSUE THREAD

**Issue by TDClarke** [VREMSoftwareDevelopment/WiFiAnalyzer#105]
The distance calculations appear wrong showing 13.8m when that is clearly at lest double the distance.

**Comment by VREMSoftwareDevelopment** [comment]
[Usage-tips section](https://vremsoftwaredevelopment.github.io/WiFiAnalyzer/#usage-tips)
Distance to the Access Point is estimated

[How-to section](https://vremsoftwaredevelopment.github.io/WiFiAnalyzer/#how-to)
How is distance calculated to Access Point
