### ISSUE TITLE
 Feature request: Switch off wifi, if it was switched off before usage

### ISSUE THREAD

**Issue by micressor** [VREMSoftwareDevelopment/WiFiAnalyzer#106]
I have 
* [X] searched open and closed issues for duplicates
----------------------------------------
WifiAnalyzer should turn off Wifi when it was switched on to use wifianalyzer.
I saw that in other wifi analyzers and I think it is very helpful.

**Comment by VREMSoftwareDevelopment** [comment]
[Wi-Fi off on exit | issue #103](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/issues/103)
