### ISSUE TITLE
Bug: App not requesting location permission

### ISSUE THREAD

**Issue by user8446** [VREMSoftwareDevelopment/WiFiAnalyzer#107]
After opening the app, I get the "no data" message regarding Android 6. I never got the location permission request from the app and after checking the app permissions itself it shows no permissions. Under all permissions it shows:
view Wi-Fi connections
connect and disconnect from Wi-Fi
full network access

I tried an alternative wifi analyzer app to try to see if it was my device and it did request the location permission and work. Running 6.0.1.
Thank you.

**Comment by VREMSoftwareDevelopment** [comment]
[Android OS 6+ - Location Service ON](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/issues/23)

**Comment by user8446** [comment]
This was closed without comment. My location services IS ON.
