### ISSUE TITLE
Issue with the Channel Rating 

### ISSUE THREAD

**Issue by haidernawaz99** [VREMSoftwareDevelopment/WiFiAnalyzer#111]
Hello!
Whenever​ I select the Channel Rating from the menu, the stars aren't fully visible in Portrait mode. Even when i slide from right to left on it, I can't see the stars scrolling from left to right. Although, the stars are fully visible in Landscape Mode, the aforementioned issue arises in Portrait 
![20170611_171456](https://user-images.githubusercontent.com/29353361/27010935-a57ad4be-4ec9-11e7-8491-4309ba6c84ce.png)
![20170611_171527](https://user-images.githubusercontent.com/29353361/27010939-c17a244e-4ec9-11e7-855a-5642cb8c31f0.png)

![screenshot_20170611-165153](https://user-images.githubusercontent.com/29353361/27010937-b29f5b88-4ec9-11e7-879e-bdca46948440.jpg)

**Comment by VREMSoftwareDevelopment** [comment]
Channel Rating uses linear layout with 3 columns (around 60%, 20% and 20%)
We have used "android layout weight" to alloy dynamic stretching of columns based on screen sizes.
That why sometimes you see full star or partial star. 
This does not effect in any way the actual rating of the channel.

To learn more about android layout weight [click here](https://stackoverflow.com/questions/3995825/what-does-androidlayout-weight-mean). 

If you know, how to do this in any other way, we would appreciate your advice or your code contribution.
