### ISSUE TITLE
Wifi scanning on secondary users

### ISSUE THREAD

**Issue by mirh** [VREMSoftwareDevelopment/WiFiAnalyzer#112]
Follows https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/issues/23#issuecomment-305981427

I know non-primary users have usually some restrictions, namely developer options, system updates, RadioInfo tests, sim status and imei (more?)
...
Though, I just checked in the [Wi-Fi status](https://android.googlesource.com/platform/packages/apps/Settings/+/nougat-release/src/com/android/settings/wifi/WifiStatusTest.java) testing menu, and that's correctly reporting RSSI. 
So, it seems a bug on your side.

**Comment by VREMSoftwareDevelopment** [comment]
### Non-primary user testing:
- Wi-Fi status testing menu
   - Current connection information is available
   - No scan results available
- WiFiAnalyzer works the same as for primary user as long as it is installed using different google account from the play store (not same as primary user).

### To help us to investigate the issue, please provide the following:
- exact steps to reproduce the issue you are seeing
- do not forget to provide screenshots, including application about screen.

**Comment by mirh** [comment]
Application about screen? What's it?

Then I haven't a lot of screenshot to provide. Wifi analyzer shows just nothing (like wifi wasn't even enabled). 

> WiFiAnalyzer works the same as for primary user as long as it is installed using different google account from the play store

I'd be curious to know why this odd additional requirement, anyway yes I'm not using the same google account. 
and @wino45 already provided 'everything' anyway.

**Comment by VREMSoftwareDevelopment** [comment]
Application has "About" screen (Application version, OS version, etc).
Without knowing exact steps to reproduce the issue we are not able to reproduce it and fix it.

**Comment by mirh** [comment]
~~Oh lol, sorry.
W-T-F? I have been trying for almost a month to get the analyzer working..
Now it is? :/~~

Ok so.. [this](https://user-images.githubusercontent.com/9366725/27256960-8500b1fc-53c6-11e7-8e4f-9589b73d6afb.png) is the screen you asked for. 
But I could actually manage to spot the wizardary. 

WifiAnalyzer can work on secondary users accounts **IF** it is *also* installed in the primary account. 
Otherwise, scenario is the one I described above. 

This is probably why you couldn't reproduce.

**Comment by VREMSoftwareDevelopment** [comment]
Great that you found the "wizardary".
We are able to see the same issue on devices running Android OS 6+.
This feel like an Android OS multi-user permission rights model.
We will see what we can about it.

**Comment by VREMSoftwareDevelopment** [comment]
**WiFiAnalyzer must be installed in the primary account, in order for it to work on the secondary accounts.**

**Comment by mirh** [comment]
Mhh.. okay. 
But I'd like hope/guess that you might have some wording that points this out to the user, if any.

**Comment by VREMSoftwareDevelopment** [comment]
@mirh Would you like to help us with this feature? It would be great to add another contributor to this project.

**Comment by mirh** [comment]
I feel already enough a contributor to have pinpointed the thing 😅

Anyway.. I'd first be curious about whatever's going on to start with. I mean, putting aside that I wonder if you can detect you are falling under that case (for example, I assume you can't know if gps is enabled or not from your side, if you have to put there its 6+ warning irregardless of anything), I'm not sure if this is expected behavior by google in the first place. 
It looks so odd.

**Comment by Apinchepelon** [comment]
#@`
[_downloads_eBook-SecurityCustomerStories.pdf](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/files/12655653/_downloads_eBook-SecurityCustomerStories.pdf)
![Screenshot_20230918-201304](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/assets/145341281/1b537b46-ebec-4366-8ec1-c632e157f35b)
`
