### ISSUE TITLE
Channel Graph Bug

### ISSUE THREAD

**Issue by IlyaZima** [VREMSoftwareDevelopment/WiFiAnalyzer#113]
After all lines reaches the entire width of the grid they starting lead to some zero coordinate point.
![screenshot_20170616-204458](https://user-images.githubusercontent.com/29510074/27255855-afcec8ae-53af-11e7-8819-3ab373d908db.png)

**Comment by VREMSoftwareDevelopment** [comment]
Can you please provide us with application "About" screenshot (app version number and OS version number)?

**Comment by IlyaZima** [comment]
![screenshot_20170618-091517](https://user-images.githubusercontent.com/29510074/27351491-3ab71e78-5606-11e7-9097-38eec748e122.png)

**Comment by Gitoffthelawn** [comment]
@IlyaZima Did you mean to close this issue?

**Comment by IlyaZima** [comment]
No. Sorry. Wrong button.

**Comment by VREMSoftwareDevelopment** [comment]
Unfortunately, we are not able to see this issue on the devices available to us for testing.
To help us to investigate further, please provide exact steps to reproduce the issue you are seeing?
