### ISSUE TITLE
Feature request: Swipe between pages

### ISSUE THREAD

**Issue by Gitoffthelawn** [VREMSoftwareDevelopment/WiFiAnalyzer#115]
The most popular app in the category, the eponymous [*Wifi Analyzer*](https://play.google.com/store/apps/details?id=com.farproc.wifi.analyzer) allows swiping between the different pages.  This is extremely useful and makes that app more usable than this one.  Can you add this feature to rise to the top?

**Comment by VREMSoftwareDevelopment** [comment]
Duplicate ["Add additional next/previous navigation"](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/issues/82)
