### ISSUE TITLE
Aliases for the APs

### ISSUE THREAD

**Issue by binarybear-de** [VREMSoftwareDevelopment/WiFiAnalyzer#116]
It would be nice to give some names for specific APs to keep them organised (e.g. positions of the AP).
Specially for environments with multi-AP but one SSID.

**Comment by kovadam69** [comment]
+1 This would be very nice. We also have 10+ AP, and it is quite difficult to identify them using the mac address.
Would be.a.nice option if we could assign alias to certain mac addresses.
Thanks

**Comment by cptechnik** [comment]
+1 !
please, please, please!  ... ;)

**Comment by VREMSoftwareDevelopment** [comment]
@cptechnik Unfortunately all current contributors are busy with other work. When we don't have an opportunity to implement a feature, we encourage developers to fork the project and become a contributor.

**Comment by kovadam69** [comment]
I'm forked the project to add this.

**Comment by jswolf19** [comment]
@kovadam69 is this something you're still working on? I don't know how much time I'll be able to give to this, but I'd like to see it happen. If you want to collaborate, let me know.

**Comment by kovadam69** [comment]
@jswolf19 yeah, I started to make it, it's kinda works, but there are problems with MAC addresses, since it's not easy to identify them, as one AP can broadcast different networks with different MAC addresses... I can try to commit back to this fork what I already have, but I don't know if it is still possible...

**Comment by jswolf19** [comment]
@kovadam69 Do you want to collaborate or would this be handing it over to me? Either way, if you don't mind sharing what you have, you can just push it to your own fork, you don't need to bring it up to date with the current repo. As you say, it may be easier to start from scratch, anyway.

**Comment by kovadam69** [comment]
@jswolf19 I tried to push, but seems my fork has been deleted... I don't think there were big changes in the internal logic that it should not work out of the box what I did, so may be there is no need to start from scratch.
I try to extract my changes somehow and start a new fork, and try to do the changes there...

**Comment by jswolf19** [comment]
@kovadam69 It looks like it got pushed... Does this look right?
https://github.com/kovadam69/WiFiAnalyzer/commit/f197bdb9733d58a47198152e1904f146a822cd4e

**Comment by kovadam69** [comment]
Yeah, I just did it, managed to log in with IntelliJ and push my changes to my repo, and create a Pull request...

now you can check it, and fix, if I did something wrong... But mainly there are minor modifications to layout and existing classes (like addig the WifiName property) and some new classes to gather them and provide for the UI (there is also an export/import possibility to CSV I think...)

**Comment by jswolf19** [comment]
@kovadam69 I think what you have might need some work before going to a pull request. I'm not currently a contributor here, anyway, so I'm fine just looking at what you have on your branch.

Do you want to continue working on this with me?

**Comment by jswolf19** [comment]
@kovadam69 I've made a copy of your commit in my repo. If you want to continue working on this, please let me know, otherwise I'll continue on my own. At any rate, thanks for providing what you've done so far! ^_^

**Comment by kovadam69** [comment]
@jswolf19 I can't merge, since I do not have write access... But they have now my changes on the shelf for the feature branch, so they can do the merge. Actually there are only slight changes to existing classes, most of them are new things, which do not need any merging.
Feel free to continue the development, I don't have the time right now to deal with it!
