### ISSUE TITLE
Show WPS status

### ISSUE THREAD

**Issue by C0rn3j** [VREMSoftwareDevelopment/WiFiAnalyzer#118]
Why - If you disable WPS on some stupid routers, it will only turn WPS into a locked state without actually fully disabling it.

Having this app show whether the WPS is currently locked or not would save me from having to resort to advanced tools on PC to check the security of my router.

**Comment by VREMSoftwareDevelopment** [comment]
The feature is not available in the current Android API's.

**Comment by C0rn3j** [comment]
I'd still prefer this to be available even as a root-only function, would that be possible?
