### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [VREMSoftwareDevelopment/WiFiAnalyzer#122]
Hi @VREMSoftwareDevelopment 

I found [this app on the Google Play Store](https://play.google.com/store/apps/details?id=com.wifi.Hotspot). This guy just took the source code, added some adds and put it on the Google Play Store

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) if it's your wish ;)

Don't forget to tell Google that:
* The app is licensed under GPL3 and this guy is violating it by distributing the app without the source code;
* He is falsely claiming he made the app;
* Also tell them that this guy has done the same thing already with other apps. Probably this is worth mentioning. (I watch him)

**Comment by hallb** [comment]
+1

**Comment by VREMSoftwareDevelopment** [comment]
Hi @Poussinou,

Thanks you very much for the information.

We will pursue all available avenues to make sure his application is compliant to GPL3v license or it will be removed from the Google play store.

VREM Development Team
