### ISSUE TITLE
Allow to select language inside the application

### ISSUE THREAD

**Issue by mbc07** [VREMSoftwareDevelopment/WiFiAnalyzer#124]
Title says all. The translation to my language isn't accurate and even then I'm forced to use it. This app needs an option to force English language or to let the user actually select whatever language they want instead of automatically forcing the same language from the device without any way to change it...

**Comment by VREMSoftwareDevelopment** [comment]
Looks like, you are reporting one issue and one feature request.
- Incorrect language translation (issue). Which language and text?
- Add ability to select the language in the application (feature request)

Would you like to help with the above? It would be great to add another contributor to this project.

**Comment by VREMSoftwareDevelopment** [comment]
@mbc07
Update Brazilian Portuguese sounds great as the first step.

**Comment by mbc07** [comment]
I'll open a PR with the language update soon, probably before the end of this week...

**Comment by VREMSoftwareDevelopment** [comment]
Next release will this feature available.
Current release V1.8.6 Google Play Store.
