### ISSUE TITLE
How to use SSID filter?

### ISSUE THREAD

**Issue by EduardBirnbaum** [VREMSoftwareDevelopment/WiFiAnalyzer#125]
It would be very helpful if the SSIDs could be selected in a dropdown menu. At the moment, the input field is key sensitive and depending on the complexity and length of the SSID, it is difficult to type them.

**Comment by VREMSoftwareDevelopment** [comment]
There is no need to use full SSID name in the filter. SSID filter allows partial text.

SSID Names Example:
- **SSIDEduard**
- **SSIDVREM**

Filter Usage Example:
- **SSID** will show both.
- **Eduard** or **Ed** will show only  **SSIDEduard**
- **VREM** or **VR** will show only  **SSIDVREM**
