### ISSUE TITLE
Export time graph to Google Sheets, etc.

### ISSUE THREAD

**Issue by MarkBennett** [VREMSoftwareDevelopment/WiFiAnalyzer#127]
As someone who's trying to understand the interference on my network over time, it would be very useful if I could capture data from the Time Graph over a long period then export all the data to Google Sheets, a CSV, Excel, etc. This would let me preform more advanced analysis that you might not necessarily want to include in the app.

Thanks for the great app!

**Comment by xuanfengttp** [comment]
I'm also looking forward to exporting the graph. But I'm not familiar with Android and Java.
But thanks for the author's great app. I can still try to export the data by image processing of the graph.

**Comment by magicbycalvin** [comment]
I'd like to bump this issue. Having the ability to output the graph to a CSV or similar would be excellent. I was sad when I found out the export option did not give me the plot data.

**Comment by VREMSoftwareDevelopment** [comment]
When we don't have an opportunity or time to implement a feature, we encourage developers to fork the project and become a contributor. It would be great to add new contributors to this project.
