### ISSUE TITLE
Make plugin for unity

### ISSUE THREAD

**Issue by FutureFireplace** [VREMSoftwareDevelopment/WiFiAnalyzer#128]
Hello, while trying to make a plugin as shown here: https://www.youtube.com/watch?v=0ahGeTNUPLM I run into trouble as the Android Studio project (from this github location) demands to be build into a full apk with UI etc.

What to do if I only want to use certain functions (spcifically R.id.channel and R.id.distance)?

// this could be useful for a lot of unity3d game-dev people, and in case you want to earn a buck/make-further-donation-options, you can sell the answer/solution on https://www.assetstore.unity3d.com ... Thomas Due, Dk

**Comment by VREMSoftwareDevelopment** [comment]
We do not consider this feature a good fit to the application. At this time we would like to spend our effort and resources to implement features that enhanced the current application. Also when we don't have an opportunity to implement a feature, we encourage developers to fork the project.
