### ISSUE TITLE
Enhancement - Use modern Android APIs

### ISSUE THREAD

**Issue by auanasgheps** [VREMSoftwareDevelopment/WiFiAnalyzer#138]
Hi guys

Your wonderful app has a little downside: still targets Lollipop APIs. Is there any particular reason for this?

Targeting Marshmallow and above would introduce many advantages like: backup of user settings, proper multi-window support, user (runtime) permissions, Quick Settings Tiles, App shortcuts and so on.

Many apps have moved forward newer APIs, it's a shame this wonderful app is being left behind!

**Comment by VREMSoftwareDevelopment** [comment]
Hi Oliver Cervera,

There are plans to implement Android 6+  features, but unfortunately not in the short term.
When we don't have an opportunity to implement a feature, we encourage developers to fork the project and become a contributor.
It would be great to add another contributor to this project.

Thank you,
The VREM Development Team
