### ISSUE TITLE
Map visualization for Wi-Fi scans

### ISSUE THREAD

**Issue by mylnikovorg** [VREMSoftwareDevelopment/WiFiAnalyzer#139]
It would be very nice to integrate Location API service due to show users positions of wifis that are contained inside of scan result. The application does not need any additional permissions to introduce.

The service https://www.mylnikov.org/archives/1170 proposes unlimited access to Wi-Fi location.
Also service could triangulate final position of a device due to multiple APs inside of the scan result.

As an example the link `https://api.mylnikov.org/geolocation/wifi?v=1.2&bssid=00:0C:42:1F:65:E9` could be used.
The visualization map could be found here `http://find-wifi.mylnikov.org/#00:0C:42:1F:65:E9`.

In total end users will be able to estimate physical location of AP and due to that find the best receive quality service.

**Comment by VREMSoftwareDevelopment** [comment]
Currently the application does not require access to internet, since we are trying to respect users' privacy and security issues.
We will be keeping this item in our bucket list.

**Comment by VREMSoftwareDevelopment** [comment]
We will not implement this feature, because of the EU General Data Protection Regulation [GDPR](https://www.eugdpr.org).
