### ISSUE TITLE
When connected to IPv6 only network the associated AP is not shown in AP list

### ISSUE THREAD

**Issue by dlakelan** [VREMSoftwareDevelopment/WiFiAnalyzer#141]
When I connect to a network that gives out IPv4 addresses, and open WiFi Analyzer and select the AP list, the first entry is different colored (lighter colored in the dark theme) and shows which AP I am associated to.

When connected to an IPv6 only network, no DHCP occurs, and no IPv4 is assigned to the phone, and WiFi analyzer mistakenly does not show which AP I am associated to, as if it thinks I'm not connected.

**Comment by VREMSoftwareDevelopment** [comment]
Can you please submit screenshots to investigate your issue?
Please find instructions here on [How to report a bug](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Feedback#how-to-report-a-bug).

**Comment by dlakelan** [comment]
Sure, here are screenshots of the channel screen and the AP screen notice that there is no entry on the top of the screen showing the AP I'm connected to, even though I am definitely connected. The network is IPv6 only.

![screenshot_20171107-195143](https://user-images.githubusercontent.com/4332910/32531018-6ecfc9cc-c3f6-11e7-999d-cf9b4f344a89.png)
![screenshot_20171107-195124](https://user-images.githubusercontent.com/4332910/32531019-6eedcc38-c3f6-11e7-8fea-2782877c491b.png)

**Comment by dlakelan** [comment]
Compare to the screenshot you show on your page: https://raw.githubusercontent.com/VREMSoftwareDevelopment/WiFiAnalyzer/master/screenshots/feature-graphic.png

At the top it shows you are currently connected to SSID-01 at 72Mbps and have ip address 192.168.1.1

this just doesn't show up when connecting to an ipv6 network.

**Comment by VREMSoftwareDevelopment** [comment]
From URL https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Feedback#how-to-report-a-bug:

> Some bugs only occur on certain devices or versions of Android, please provide the following information Device/Android OS (Settings → About Phone) and WiFiAnalyzer version (Menu -> About)

In addition can you please provide screenshoot of Android phone `Wi-Fi status`.
Here is a link to the article that explains how to get to it:
[Android Signal Strength and Field Test Codes](http://www.adweek.com/digital/android-signal-strength-and-field-test-codes/)

**Comment by dlakelan** [comment]
Problem occurs on a Moto G3 Android version 6.0 kernel 3.10.49 last updated via OTA update April 2017

Wifi Analyzer is version 1.8.7 - 33S (6.0-23) which is the latest version available to me on Google Play store.

The problem also occurs on a Kindle Fire 7 FireOS 5.4.0.1 installed Sept 19 2017 Wifi Analyzer is 1.8.7 - 33SL (5.1.1-22) installed from Fdroid.

In both cases the device is *DEFINITELY* connected to the access point. For example I debug my VOIP performance by making a test call and wandering around the house while looking at access point signal levels in wifi analyzer, so data is being constantly transmitted and received over the wifi.

In the settings -> device -> status menu it shows only IP addresses not any kind of signal levels. I prefer not to upload the IPv6 addresses of my personal WiFi network but I can tell you there is a list of 2 global addresses and 2 ULA addresses, including standard SLAAC addresses as well as what I assume are some kind of android privacy random addresses and the 192.0.0.5 address created by the Android CLAT 464xlat daemon.

**Comment by dlakelan** [comment]
Ah I see the special phone code you're supposed to dial...  Doing that I see 
Wifi state: enabled
Network state: connected to <myssidhere>
supplicant state: COMPLETED
RSSI: -32

ping tests pass.

everything else blank...

**Comment by VREMSoftwareDevelopment** [comment]
Press "refresh stats" button to fill all the information.

Does the information provided matches your other WiFi information?

You can provide screenshots and hide any private information that you do not want to show.

**Comment by dlakelan** [comment]
Here's a screenshot. I've blanked out the SSID and MAC address low order bits... but they all make perfect sense in my case. I'm connected to the SSID I expect to be connected to. Note that it shows ip address 0.0.0.0 there is no IPv4 address involved here as the network is IPv6 only.

![screenshot_20171109-073624](https://user-images.githubusercontent.com/4332910/32614498-452642ae-c522-11e7-80c7-6073618709a1.png)

**Comment by VREMSoftwareDevelopment** [comment]
Next release will have this feature available.
Current release V1.8.7 Google Play Store.
