### ISSUE TITLE
2.4Ghz: 40Mhz show as 20Mhz (Android marshmalow 6.0/phone Meizu m2)

### ISSUE THREAD

**Issue by Sharabaddin** [VREMSoftwareDevelopment/WiFiAnalyzer#144]
![photo_2017-12-13_16-25-42](https://user-images.githubusercontent.com/10178672/33943628-5276c04e-e022-11e7-8e3d-a41e63fefe72.jpg)

My wi-fi router(Netis WF2411E, frimware:V2.4.41346)
![screenshot from 2017-12-13 16-27-48](https://user-images.githubusercontent.com/10178672/33943750-99fb95ca-e022-11e7-9d6e-3cfede427bc4.png)

![image](https://user-images.githubusercontent.com/10178672/33943831-dcf0aff0-e022-11e7-8bb5-ffad6ab364d0.png)

![image](https://user-images.githubusercontent.com/10178672/33943853-f28ca7e2-e022-11e7-86ff-4aa82194e06a.png)

**Comment by Sharabaddin** [comment]
Fast fix: if connected speed 135 mbps- show 40MHz

**Comment by Sharabaddin** [comment]
Im sory version Lolipop)

**Comment by Rikk** [comment]
Why you closed this? The problem seems true.
