### ISSUE TITLE
Vendors search

### ISSUE THREAD

**Issue by VREMSoftwareDevelopment** [VREMSoftwareDevelopment/WiFiAnalyzer#145]
Add ability to search vendors database by vendor name or mac address

**Comment by VREMSoftwareDevelopment** [comment]
Next release will have this feature available.
Current release V1.8.8 Google Play Store.

**Comment by Rikk** [comment]
Vendor search is case sensitive, ie. we need to type all in caps because all company names are uppercase. Wouldn't it be a good idea to make it case insensitive? Thank you ☺
