### ISSUE TITLE
Zoom on the chart?

### ISSUE THREAD

**Issue by smarcu** [VREMSoftwareDevelopment/WifiAnalyzer#15]
I don't know if this sounds as a good feature but it will be nice to have some zoom capabilities on the charts, especially on the tablet where is more area to view.
thank you!

**Comment by VREMSoftwareDevelopment** [comment]
Thanks, for you quick reply.

Would you like to put this into GitHub?

Thanks,

Vadim

**Comment by smarcu** [comment]
it is on github … or what exactly do you mean by to put it in to github ?
silviu

**Comment by VREMSoftwareDevelopment** [comment]
You have different choices: add an issue or change code. :)
