### ISSUE TITLE
Latitude Longitude in Exports

### ISSUE THREAD

**Issue by mailysll** [VREMSoftwareDevelopment/WiFiAnalyzer#152]
This is a great tool, thank you. I used it today for checking APs signal strength while walking but using a second tool to collect data. My goal is to create an outdoor heat map. I don't know if it's possible, it would be even more useful for me if you could add 2 fields, latitude and longitude of scans in export.

**Comment by VREMSoftwareDevelopment** [comment]
@mailysll We are not planning to implement this feature. You are welcome to create a PR.
When we don't have an opportunity or time to implement a feature, we encourage developers to fork the project and become a contributor. It would be great to add new contributors to this project.

**Comment by evgenbn** [comment]
Since Android 9 Pie requires the location please add a function to export GPS coordinates. Unfortunately I have no development experience, I would help if I could.
