### ISSUE TITLE
Do you support 802.15 as well?

### ISSUE THREAD

**Issue by EAwesomeK** [VREMSoftwareDevelopment/WiFiAnalyzer#154]
### Note
Some behaviour only occurs on certain devices or versions of Android, please provide the following screenshots/information Device/Android OS (Settings → About Phone) and WiFi Analyzer version (Menu -> About)

**Comment by VREMSoftwareDevelopment** [comment]
Application relies on the Android Device, Android OS and provided Android APIs to support different protocols.

Please see [Android API](https://developer.android.com/reference/packages.html)
