### ISSUE TITLE
Logo / icon design proposition

### ISSUE THREAD

**Issue by ideosprocess** [VREMSoftwareDevelopment/WiFiAnalyzer#157]
Hello ,
I designed a new logo for your application [HERE](https://steemit.com/utopian-io/@ideosprocess/proposal-logo-and-iconfor-applications-wifianalyzer) , so let me know if you want any changes.
Thank you.

**Comment by VREMSoftwareDevelopment** [comment]
Please create a pull request to propose and collaborate on changes to a repository.
To find how to do it, please see the following: [Creating a pull request](https://help.github.com/articles/creating-a-pull-request/)
