### ISSUE TITLE
Faster update time for graphs

### ISSUE THREAD

**Issue by hackerb9** [VREMSoftwareDevelopment/WiFiAnalyzer#159]
It'd be nice if graphs could update more than once a second, so I don't have to pause after each antenna adjustment. WiFi hardware can get new signal quality data many times per second. How about an option to have the graphs update "as fast as possible"?

I could imagine someone saying CPU usage would be an issue. If so, perhaps there's a way to block while waiting for the WiFi hardware to have fresh data.

Another possible objection would be that graphs would scroll too fast. A good solution would be to switch to a graph that uses logarithmic time for the x-axis. Recent changes would take up the most space, with older samples essentially getting averaged together so they take up less.

**Comment by VREMSoftwareDevelopment** [comment]
This is an interesting idea for a feature. Unfortunately all current contributors are busy with other work. When we don't have an opportunity to implement a feature, we encourage developers to fork the project and become a contributor.

**Comment by VREMSoftwareDevelopment** [comment]
We will not implement this feature, since it conflicts with #182.

**Comment by hackerb9** [comment]
I'm sorry if I'm just missing something, but I don't see this as conflicting with #182. How about having the refresh rate start out high (many times per second) and then slow down only if the hardware can't handle it?
