### ISSUE TITLE
Allowed Channels per Locale

### ISSUE THREAD

**Issue by VREMSoftwareDevelopment** [VREMSoftwareDevelopment/WifiAnalyzer#16]
Show only channels allowed in locale

**Comment by VREMSoftwareDevelopment** [comment]
Current release V1.3.1.40 
This feature will be available in the next release

**Comment by 4elta** [comment]
> Show only channels allowed in locale

i don't think it's a good idea to link a user's locale to something other than _language_. 
keep in mind that people can and do set their **locale** to something different than their actual **location** (eg. location: japan; locale: `en_UK`).

also, imho there is no reason to only show the _allowed_ channels. it's not like you (the app's developer) can be sued by users who configured their network devices incorrectly (against their country's regulations/laws).

thanks for your work.

**Comment by VREMSoftwareDevelopment** [comment]
Good point.
