### ISSUE TITLE
Not working on Huawei P20 Pro

### ISSUE THREAD

**Issue by ptnik** [VREMSoftwareDevelopment/WiFiAnalyzer#164]
### Expected behaviour
Show WiFi / AP info

### Actual behaviour
Stuck at "scanning" with spinning wheel, stating "no Data"
(This is with location service enabled, just in case)

### Steps to reproduce the behaviour
Every time I try to run the app.
Additional note: the "other" WiFi Analyzer app also has the same behavior, not showing any data - so I suspect it might have something to do with the system itself (maybe some extra permissions required?)

### Note
WiFiAnalyzer: 1.8.10 - 36S (8.1.0-27)
Android 8.1.0 - EMUI 8.1.0

**Comment by VREMSoftwareDevelopment** [comment]
Hi @ptnik 

- Was application installed on the primary/owner account?
- Is this your device specifications: P20 Pro (HWCLT) | Huawei | CPU - HiSilicon | CPU model - KIRIN970?

Thank you,
The VREM Development Team

**Comment by ptnik** [comment]
Yes, on the primary/owner (and only) account.
Model CLT-L29 (8.1.0.106)  Kirin 970

**Comment by BROBIRD** [comment]
The same problem on Huawei Honor 9 （STF-AL10） , it was working on beta channel firmware, but failed on release channel.

**Comment by VREMSoftwareDevelopment** [comment]
Looks like this is a very specific issue to Huawei Android version 8.+.
Sorry to say, we do not have these specific hardware available for testing.
We will continue the investigation.

**Comment by BROBIRD** [comment]
Maybe you can try to send e-mails to Huawei about this. I'll try to contact them for more information.

**Comment by VREMSoftwareDevelopment** [comment]
@ptnik @BROBIRD

Experimental application that may help with this issues is deployed to the play store under private BETA testing program. We would like to test it first, before releasing it to the public.

Can you please provide your email address via email that we can add your to the testing program?

Thank you,
The VREM Development Team

**Comment by BROBIRD** [comment]
With pleasure. I have sent an e-mail to you.

**Comment by ptnik** [comment]
Done

**Comment by ptnik** [comment]
The beta version is working! :)

**Comment by VREMSoftwareDevelopment** [comment]
The application that solve this specific issue is available [here](https://play.google.com/apps/testing/com.vrem.wifianalyzer.location) under open beta testing program.
