### ISSUE TITLE
Application Icon/Logo changes

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [VREMSoftwareDevelopment/WiFiAnalyzer#166]
Please add support for icon shape
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html
https://material.io/guidelines/style/icons.html

**Comment by VREMSoftwareDevelopment** [comment]
Please create a pull request to propose and collaborate on changes to a repository.
To find how to do it, please see the following: [Creating a pull request](https://help.github.com/articles/creating-a-pull-request/)

**Comment by c-e-p-x-u-o** [comment]
It's just a feature request, I don't have real changes.

**Comment by VREMSoftwareDevelopment** [comment]
Currently there are no plans to implement this feature.
When we don't have an opportunity to implement a feature, we encourage developers to fork the project and become a contributor.
It would be great to add another contributor to this project.

**Comment by c-e-p-x-u-o** [comment]
Please reopen this bug until it is not fixed!

**Comment by VREMSoftwareDevelopment** [comment]
@c-e-p-x-u-o 
Are you planning to implement this feature and submit a pull request?

**Comment by c-e-p-x-u-o** [comment]
Yep!

**Comment by amirdesaingrafis** [comment]
Hello, I want to contribute to this awesome project, and I have a new logo design for you, if you allowed I will send to you :)

**Comment by c-e-p-x-u-o** [comment]
@VREMSoftwareDevelopment: Provide svg source please.

**Comment by VREMSoftwareDevelopment** [comment]
Android "svg" file is available in the repository [ic_app_green_800_48dp.xml](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/blob/feature/app/src/main/res/drawable/ic_app_green_800_48dp.xml).

Here are a few links that maybe helpful:
- [Add Multi-Density Vector Graphics Using Android studio](https://developer.android.com/studio/write/vector-asset-studio)
- [Create App Icons with Image Asset Studio](https://developer.android.com/studio/write/image-asset-studio)

**Comment by Tobaloidee** [comment]
Can I help in making the app icon an adaptive icon? I am a graphic designer and I want to contribute to these great project.

**Comment by Tobaloidee** [comment]
I can make a proposal for a new app icon design also if it's an option.

**Comment by c-e-p-x-u-o** [comment]
@VREMSoftwareDevelopment why have you deleted a comment from amirdesaingrafis?

**Comment by c-e-p-x-u-o** [comment]
```
$ wget https://raw.githubusercontent.com/VREMSoftwareDevelopment/WiFiAnalyzer/feature/app/src/main/res/drawable/ic_app_green_800_48dp.xml -O ic_app_green_800_48dp.svg
$ inkscape ic_app_green_800_48dp.svg
```

```
Failed to load the requested file ic_app_green_800_48dp.svg
```

**Comment by c-e-p-x-u-o** [comment]
@Tobaloidee you should not ask permission to help. Just make the icon!

**Comment by Tobaloidee** [comment]
@c-e-p-x-u-o  okay I will post it here asap. thanks!

**Comment by VREMSoftwareDevelopment** [comment]
@Tobaloidee 
Please create a pull request to propose and collaborate on changes to a repository.
To find how to do it, please see the following: [Creating a pull request](https://help.github.com/articles/creating-a-pull-request/)

**Comment by VREMSoftwareDevelopment** [comment]
@c-e-p-x-u-o 
As mentioned in previous comment, the file [ic_app_green_800_48dp.xml](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/blob/feature/app/src/main/res/drawable/ic_app_green_800_48dp.xml) is in **"Android svg"** format.  Android applications require and use this format.

Please take a look at explanations provided in the following links:
- [Add Multi-Density Vector Graphics Using Android studio](https://developer.android.com/studio/write/vector-asset-studio)
- [Create App Icons with Image Asset Studio](https://developer.android.com/studio/write/image-asset-studio)

Please convert "android svg" file into true svg formatted file in order to use it in Inkscape.

**Comment by yanokwa** [comment]
Wow! This looks really great, @Tobaloidee!

My (unsolicited) feedback is that the shadow on the right side is a bit too much. I think a simple drop shadow around the white elements would look better to my eye.

**Comment by Tobaloidee** [comment]
I will edit and update my post Sir! I am so glad that you liked it..I will show here first after I edit and when ita good i will make the adaptive icon mockups.

**Comment by c-e-p-x-u-o** [comment]
Nice! I like it too.

**Comment by Tobaloidee** [comment]
Hi Sir @yanokwa , here it is! :)

![wifi analyzer all drop hires-02](https://user-images.githubusercontent.com/36028424/39647091-25efaad2-5010-11e8-9112-aa55f577e2b6.png)
![wifi analyzer all drop hires-03](https://user-images.githubusercontent.com/36028424/39647133-4ac1548c-5010-11e8-8428-16b4c4f52c40.png)


Thanks also Sir @c-e-p-x-u-o  glad that you liked it!

**Comment by yanokwa** [comment]
I talked to @lognaturel and she said that your first icon is more standard on Android these days and that I'm just old-fashioned 😂

I think @ @VREMSoftwareDevelopment should decide, but I think we should go with your first one!

**Comment by VREMSoftwareDevelopment** [comment]
@Tobaloidee 

First image looks good. 

1. Is there are anyway to preserve wi-fi icon as green (not background)?
We were trying to convent the message of good quality wi-fi connection by choosing green color?

2. Will new icon comply to GPLv3 copyright license?
The application is licensed under [GPLv3](https://www.gnu.org/licenses/gpl-3.0.html). 
Current icon is material design icon and is licensed under [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0). 
The new/proposed icon is licensed under a [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0).

Thank you,

VREM Development Team

**Comment by Tobaloidee** [comment]
hi Sir @VREMSoftwareDevelopment 

I made a version based from the original color sir.

![wifi analyzer-05](https://user-images.githubusercontent.com/36028424/39675103-e17cd346-5188-11e8-8ae0-5fbc89cab28b.png)
![wifi analyzer-06](https://user-images.githubusercontent.com/36028424/39675104-e572909e-5188-11e8-9a38-0ed950ac34fa.png)
![ezgif com-crop](https://user-images.githubusercontent.com/36028424/39675105-ed97e012-5188-11e8-919d-db420c6df012.gif)

All I want is to give this design of mine to Wifi Analyzer Sir. for free you can use it in whatever/however you want it. I updated my google drive with this new version Sir.

**Comment by Tobaloidee** [comment]
I removed the license Sir in my comment. Please tell me sir which is the best way in turning this design over to the project.

**Comment by VREMSoftwareDevelopment** [comment]
Hi @Tobaloidee 

Out of the three choices available, your first logo/icon was picked by the team.
Please create a pull request with the first logo/icon.

Thank you,

VREM Development Team

**Comment by Tobaloidee** [comment]
Hi @VREMSoftwareDevelopment 

Thanks so much for accepting my icon/design proposal for WiFI Analyzer. If you still need any help or have any sug

**Comment by VREMSoftwareDevelopment** [comment]
@c-e-p-x-u-o work by @Tobaloidee  is merge into feature branch.
Please find all required icon files in the images or images\svg folders.

**Comment by c-e-p-x-u-o** [comment]
(:

**Comment by VREMSoftwareDevelopment** [comment]
new/updated icons (including adaptive and legacy icons) will be available in the next release.
