### ISSUE TITLE
New logo desing for WifiAnalyzer

### ISSUE THREAD

**Issue by sametceylan** [VREMSoftwareDevelopment/WiFiAnalyzer#167]
Hello sir, my name is Samet Ceylan and I am a designer. If you want and let me, I want to design a creative logo for WifiAnalyzer. I want you to know that I will do it for you. I do not want any compensation. If you would like me to design and if you have any particular detail, please contact me.

**Comment by VREMSoftwareDevelopment** [comment]
Please create a pull request to propose and collaborate on changes to a repository.
To find how to do it, please see the following: [Creating a pull request](https://help.github.com/articles/creating-a-pull-request/)
