### ISSUE TITLE
Green Wi-Fi signals in logo should be centered and reduced in size

### ISSUE THREAD

**Issue by yanokwa** [VREMSoftwareDevelopment/WiFiAnalyzer#169]
Thank you for making this app. I found it very useful and this issue is extremely minor but I figured I'd file it anyway.

### Expected behaviour
The green Wi-Fi signals in the logo are perfectly centered and the distance from the borders feel comfortable.

### Actual behaviour
The Wi-Fi signals in the icon are not vertically centered. It needs to be bumped up a few pixels. The signals feel a little too close to the left and right borders.

### Steps to reproduce the behaviour
Install the app, look at the app icon, and be extremely nitpicky!

### Please provide a screenshot of the issue you are reporting
![screen shot 2018-04-29 at 10 25 31](https://user-images.githubusercontent.com/32369/39409203-b1fa5586-4b97-11e8-9424-87b62aa69c1f.png)

### How I can help
If the maintainers attach the source image to this issue, I'm glad to make adjustments and send in a PR

**Comment by VREMSoftwareDevelopment** [comment]
Source images are part of the repository and can be found [here](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/tree/feature/app/src/main/res) under `mipmap-*` folders

**Comment by amirdesaingrafis** [comment]
Hello, I want to contribute to this awesome project, and I have a new logo design for you, if you allowed I will send to you :)

**Comment by VREMSoftwareDevelopment** [comment]
@amirdesaingrafis 
Please create a pull request to propose and collaborate on changes to a repository.
To find how to do it, please see the following: [Creating a pull request](https://help.github.com/articles/creating-a-pull-request/)

**Comment by VREMSoftwareDevelopment** [comment]
Any current or future Logo work will be move to #166
This issue will be closed, since it is a duplicate and may conflict with work being done on  #166.
