### ISSUE TITLE
Catalan Translation

### ISSUE THREAD

**Issue by Solatec** [VREMSoftwareDevelopment/WiFiAnalyzer#171]
### Note
Some behaviour only occurs on certain devices or versions of Android, please provide the following screenshots/information Device/Android OS (Settings → About Phone) and WiFi Analyzer version (Menu -> About)

### How I can help
I want to translate the application into Catalan. Can you duplicate the Spanish language folder? And I start the translation.
Thank you so much!

**Comment by VREMSoftwareDevelopment** [comment]
Please use Android Studio to create desired language translation.

Here is a how-to link:
[Localize the UI with translations editor using Android Studio ](https://developer.android.com/studio/write/translations-editor).
