### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by IzzySoft** [VREMSoftwareDevelopment/WifiAnalyzer#18]
would you consider attaching the `.apk` file with your `releases/` here on Github – so people running Google-free devices w/o Playstore access can grab your app? I'd then even offer to [add it here](https://android.izzysoft.de/repo), so your users can get updates automatically using the F-Droid client.

Thanks in advance!

**Comment by VREMSoftwareDevelopment** [comment]
One of our items is to put the application into [F-Droid](https://f-droid.org/) catalogue.  At the moment, we have higher priority items that we are working on. We also want to make sure that our application complies to [F-Droid inclusion policy](https://f-droid.org/wiki/page/Inclusion_Policy)  and gets [build by F-Droid]( https://f-droid.org/wiki/page/FAQ_-_App_Developers#Will_my_app_be_built_from_source.3F).

**Comment by IzzySoft** [comment]
That's even better then (to have it in the main catalog). If you wish to have it included with my repo *until it's picked up by F-Droid* my offer stands (you'd just need to attach the `.apk` to the `releases/` and let me know). As soon as it made its way to the main catalog, I'd remove it from my repo again anyway as soon as I notice (to avoid confusion with different signatures; dropping me another note then would speed up that step).

**Comment by codedust** [comment]
Hey! Found your app on F-Droid! Thanks for the great work!

**Comment by VREMSoftwareDevelopment** [comment]
Done
