### ISSUE TITLE
Issue using 1 second scan interval

### ISSUE THREAD

**Issue by jidanni** [VREMSoftwareDevelopment/WiFiAnalyzer#182]
Stop showing the no data screen. It is very annoying. Just wait a little longer and the problem will be solved. With many strong channels, every few seconds one still sees the no data screen.

### Expected behaviour

Only showing graphs

### Actual behaviour

Mostly showing graphs, but interrupted by "No Data" screens every few seconds.

### Steps to reproduce the behaviour

In a place with many signals, many wifis, use the app on ASUS Android 8.0.

### Please provide a screenshot of the issue you are reporting

Problem usually goes away before the user has a chance to make a screenshot. 
OK, see below.
### Note
Some behaviour only occurs on certain devices or versions of Android, please provide the following screenshots/information Device/Android OS (Settings → About Phone) and WiFi Analyzer version (Menu -> About)

#183 has version snapshot.

### How I can help

Especially on fast cellphones, change the algorithm to notice that there is no way "No Data" could be correct, as the airwaves have plenty data.

**Comment by jidanni** [comment]
With many strong channels, every few seconds one still sees the no data screen.

**Comment by VREMSoftwareDevelopment** [comment]
@jidanni 
In order to investigate the issue you are trying to report, please provide missing information in the above template.

**Comment by jidanni** [comment]
![screenshot_20180601-084003](https://user-images.githubusercontent.com/1230959/40815380-af24e524-6578-11e8-94a2-8821ce967739.jpg)

![screenshot_20180601-084019](https://user-images.githubusercontent.com/1230959/40815371-a2ab29d4-6578-11e8-91de-2bc3634d215b.jpg)

**Comment by VREMSoftwareDevelopment** [comment]
Can you please provide Scan Interval setting value?

**Comment by VREMSoftwareDevelopment** [comment]
Looks like the phone hardware is having issues with trying to scan every second.
The fix for this issue will be available in the next release.
