### ISSUE TITLE
Version info background dark

### ISSUE THREAD

**Issue by jidanni** [VREMSoftwareDevelopment/WiFiAnalyzer#183]
It is hard to read the version number, because it is black on gray, instead of black on white
![screenshot_20180601-084104](https://user-images.githubusercontent.com/1230959/40815355-78f748d4-6578-11e8-8984-2838bc652a31.jpg)

**Comment by VREMSoftwareDevelopment** [comment]
Light Theme expected behavior.
Duplicate #117
