### ISSUE TITLE
Cannot copy version info text

### ISSUE THREAD

**Issue by jidanni** [VREMSoftwareDevelopment/WiFiAnalyzer#184]
### Expected behaviour
Can copy version info

### Actual behaviour
Cannot copy version info, and must instead take a snapshot.

### Steps to reproduce the behaviour
Long-press you finger on the version info.

# Please provide a screenshot of the issue you are reporting
#183

### Note
Some behaviour only occurs on certain devices or versions of Android, please provide the following screenshots/information Device/Android OS (Settings → About Phone) and WiFi Analyzer version (Menu -> About)

See #183. ASUS Android 8.0.

**Comment by VREMSoftwareDevelopment** [comment]
We do not see a great benefit in adding this feature, since taking a screenshot works perfectly fine. Also when we don't have an opportunity to implement a feature, we encourage developers to fork the project and create a pull request.

**Comment by jidanni** [comment]
(OK, just noting that using a screenshot wastes about 10,000 to 100,000 times more bytes.)
