### ISSUE TITLE
Not working on Android 9

### ISSUE THREAD

**Issue by pcartwright81** [VREMSoftwareDevelopment/WiFiAnalyzer#188]
**Describe the bug**
Scan will not show any available AP.

**To Reproduce**
1. Go to 'Wifi Analyzer'
2. Click on 'Access Points'

**Expected behavior**
Show Available AP

**Screenshots**
![scan page](https://user-images.githubusercontent.com/2352477/41201899-25b40044-6c86-11e8-8880-9dccb80f48e5.png)

**Note**
Some behaviour only occurs on certain devices or versions of Android, please provide the following screenshots/information Device/Android OS (Settings → About Phone) and WiFi Analyzer version (Menu -> About)

Android Version 9
App Version 1.9.1

![android version](https://user-images.githubusercontent.com/2352477/41201874-c9325154-6c85-11e8-9b31-4e682fef0f3c.png)
![app version](https://user-images.githubusercontent.com/2352477/41201875-c944bf24-6c85-11e8-95a0-1135604647a8.png)

**Additional context**
Can not give location permission in app settings because it says no permissions requested.  Additionally app Is not available under location=> app-level permissions.

**Comment by VREMSoftwareDevelopment** [comment]
@pcartwright81 
In order to investigate the issue you are trying to report, please provide missing information in the above template.

**Comment by pcartwright81** [comment]
Thanks!  It works great.  I didn't even think to check if there was a beta version.  Location permission is checked for at startup as expected.  I understand not supporting Android 9, but my main reason for writing it up was I did an issue search, and my device was not a Huawei.  Of course most people don't check the open and closed issues.
