### ISSUE TITLE
Can no longer enter text in SSID Filter TextView

### ISSUE THREAD

**Issue by reggiepdavison** [VREMSoftwareDevelopment/WiFiAnalyzer#191]
Cannot enter any text in the SSID Filter field.

Steps:
1. Click on Filter icon.
2. Click/tap on SSID Filter text field.

Keyboard does not pop up.

Expected Behaviour:
Should display keyboard and allow you to enter SSID filter text.

**Comment by VREMSoftwareDevelopment** [comment]
@reggiepdavison 

Please provide the following information:
- Device/Android OS
- Application version

**Comment by reggiepdavison** [comment]
Android version 7.0
Security patch: March1, 2018

Samsung Galaxy S6.

P

**Comment by VREMSoftwareDevelopment** [comment]
Next release will have this bug fixed.
