### ISSUE TITLE
The connection section does not show when connected to an hidden ssid network

### ISSUE THREAD

**Issue by sebma** [VREMSoftwareDevelopment/WiFiAnalyzer#194]
[How to report a bug](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Feedback)

**Describe the bug**
IP and bitrate don't show when connected to a hidden ssid network

**To Reproduce**
1. Go to 'WiFiAnalyer'
2. Click on 'Access Points'
3. Select/Look at the line who's ssid is **`***`**

**Expected behavior**
IP and bitrate show up in the Access Point **`***`** when connected to a hidden ssid network

**Screenshots**

**Note**
Android 5.0 on Samsung Galaxy Note 3
WiFiAnalyser v1.9.2

**Comment by VREMSoftwareDevelopment** [comment]
This is not a bug, it is an expected behavior. IP Address and Link speed is only available in the connection section.

**Comment by sebma** [comment]
@VREMSoftwareDevelopment Hi, this connection section is the first row of all the visible "Access Points" ?

If so, this connection section only appears when connected to non hidden ssid network, is this normal ?

**Comment by VREMSoftwareDevelopment** [comment]
Connection section is available on the following screens: `Access Points`, `Channel Rating`, `Channel Graph` and `Time Graph`.

Connection section is visible when device is connected to the WiFi and `Connection Display` option in the setting menu has one of the following selections: `Complete` or `Compact`.

Please note, that  `***` will never appear in the connection section since the device will be connected and will know `SSID` of the access point.

Feature graphics have a very good example of connection section.

Regards,

VREM Development Team.

**Comment by sebma** [comment]
@VREMSoftwareDevelopment Thanks for the explanation.

I guess the title of my issue was incorrect, it should be "The connection section does not show when connected to an hidden ssid network".

May I create a new issue for that ?

**Comment by sebma** [comment]
@VREMSoftwareDevelopment I was asking your permission to create a new one :)

Thank you for reopening it :)

**Comment by VREMSoftwareDevelopment** [comment]
@sebma 

Please provide sample screenshots clearly showing the issue.
Remember that application scans the connection and access points based on the scan interval setting, so please give the application enough time to find all the necessary information.

**Comment by sebma** [comment]
@VREMSoftwareDevelopment I'll do that as soon as I get back home tonight.

In the meantime, do you know an F-droid app to take screenshots of an app ?

**Comment by sebma** [comment]
![](imap://sebmansfeld%40yahoo%2Efr@imap.mail.yahoo.com:993/fetch%3EUID%3E/INBOX%3E348058/;section=2?part=1.2&filename=Screenshot_2018-06-19-23-48-56.png)

**Comment by sebma** [comment]
![image](https://user-images.githubusercontent.com/4569306/41626455-a0bfcbe0-741c-11e8-92f0-85c90dd4e7e2.png)

**Comment by sebma** [comment]
@VREMSoftwareDevelopment As you can see there is no `connection section`.

Please fetch the screenshot and let me know so I can remove it.

**Comment by VREMSoftwareDevelopment** [comment]
@sebma 

Please provide additional screenshot(s) from Android OS WiFi settings section clearly displaying current connection information.

After that disable hidden ssid feature on you access point and provide the same screenshots again.

If you have privacy concern regarding screen shoots, do not post them on GitHub, just email them to us.

Thanks,

VREM Development Team.

**Comment by sebma** [comment]
@VREMSoftwareDevelopment OK, I'll do when I get back home (It's 2PM in France at the moment)

**Comment by sebma** [comment]
@VREMSoftwareDevelopment Can you please give an email to which I will send the screenshot(s) ?

**Comment by sebma** [comment]
@VREMSoftwareDevelopment Hi, it was 2AM in France when I received your answer, so I'll have to wait when I get back home tonight to send you the screenshots.

**Comment by sebma** [comment]
@VREMSoftwareDevelopment Hi, I've just sent you the screenshots.

Hope this helps.

**Comment by VREMSoftwareDevelopment** [comment]
@sebma 

It would be helpful, if you can provide more information.
- Enable developer options on your phone
- Enable Wi-Fi verbose logging in the developer options
- Provide screenshots from Android OS WiFi settings section (not application) clearly displaying current connection information. (with enable SSID broadcasts and without)
