### ISSUE TITLE
Incorrect Channel-Width and speed on Chromebook Pixel

### ISSUE THREAD

**Issue by EVSB18** [VREMSoftwareDevelopment/WiFiAnalyzer#195]
I have installed the app in my Google Chromebook Pixel, and It works but it shows incorrect channel width and speed, because all Wifi Access Points are shown with 20 MHz, and data rate of 100 Mbps.
Version: 1.9.2
Chrome OS Version 67.0.3396.87 (Official Build) (64-bit)
Platform 10575.55.0 (Official Build) stable-channel eve
Firmware Google_Eve.9584.107.0
Channel: Currently on stable

**Comment by VREMSoftwareDevelopment** [comment]
This is an Android OS application, there are no plans to support Chrome OS.
When we don't have an opportunity to implement a feature, we encourage developers to fork the project and become a contributor.
It would be great to add another contributor to this project.

Thank you,
The VREM Development Team
