### ISSUE TITLE
AP manufacturer names cut off after 10 chars

### ISSUE THREAD

**Issue by thatso** [VREMSoftwareDevelopment/WiFiAnalyzer#197]
Version: 1.9.2 - 40S (7.0 - 24)
Platform: Android 7.0 on Huawei P9 lite

Tested with both F-Droid and GooglePlay versions: the manufacturer name of APs is cut off after 10 chars. Earlier versions stated i. e. "CISCO MERAKI" while now it reads "CISCO MERA".

**Comment by Graham-Foster** [comment]
Thanks for logging this. I can reproduce this issue on my device as well, though I don't know the history of seeing a longer text field in past versions. Are you able to make a pull request with an update? I'm sure the VREM team would appreciate the support

**Comment by thatso** [comment]
Sorry, I'm no programmer. I've only reported my observation about the cut-off names.

**Comment by VREMSoftwareDevelopment** [comment]
It was reported that on the smaller screens the 12 character vendor name would wrap to the next line, the change to the length from 12 to 10 was implement to fix this issue. 
Full vendor name is still available in pop-up detailed displays and in the vendor search.

**Comment by thatso** [comment]
Strange. At least on my device there is space for roughly 6 more chars for vendor name in the AP list - see unused space circled in red in screenshot.
Maybe you could consider writing full names in landscape mode? Until now, the additional space is not used at all.

![screenshot](https://user-images.githubusercontent.com/40745263/42414222-d5cea974-8230-11e8-830a-269efe664507.png)
