### ISSUE TITLE
Location Access

### ISSUE THREAD

**Issue by pysklo** [VREMSoftwareDevelopment/WiFiAnalyzer#200]
Describe the bug
On Android P DP3 the app doesn't ask for any permissions, making the app unusable.

To Reproduce
-Download Wifi Analyzer from the play store.
-Launch the app.
-No popup asking for permissions

Expected behavior
-First time opening the app, a dialog box should appear asking for permissions.
-The app will then Be able to run as expected.

Note
Android P DP3 OnePlus 6
WiFiAnalyser v1.9.2

**Comment by VREMSoftwareDevelopment** [comment]
Duplicate #188
