### ISSUE TITLE
Android 9 Support

### ISSUE THREAD

**Issue by VREMSoftwareDevelopment** [VREMSoftwareDevelopment/WiFiAnalyzer#202]
Please try the BETA version of the application in the Google Play Store.

[Android WiFi Scan Restrictions](https://developer.android.com/guide/topics/connectivity/wifi-scan#wifi-scan-restrictions)

References:
#188
#199
#201

**Comment by Jon8RFC** [comment]
Yes, the beta works for me.  When will the functionality be moved over to the non-beta?
