### ISSUE TITLE
Hidden SSID not shown on Android Pie

### ISSUE THREAD

**Issue by pingu8007** [VREMSoftwareDevelopment/WiFiAnalyzer#206]
Access point without SSID broadcasting didn't show after upgrade to Android Pie, unless the SSID was connected before and is saved.

Probably an issue related to the new limitation on WiFi scanning.

**Comment by VREMSoftwareDevelopment** [comment]
Application is relying on the Access Point information provided by Android API.
Based on your information, we would assume that Android API does not provide hidden SSID, unless connection information was saved before.
[https://developer.android.com/reference/android/net/wifi/ScanResult](https://developer.android.com/reference/android/net/wifi/ScanResult)
