### ISSUE TITLE
Should the Channel Rating be reversed?

### ISSUE THREAD

**Issue by kuba-orlik** [VREMSoftwareDevelopment/WiFiAnalyzer#209]
In the "Channel Rating" view, we can see the ranking for each WiFi channel, based on the amount of access points using that channel:

![photo_2018-10-01_16-22-48](https://user-images.githubusercontent.com/2697916/46294679-97f54500-c596-11e8-8ce3-abfa1048f05c.jpg)

But something seems off - channels with the best ranking are the channels that are used by the most access points... shouldn't it be reversed? So that the best channels are the ones used the *least*?

**Comment by VREMSoftwareDevelopment** [comment]
The channel rating algorithm is working as expected. The algorithm uses different criteria to rate. The number of the access points is only one of the criteria. You are welcome to review the algorithm.
