### ISSUE TITLE
Graphs don't update after opening settings 

### ISSUE THREAD

**Issue by spottenn** [VREMSoftwareDevelopment/WiFiAnalyzer#212]
[How to report a bug](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Feedback)

**Please search issues (open and closed) to see the issues has already been reported.**

**Describe the bug**
When viewing either graph, if you open settings, and then hit back, the graph no longer updates or responds to user input. The issue also happens in the channel rating view and also happens with the about page.

**To Reproduce**

**Screenshots**

![screenshot_20181021-133327](https://user-images.githubusercontent.com/17463126/47271598-1f036080-d538-11e8-9e1d-38c59819401a.png)

Device: Google Pixel XL
Android version: 9
App version: 2.0.1 42S (9-28)

**Additional context**

**Comment by VREMSoftwareDevelopment** [comment]
The fix will be available in the next release

**Comment by VREMSoftwareDevelopment** [comment]
@spottenn Please try new BETA version available in Play Store
