### ISSUE TITLE
Doesn't work on android p

### ISSUE THREAD

**Issue by Wan-Shi-Tong** [VREMSoftwareDevelopment/WiFiAnalyzer#215]
[How to report a bug](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Feedback)

**Describe the bug**
Doesn't work on android p

**To Reproduce**
Install the app, open and it doesn't detect any networks.

**Additional context**
I think you need to add location permission in the manifest file for it to work properly.

**Comment by VREMSoftwareDevelopment** [comment]
Duplicate #211
