### ISSUE TITLE
cannot install on any device through playstore.

### ISSUE THREAD

**Issue by nldudok1** [VREMSoftwareDevelopment/WifiAnalyzer#22]
If I try to install it through the android playstore website, it tells me that none of my devices can run/install this app.
What special requirements or android version does the app need/request?
I have a samsung galaxy ace 2 (adroid 4.4), and a xiami redmi note 2 (android 5.02), and samsung galaxy tab 2, and a blu dash 3.5.

**Comment by VREMSoftwareDevelopment** [comment]
WiFi Analyzer is written for Android 5.1+. 
The best thing is to use Play Store on the device. It will show only applications that can be installed on your device.
