### ISSUE TITLE
Location Service Permission requirements need better information in the app

### ISSUE THREAD

**Issue by quantumpacket** [VREMSoftwareDevelopment/WiFiAnalyzer#220]
The latest update I got now requires network location access. Denying it causes the app to close. Why is this permission now needed and why is it required?

[How to report a bug](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Feedback)

**Please search issues (open and closed) to see the issues has already been reported.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Note**
Some behaviour only occurs on certain devices or versions of Android, please provide the following screenshots/information Device/Android OS (Settings → About Phone) and WiFi Analyzer version (Menu -> About)

**Additional context**

**Provide Device/Android OS information**

**Comment by ZeroDot1** [comment]
I can confirm the problem, I looked at it, the app doesn't show any networks anymore.

**Comment by VREMSoftwareDevelopment** [comment]
@quantumpacket, @ZeroDot1 

Please fill the missing information in the request template we have provided above, this helps us to investigate and spend less time on the issues.

"Requires Network Location" do you mean "Location Service Permission" (ACCESS_COARSE_LOCATION), than please see FAQ section.

**Comment by jmorahan** [comment]
I can see that there is a description with a link to a FAQ, but the permission dialog obscures both the description and the link, and denying the permission closes the app without giving me a chance to read it. Granting the permission also dismisses the text and link before I can read it.

Having found the FAQ via github, sure, it makes perfect sense, but perhaps it could be easier to discover from within the app itself?

**Comment by VREMSoftwareDevelopment** [comment]
@jmorahan 
Please open a new feature request (do not forget to fill the feature template)

**Comment by quantumpacket** [comment]
No need to open a new issue, I'll edit this one when I get on my computer. Maybe first show a notice about the change and new requirement and then once notice is closed request the permission? Or better yet put a changelog/notice in the app info section. I installed via F-Droid, so I had no idea why the app was needing location permissions, let alone why it would exit when I denied it.

**Comment by VREMSoftwareDevelopment** [comment]
For now we will add more information to the version release notes

**Comment by VREMSoftwareDevelopment** [comment]
This feature will be available in the next release.

**Comment by wesinator** [comment]
Can you make the app prompt the user to enable location services when disabled ?

This would clear up the confusion around requiring location to be enabled.

**Comment by VREMSoftwareDevelopment** [comment]
@wesinator 
Next release will redirect user to location services setup when disabled.

**Comment by TheOtherDoctor** [comment]
This might be not working in a useful way on all platforms, this is what I observe on mine:

Starting the app, it shows quickly the empty screen with the app icon and then drops into the location settings dialog. Location is on, I tap the back arrow, same settings screen appears - unless I give up and close the app.

As I learned meanwhile, activating the GPS fixes this. But I could get this info only via searching here in the github - for "normal" users this is a bit too far to go.

I'd pragmatically suggest to remember the starting state of the app, and when the user has obviously closed the app without ever having scanned anything, show a startup pop up message like "It looks like the app did not run normally yet. Please make sure to have location service GPS enabled." before dropping into the settings menu. Without this info, the behaviour is very confusing.  

App version 2.1.2-52SL (7.1.2-25) as currently delivered by f-droid, running on Lineage OS 14.1 (equiv Android 7.1).
