### ISSUE TITLE
Improve french translation

### ISSUE THREAD

**Issue by ThomasSevestre** [VREMSoftwareDevelopment/WiFiAnalyzer#221]
The label of the menu item used to share the results is "Exportation"
It should be "Partager"

I've not found translation strings in the repository to do the PR

**Comment by ldmpub** [comment]
Hi, What version of the app are you using?
In the main menu of version 2.0.2, the item is "Exporter" in french which looks good from my point of view because it's both a generic term for the operation and it's close to english (which may help users when asking for help).

**Comment by ThomasSevestre** [comment]
Hi,
I'm using version 1.9.3 from the Play Store
"Exporter" is much better than "Exportation"
I still prefer "Partager" since it is used everywhere in Android but feel free to close if you don't want to change the label.
Thanks for sharing this app !

**Comment by VREMSoftwareDevelopment** [comment]
Please refer to pull request #205 to change french translations.
There will be no updates to the Version 1.9.3. 
All new changes will be available in the future releases.

**Comment by ldmpub** [comment]
You can install more recent version of the app through F-Droid (both the website or the Android app which will allow you to get automatic updates).
