### ISSUE TITLE
MAC vendor search is case sensitive

### ISSUE THREAD

**Issue by LeSpocky** [VREMSoftwareDevelopment/WiFiAnalyzer#222]
**Please search issues (open and closed) to see the issues has already been reported.**
In #145 a hardware address vendor search was added, which I highly appreciate.

**Describe the bug**
However, as already stated in one of the comments, the search is case sensitive, it only works if you type upper case letters. That breaks user expectations and is cumbersome to type with some keyboards.

I consider that a bug, because lower case letters are perfectly valid for a hexadecimal value.

**To Reproduce**
1. Go to 'Menu'
2. Click on 'Hersteller' (that may be 'Vendor' in English?)
3. Type a valid address containing lower case letters from a to f
4. See no results

**Expected behavior**
`00:16:3e` is actually the very same (part of) address like `00:16:3E` because hexadecimal notation does not differentiate case of letters. So I expect both (and even mixed case) input to get me results.

**Screenshots**
![screenshot_20181206-222819](https://user-images.githubusercontent.com/661636/49613187-48246700-f9a7-11e8-9c4d-3925129dc5ac.jpg)
![screenshot_20181206-222914](https://user-images.githubusercontent.com/661636/49613193-4ce91b00-f9a7-11e8-8b0a-eadece3d2254.jpg)

**Note**
Some behaviour only occurs on certain devices or versions of Android, please provide the following screenshots/information Device/Android OS (Settings → About Phone) and WiFi Analyzer version (Menu -> About)

![screenshot_20181206-222509](https://user-images.githubusercontent.com/661636/49613198-55d9ec80-f9a7-11e8-9bd5-acde82046da1.jpg)
![screenshot_20181206-222642](https://user-images.githubusercontent.com/661636/49613203-596d7380-f9a7-11e8-9e0d-57b87f1aaba1.jpg)

Please make hardware address input/search case insensitive!

**Comment by VREMSoftwareDevelopment** [comment]
@LeSpocky 

Please fill the missing information in the feature request template we have provided above, this helps us to investigate and resolve this faster.

**Comment by LeSpocky** [comment]
@VREMSoftwareDevelopment Although I consider it rude to edit my report without asking, I provided the information in a way you might like better now?!

**Comment by VREMSoftwareDevelopment** [comment]
The fix will be available in the next release
