### ISSUE TITLE
Report locally administered and multicast addresses in vendor search

### ISSUE THREAD

**Issue by LeSpocky** [VREMSoftwareDevelopment/WiFiAnalyzer#223]
**Please search issues (open and closed) to see the issues has already been reported.**
This is a follow up to #145.

**Is your feature request related to a problem? Please describe.**
When searching for addresses which have the locally administered or multicast flag set, no result is returned, which is right. However the app could report, when it detects one or both of those flags.

**Describe the solution you'd like**
The app could report, the user just entered a locally administered (aka private) address.

**Describe alternatives you've considered**
A trained user could maybe see those flags in the first octet, but for non trained users it would be nice if the app would show why it did not get a result, if it can detect that from those flags.

**Additional context**
https://en.wikipedia.org/wiki/MAC_address#Address_details

**Provide Device/Android OS information**
Android 6.

**Comment by VREMSoftwareDevelopment** [comment]
This is an interesting idea for a feature. Unfortunately all current contributors are busy with other work. When we don't have an opportunity to implement a feature, we encourage developers to fork the project and become a contributor. It would be great to add new contributors to this project.
