### ISSUE TITLE
Freezes a lot when going from background to foreground

### ISSUE THREAD

**Issue by ea4eoz** [VREMSoftwareDevelopment/WiFiAnalyzer#224]
**Describe the bug**
Since the last update opening the application from the launcher icon or from the task list results in a frozen application most of the times. When frozen no updates are shown: It shows the last APs received when the app went to background but the list does not change/update at all. Switching from 2.4 to 5 GHz switchs the 2.4 or 5 GHz label but the graph / list content does not.

The only way to get the application working again is to kill it and launch it again.

WifiAnalyzer version: 2.0.2 - 43S (8.1.0-27)
Device: Samsung J7 Pro, Android 8.1.0, non-rooted.

**To Reproduce**
1. Go to the main screen
2. Tap on Wifi Analyzer icon

**Expected behavior**
Work nicely all the times just like in previous versions.

**Additional context**
The application has all needed permisions.

Thank you.

**Comment by VREMSoftwareDevelopment** [comment]
Most likely the reason for the described behavior, is that the version 2.X of the application is written to support Android OS 8 (Oreo) and 9 (Pie) APIs requirements. Please take a look at Android documentation [Wi-Fi scanning overview](https://developer.android.com/guide/topics/connectivity/wifi-scan) specifically throttling section.

If you would like to install old version of the application, how to instructions are available [here](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Location-Service-Permission-Requirements).

Thank you,
The VREM Development Team

**Comment by ea4eoz** [comment]
I'm pretty sure the problem is not related to the throttling because Android 8.1 only limit scans in background and this app only works in foreground, right?

Also any other wifi scanning app I have installed works like a charm. Only this one gets frozen too often.

Thank you anyway.

**Comment by VREMSoftwareDevelopment** [comment]
By pushing application into background all the WiFi scanning background rules are applicable.

**Comment by ea4eoz** [comment]
Sorry but I still feel there is a problem with the current version of WifiAnalyzer.

All other WiFi scanning apps I have installed works just fine.

This one started to freeze since the last update: The previous version did not freeze at all.

If background rules are applicable when going to background, they are also applicable to the previous version, which works just fine. Think about it.

I will install the previous version and block further updates.

Thanks.

**Comment by VREMSoftwareDevelopment** [comment]
Version 1.X build supports Android OS 5.1 or prior, it runs in the compatible mode on the device running Android OS 6 and higher. This could be the reason why there are differences in behavior between 1.X and 2.X versions of the application.
