### ISSUE TITLE
Building a reusable standalone library for scanning the network

### ISSUE THREAD

**Issue by TomasJ1993** [VREMSoftwareDevelopment/WiFiAnalyzer#225]
Hello,
I would like to create a reusable standalone library for my [project](https://github.com/HoutanProject/WiFiAnalyzer/wiki) based on Wifianalyzer under the GNU license. I need the specific function of scanning the network and getting the wifidetails. I want to separate the WifiAnalzyer Newtorking and WifiAnalyzerUI modules and be able to implement them to my project and at the same time help other people to use this great function. However, I am not sure how to exactly do it, maybe you could provide some guidelines?

**Comment by VREMSoftwareDevelopment** [comment]
Hi @TomasJ1993 

Have you considered the following open source libraries:
- [ReactiveNetwork](https://github.com/pwittchen/ReactiveNetwork)
- [ReactiveWiFi](https://github.com/pwittchen/ReactiveWiFi)

Have you considered the following open source applications:
- [LocalWifiNlpBackend](https://f-droid.org/en/packages/org.fitchfamily.android.wifi_backend/)
- [Smarter Wi-Fi Manager](https://f-droid.org/en/packages/net.kismetwireless.android.smarterwifimanager/)

Regards,
VREM Development Team
