### ISSUE TITLE
not working w/ new Galaxy S10plus

### ISSUE THREAD

**Issue by bzdzz** [VREMSoftwareDevelopment/WiFiAnalyzer#229]
1. got my Samsung S10plus yesterday, did upgrade to all latest firmware
2. installed WiFiAnalyzer, launched, screen just says "scanning", left for 3 mins, nothing.
3. Rebooted S10+, then repeated step 2 above, same nothing.
Conclusion: must not be accessing S10+ wifi hardware correctly.

Please fix, love this app.
Thanks

-------------------------------------------------------------------------------------------------

[How to report a bug](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Feedback)

**Please search issues (open and closed) to see the issues has already been reported.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Note**
Some behaviour only occurs on certain devices or versions of Android, please provide the following screenshots/information Device/Android OS (Settings → About Phone) and WiFi Analyzer version (Menu -> About)

**Additional context**

**Provide Device/Android OS information**

**Comment by VREMSoftwareDevelopment** [comment]
@bzdzz
 
Please fill the missing information in the feature request template we have provided above, this helps us to investigate and resolve this faster.

**Comment by VREMSoftwareDevelopment** [comment]
We can not investigate this issue, since not enough information is provided
