### ISSUE TITLE
Updating interval issue

### ISSUE THREAD

**Issue by Srednii** [VREMSoftwareDevelopment/WiFiAnalyzer#231]
Good day,
App not working as I expect it must. App can't real-time update test results, it's static. One way I can update result is change test and return back.
For example: i had choosed "Access Points" test and i can see my AP with result: -51dbm, CH11, ~3m. Next i had gone to another room (something like 5m) and nothing change. I choosed another test (Channel Graph), and return to AP test back, then result had changed (-65dbm, CH11, ~8m). 
Any change of scan interval option can't help. It setted up as 1 second now.

HW: OnePlus 6T, A6010
FW: Android Pie, 9.0.12, official, not rooted.

**Comment by VREMSoftwareDevelopment** [comment]
@Srednii 

Android 9 is throttling wifi scanning, from android documentation: "Each foreground app can scan four times in a 2-minute period."

Please take a look at following android documentation references:

- [Wi-Fi scanning overview](https://developer.android.com/guide/topics/connectivity/wifi-scan)
- [Throttling](https://developer.android.com/guide/topics/connectivity/wifi-scan#wifi-scan-throttling)

In the future releases of the application we are planning to remove scanning interval settings for Android 9+.

**Comment by hues0** [comment]
What if we add `android.Manifest.permission.NETWORK_SETTINGS` permission to the app? We might be able to override throttling (it may require signature spoofing).
See [this related SE question](https://stackoverflow.com/questions/51901074/prevent-wifi-scan-throttling-on-android-9-pie-with-network-settings-permission).
