### ISSUE TITLE
Latest Android Studio and Latest Jacoco build error

### ISSUE THREAD

**Issue by chankruze** [VREMSoftwareDevelopment/WiFiAnalyzer#232]
**Describe the bug**
Unable to compile and run feature branch on both physical and emulator device.
The clean clone don't even build successfully.

**To Reproduce**
1. Clone the feature branch or checkout feature.
2. Then import this project to android studio.
3. Then you will encounter below
```
WARNING: The option setting 'android.enableUnitTestBinaryResources=true' is experimental and unsupported.
The current default is 'false'.
Affected Modules: app
```
4. To fix this open `gradle.properties` and comment out `android.enableUnitTestBinaryResources=true` and do sgradle sync.
4. Now Build is completed successfully. Now try to run the app by clicking `run` button, you will get an error `Cause: java.lang.IllegalStateException`. This error is from run build.

**Screenshots**
![Screenshot from 2019-04-05 00-22-38](https://user-images.githubusercontent.com/29806845/55581457-84d85300-573a-11e9-8481-1765d15b105c.png)
![Screenshot from 2019-04-05 00-22-55](https://user-images.githubusercontent.com/29806845/55581461-8570e980-573a-11e9-8c10-f7cf62373c98.png)
![Screenshot from 2019-04-05 00-24-20](https://user-images.githubusercontent.com/29806845/55581465-8570e980-573a-11e9-9e08-3fa0f4ae36af.png)
![Screenshot from 2019-04-05 00-24-29](https://user-images.githubusercontent.com/29806845/55581466-86098000-573a-11e9-9a2e-3dd891bf2b1f.png)

**Provide Device/Android OS information**
Host Details
```
Distributor ID:	Ubuntu
Description:	Ubuntu Disco Dingo (development branch)
Release:	19.04
Codename:	disco

Linux chankruze-TUF 5.1.0-rc3+ #2 SMP Thu Apr 4 06:08:34 IST 2019 x86_64 x86_64 x86_64 GNU/Linux
```
Target Details
```
1) Moto G5 Plus (Android 9)
2) Emulator Nexus 5x (Android 9)
```

**Comment by VREMSoftwareDevelopment** [comment]
1) android.enableUnitTestBinaryResources=true
This is not an Error, it is only a warning and it is required to run tests

2) The last feature branch build is successful, Travis CI reference
https://travis-ci.org/VREMSoftwareDevelopment/WiFiAnalyzer/builds/504068141

**Comment by chankruze** [comment]
Yes i can read android.enableUnitTestBinaryResources=true is not a error,
What about the `Cause: java.lang.IllegalStateException` ?

**Comment by chankruze** [comment]
Again i clone cleanly and run tests and the same permission error.

```
chankruze@chankruze-TUF:~/AndroidStudioProjects/WiFiAnalyzer$ ./gradlew lint testDebugUnitTest jacocoTestReport
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :app
WARNING: The option setting 'android.enableUnitTestBinaryResources=true' is experimental and unsupported.
The current default is 'false'.

>>> WiFiAnalyzer 2.0.3.19 (44) com.vrem.wifianalyzer.BETA

> Task :app:lint
Ran lint on variant debug: 85 issues found
Ran lint on variant release: 85 issues found
Wrote HTML report to file:///home/chankruze/AndroidStudioProjects/WiFiAnalyzer/app/build/reports/lint-results.html
Wrote XML report to file:///home/chankruze/AndroidStudioProjects/WiFiAnalyzer/app/build/reports/lint-results.xml

> Task :app:lint FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lint'.
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
  
  Errors found:
  
  /home/chankruze/AndroidStudioProjects/WiFiAnalyzer/app/src/main/java/com/vrem/wifianalyzer/wifi/scanner/Scanner.java:161: Error: Missing permissions required by WifiManager.getConfiguredNetworks: android.permission.ACCESS_FINE_LOCATION [MissingPermission]
              return wifiManager.getConfiguredNetworks();
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s
27 actionable tasks: 22 executed, 5 up-to-date
chankruze@chankruze-TUF:~/AndroidStudioProjects/WiFiAnalyzer$ 
```

**Comment by chankruze** [comment]
Jesus !
The build succeed!

https://travis-ci.org/chankruze/WiFiAnalyzer/builds/516372762

I think it's my environment who is the culprit here. I will now add time stamp and let's see if it builds or not.

**Comment by VREMSoftwareDevelopment** [comment]
@chankruze 

https://travis-ci.org/chankruze/WiFiAnalyzer/builds/516378549 

Line 1604 - 1611 (just a warning)
```
> Task :app:compileDebugUnitTestJavaWithJavac
/home/travis/build/chankruze/WiFiAnalyzer/app/src/test/java/com/vrem/wifianalyzer/wifi/scanner/ScannerTest.java:195: warning: [deprecation] startScan() in WifiManager has been deprecated
        verify(wifiManager).startScan();
                           ^
/home/travis/build/chankruze/WiFiAnalyzer/app/src/test/java/com/vrem/wifianalyzer/wifi/scanner/ScannerTest.java:205: warning: [deprecation] startScan() in WifiManager has been deprecated
        when(wifiManager.startScan()).thenReturn(true);
                        ^
2 warnings
```

Line 3401 - 3402 (this is an error, failed test)
```
com.vrem.wifianalyzer.navigation.items.ExportItemTest > testActivate FAILED
    org.junit.ComparisonFailure at ExportItemTest.java:93
```

**Comment by VREMSoftwareDevelopment** [comment]
@chankruze 

> What about the Cause: java.lang.IllegalStateException ?

We were able to recreate this error in Android Studio. This is an issue between latest Android Studio and latest jacoco version (solution: downgrade jacoco version). The gradle scripts are updated to reflect this. Please pull the latest changes from feature branch.

**Comment by chankruze** [comment]
Ok i will try to write/update test
