### ISSUE TITLE
WifiAnalyzer does not update signal strenght when changing distance

### ISSUE THREAD

**Issue by TobiasGrueninger** [VREMSoftwareDevelopment/WiFiAnalyzer#234]
[Description]

First of all, in an older version of WifiAnalyzer (Sept. 2017) I did not notice this (on older Galaxy S3 NEO vian Analyzer probably <1.9.3 and Android 4.4.2).
Used Version now 2.0.2 on Galaxy A5 /Android 8.0.0: 

![Screenshot_20190413-103624_WiFiAnalyzer](https://user-images.githubusercontent.com/49689954/56224726-66deec80-6070-11e9-9293-8b4be55bd4c1.jpg)

**Please search issues (open and closed) to see the issues has already been reported.**
Didn't saw any issue

**Describe the bug**
It seems that the update to show the actual AccessPoint strengh is quite slow and sometimes got stuck. So when walking towards or away from any AP, it would be expected that the Signal strenght is updating.
However it seems to be frozen, only stopping and starting your App does then update the screen.
Above it can be seen what I experience: We see the same AP twice, which is fine - the one with the grey background is the one with which the mobile would like to connect to (but is not having n Internet connection), the one below would be the list of possible APs it can connect, here only one.
As I walked away, only the lower AP did reduce the channel strenght, the upper kept frozen despite they are the same

**To Reproduce**
- Connect (or not connect) to an AP
- Change signal strength by changing distance

**Expected behavior**
The Signal strenght should change identical in all screens whith all APs the App can see. No AP should be in a frozen strength

**Screenshots**
Additional Screenshot:
![Screenshot_20190413-103619_WiFiAnalyzer](https://user-images.githubusercontent.com/49689954/56226527-b1159d00-6073-11e9-987d-be8d01f8bb79.jpg)

Here a similar problem can be seen:
The AP is reported above with -60dBm, while below (correct because I walked away) the graph shows ~ -81dBm

**Comment by VREMSoftwareDevelopment** [comment]
Hi Tobias Grueninger,

Thank you for your detailed explanation of the issue you are seeing.

Here some information that maybe relevant to this issue:
- Information displayed on the top with gray background is current WiFi device connection information.  To following Android API is used to retrieve connection information [WifiManager.getConnectionInfo](https://developer.android.com/reference/android/net/wifi/WifiManager.html#getConnectionInfo())
- The information displayed in other place in the application is information retrieved from [WifiManager.getScanResults] https://developer.android.com/reference/android/net/wifi/WifiManager.html#getScanResults()

As you can see they are two different API. Also starting with Android 8+, there some behavior changes to WifiManager.getScanResults functionality.

Instructions on how to install older version of the application (version 1.9.3) and information of new changes to WiFi Scanning on Android 8+, with links to Android documentation, is available [here](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Location-Service-Permission-Requirements).

Can you please try different version of the application and see if behaviors changes?
- Version 1.9.3 [link here](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/releases/tag/V1.9.3-F-DROID)
- Version 2.0.4 [link here](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/releases/tag/V2.0.4-F-DROID)

Version 2.0.4 wast just released.

Regards,

VREM Development Team
