### ISSUE TITLE
Bug: Updates don't resume when using the app switcher

### ISSUE THREAD

**Issue by user8446** [VREMSoftwareDevelopment/WiFiAnalyzer#237]
When using the app switcher and returning to WiFiAnalyzer, the updates do not resume and are instead "frozen" from the last update when leaving the app.

**To Reproduce**
1. Use WiFiAnalyzer as normal
2. Click on the app switcher to switch to different app
3. Click on the app switcher to switch back to WiFiAnalyzer
4. See that the updates do not resume. You have to close out the app and reopen it

**Expected behavior**
Updates should resume since the app is in the foreground

**Note**
Observed on Android 8.1

**Comment by VREMSoftwareDevelopment** [comment]
Some behaviour only occurs on certain devices or versions of Android.
Please provide the following screenshots/information:
- Device/Android OS (Settings → About Phone) 
- WiFi Analyzer version (Menu -> About)

**Comment by user8446** [comment]
Same behavior on two different devices:

Moto g5plus phone
Android 8.1
WiFi analyzer v2.0.2 - 43S (8.1.0-27)

Asus ZenPad 10 tablet
Android 7.0
WiFi analyzer v2.0.2 - 43SL (7.0-24)


On Sat, May 25, 2019, 9:04 AM VREM Software Development <notifications@github.com<mailto:notifications@github.com>> wrote:

Some behaviour only occurs on certain devices or versions of Android.
Please provide the following screenshots/information:

  *   Device/Android OS (Settings → About Phone)
  *   WiFi Analyzer version (Menu -> About)

**Comment by VREMSoftwareDevelopment** [comment]
Application Version 2.X is designed to comply to latest Android 9 (Pie) requirements, such as location permission.

Version 1.9.3 is recommended for any device running Android 8.1 and lower. Instructions on how to install older version of the application (version 1.9.3) is available [here](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Location-Service-Permission-Requirements).

If you still wish to use Application Version 2.X, please make sure you are running the latest version. Instructions on how to install latest version of the application (latest release is version 2.0.4) is available [here](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Location-Service-Permission-Requirements).

Regards,

VREM Development Team

**Comment by user8446** [comment]
Thanks for the reply. 
I don't have a problem with the location permission and already had it on. I updated to 2.0.2 to 2.0.4 and the bug is gone on both devices. 
Question though - how come the latest version wasn't uploaded to the play store?

**Comment by VREMSoftwareDevelopment** [comment]
A lot play store users are not happy with new android location permission requirements, so decision was made to make Version 2.X available only to devices running Android 9 (Pie) and higher. There is no options in Play Store to offer multiple version of application for the same Version of Android OS.
