### ISSUE TITLE
Android Q Wifi scan throttling

### ISSUE THREAD

**Issue by buttercookie42** [VREMSoftwareDevelopment/WiFiAnalyzer#238]
According to [this comment](https://issuetracker.google.com/issues/79906367#comment29) on the Android issue tracker, Android Q will include an option to disable throttling again, though it's not clear whether it might also appear in the GUI developer options, or whether it can only be set programatically via adb, respectively using root access.

**Comment by VREMSoftwareDevelopment** [comment]
Please submit pull request, that solves this issue.
Currently there is no plan to create application that requires to root the phone.

**Comment by woheller69** [comment]
what about adding a dialog box at first start on Android Q+ that recommends to deactivate the throttling in developer settings?
