### ISSUE TITLE
2.4Ghz channels not correct for Australia

### ISSUE THREAD

**Issue by pyko** [VREMSoftwareDevelopment/WiFiAnalyzer#239]
**Describe the bug**
In Available Channels and Channel Ratings, it only shows channels 1-11 for Australia, but Australia can use channels 1-13.

See:
https://www.juniper.net/documentation/hardware/netscreen-appliances/5gtwireless/wireless_channels.pdf
https://en.wikipedia.org/wiki/List_of_WLAN_channels

**To Reproduce**
View Available Channels or Channel Ratings with Australia as selected country

**Expected behavior**
Channels 1-13 are shown

**Additional context**
Noticed this because I am reside in Australia and this app only shows 1-11, but router showed channels 1-13.

**Comment by pyko** [comment]
I had a look into this ticket, and realised that other countries may also be incorrect.

Cross referencing https://www.juniper.net/documentation/hardware/netscreen-appliances/5gtwireless/wireless_channels.pdf (for country/channel support) and https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes for the 2 letter country codes used in code, I got:

<img width="468" alt="Screen Shot 2019-05-27 at 9 51 26 pm" src="https://user-images.githubusercontent.com/151003/58419061-e4186b00-80cc-11e9-95e3-1a73cc63dcc5.png">

**Not in table**
AS (American Samoa)
FM (Federated States of Micronesia)
GU (Guam)
MP (Northern Mariana Islands)
UM (United States Minor Outlying Islands)
VI (Virgin Islands)

Of the above (except for FM), fairly certain they should still be included as they are all listed as "United States" sovereignty.

FM is "UN member state" sovereignty. There is a mix of 1-11 and 1-13 for UN member state countries.

**Need to be added**
Countries listed in "Missing" column

**Need to be removed**
Australia (AU) is "In Code" but is listed as Channels 1-13

**Comment by VREMSoftwareDevelopment** [comment]
Will be available in the next release
