### ISSUE TITLE
Accessing Settings crashes the app

### ISSUE THREAD

**Issue by fllms** [VREMSoftwareDevelopment/WiFiAnalyzer#241]
**Describe the bug**
Tapping on "Settings" in the menu crashes the app

**To Reproduce**
1. Flash latest GrapheneOS
2. Install WifiAnalyzer 2.0.4
3. Open WifiAnalyzer
4. Open menu
5. Tap on "Settings"

**Expected behavior**
Entering Settings

**adb logcat**
https://pastebin.com/jm8EQV53

**Provide Device/Android OS information**
Device/OS: Pixel 3 running GrapheneOS build no. PQ3A.190505.002.2019.05.18.20 (Android 9 2019.05.05)
WiFiAnalyzer: 2.0.4 - 45S (9-28)

**Comment by fllms** [comment]
Reinstall fixed it.

**Comment by VREMSoftwareDevelopment** [comment]
The fix will be available in the next release
