### ISSUE TITLE
Displayed information does not update on Pixel 3

### ISSUE THREAD

**Issue by a64801** [VREMSoftwareDevelopment/WiFiAnalyzer#242]
**Description**
The information displayed (WiFi networks, signal strengths, etc) does not update after starting the app on Google Pixel 3. Attempting to refresh the information manually by swiping down has no effect, just displays a refreshing symbol for a while.

**Device information**
Model: Pixel 3
Android version: 9
Build number: PQ3A.190505.002

**App information**
App version (from about page): 2.0.4 - 45S (9-28)

**Comment by evgenbn** [comment]
Hello! I probably have the same problem. For example, I started the program or forcibly update access points, the update icon appears and does not stop. Transition to any other menu helps. Version 2.0.4 - 45S (9-28). Nokia 6.1, Android 9 (00WW_3_51F_SP02)

**Comment by VREMSoftwareDevelopment** [comment]
Android 9+ (Pie) is throttling wifi scanning
Duplicate #231
