### ISSUE TITLE
Versions 1.x work, but versions 2.x don't work (infinite loading circle)

### ISSUE THREAD

**Issue by opusforlife** [VREMSoftwareDevelopment/WiFiAnalyzer#243]
Location permission is granted. I've tried different scan intervals. Pausing and resuming doesn't affect the loading circle animation. Everything is allowed under Privacy Guard (LineageOS 15.1, so Android Oreo).

The versions before 2, including 1.9.3, work perfectly well. I can't think of any other variables to check for.

**Comment by StyXman** [comment]
Same here. Version from F-Droid, 2.0.4-45S (7.1.2-25). Not sure which was the version that worked before. Currently running FairPhone 19.05.3, based on AOSP-7.0.2 PL March 01, 2019. Then I turned Location on (GPS) and it started working.

**Comment by evgenbn** [comment]
Hello! I probably have the same problem. For example, I started the program or forcibly update access points, the update icon appears and does not stop. Transition to any other menu helps. Version 2.0.4 - 45S (9-28). Nokia 6.1, Android 9 (00WW_3_51F_SP02)

**Comment by 532910** [comment]
same issue with LineageOS 16

**Comment by VREMSoftwareDevelopment** [comment]
@opusforlife , @evgenbn, @532910 

Please make sure location services on the device is enabled and functioning and application must have access to location services. As per @StyXman comment, application works after location services were enabled.

Application Version 2.X is designed to comply to latest Android 9 (Pie) requirements, such as location permission.

Version 1.9.3 is recommended for any device running Android 8.1 and lower. Instructions on how to install older version of the application (version 1.9.3) is available [here](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Location-Service-Permission-Requirements)

If you still wish to use Application Version 2.X, please make sure you are running the latest version. Instructions on how to install latest version of the application is available  [here](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Location-Service-Permission-Requirements)

Regards,

VREM Development Team

**Comment by opusforlife** [comment]
@StyXman Thanks for the help!

@VREMSoftwareDevelopment Sorry about the false alarm! Does this mean that on Android Pie, you can't use version 1.9.3 _at all_? It seems very weird on Google's part to ask for GPS to be enabled just to scan some Wi-Fi networks. Explicitly asking for the location permission should be enough for the user to realise that Wi-Fi scanning can be used to track device location. Unless Google wants that every time the user wishes to use apps like this, Play Services should be able to track them along with all other apps that ping device location in the background. >:(

On that note, since versions 2.x won't work without GPS being enabled, could you please add a popup that gives you the option of enabling GPS, taking you to the Location menu if the user agrees? That's how GPSTest and Tower Collector do it. This will prevent silent fails like mine.

**Comment by 532910** [comment]
I'm absolutely sure location services on the device is enabled and functioning and application have access to location services.

![image](https://user-images.githubusercontent.com/14617699/59524623-0f78c380-8edd-11e9-87d4-22acdbbc07f2.png)

![image](https://user-images.githubusercontent.com/14617699/59524644-20293980-8edd-11e9-83c0-c46cda9001c2.png)

![image](https://user-images.githubusercontent.com/14617699/59524699-3e8f3500-8edd-11e9-8fc3-3f4c6cf65143.png)

![image](https://user-images.githubusercontent.com/14617699/59524755-5961a980-8edd-11e9-9d13-7334b580f73e.png)

Please reopen.

**Comment by 532910** [comment]
The app can successfully scan wifi networks. But pulling down leads to endless circle animation:
![image](https://user-images.githubusercontent.com/14617699/59525250-8bbfd680-8ede-11e9-8a11-a6dfaf936f92.png)

**Comment by 532910** [comment]
Moreover, `fast scannig` does nothing.

**Comment by VREMSoftwareDevelopment** [comment]
@StyXman application provide popup that explains all requirements at the startup: 

![Capture](https://user-images.githubusercontent.com/6217364/59542812-d25d0300-8ed5-11e9-9c9e-8c89ca462af4.JPG)

Would you like to create pull request, regarding taking user to Location Services menu, since all current contributors are busy with other work. When we don't have an opportunity to implement a feature, we encourage developers to fork the project and become a contributor. It would be great to add new contributors to this project.

**Comment by VREMSoftwareDevelopment** [comment]
@532910 some behavior only occurs on certain devices or versions of Android. 
We do not have devices running LineageOS 16, so we will not be able to investigate your specific issues.
