### ISSUE TITLE
Distance between two mobile devices connected to the same wi-fi router

### ISSUE THREAD

**Issue by konashevich** [VREMSoftwareDevelopment/WiFiAnalyzer#245]
Dear community,
Is it possible to get info on distance between two mobile devices connected to one WiFi router?

Thanks,
Alex

**Comment by VREMSoftwareDevelopment** [comment]
Please submit pull request.

**Comment by konashevich** [comment]
I am sorry, this question has nothing to do with forks. 
Why I can just ask the community this question?

**Comment by VREMSoftwareDevelopment** [comment]
@konashevich 
Issues are to keep track of tasks, enhancements and bugs for the project.
[GitHub Guides - Mastering Issues](https://guides.github.com/features/issues)

**Comment by konashevich** [comment]
Where your community talks to each other?
