### ISSUE TITLE
scan connected devices

### ISSUE THREAD

**Issue by Fuseteam** [VREMSoftwareDevelopment/WiFiAnalyzer#246]
as the the slogan is to "optimize your wifi network" i would like to be able to scan how many devices are connected to the wifi network

**Comment by VREMSoftwareDevelopment** [comment]
@Fuseteam when create an issues (Feature request or Bug report) please use an appropriate template that is provided.  This helps us to investigate and resolve the issue faster.

**Comment by VREMSoftwareDevelopment** [comment]
There are other open source Android applications/projects that provide the functionality that you are requesting.
- [Android Network Tools](https://github.com/stealthcopter/AndroidNetworkTools)
- [PortAuthority](https://github.com/aaronjwood/PortAuthority)

Potentially in the future, we might add the link to one of the application, but unfortunately not in the short term. By any chance, do you have any knowledge in Android development? When we don't have an opportunity to implement a feature, we encourage developers to fork the project.

**Comment by VREMSoftwareDevelopment** [comment]
Link to [PortAuthority](https://github.com/aaronjwood/PortAuthority) will be added in the next release

**Comment by Fuseteam** [comment]
I was not aware of the other open source alternatives
but i'm more a fan of a single app that that can do all related tasks then several  apps cluttering my phone

while i am somewhat familiar with andriod development, i'm not familiar with your codebase and i'd rather contribute than fork
