### ISSUE TITLE
Bug with version 2.0.6 when selecting channel graph.

### ISSUE THREAD

**Issue by SuperSentient** [VREMSoftwareDevelopment/WiFiAnalyzer#247]
[How to report a bug](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Feedback)

**Please search issues (open and closed) to see the issues has already been reported.**

**Describe the bug**

**To Reproduce**
2. Click on '....' Channel Graph

**Expected behavior**
Stutter/lag when selecting Channel Graph.

**Screenshots**

**Note**
Some behaviour only occurs on certain devices or versions of Android, please provide the following screenshots/information Device/Android OS (Settings → About Phone) and WiFi Analyzer version(Menu -> About)
Samsung Galaxy S8 with Android version 9 WiFi Analyzer version 2.0.6.

**Additional context**

**Provide Device/Android OS information**
Samsung Galaxy S8 with Android version 9.

**Comment by VREMSoftwareDevelopment** [comment]
Please fill all the sections of the template. This will helps us to investigate and resolve the issue.

**Comment by VREMSoftwareDevelopment** [comment]
@SuperSentient What is the scan interval in the setting menu?

**Comment by VREMSoftwareDevelopment** [comment]
The fix will be available in the next release
