### ISSUE TITLE
WI-FI: Disconnects every 30 seconds

### ISSUE THREAD

**Issue by Dustyn69** [VREMSoftwareDevelopment/WiFiAnalyzer#248]
**Describe the bug**
Each time I open WI-FIAnalyzer, the WI-FI connection on my phone will disconnect every 30 seconds. It reconnects after losing the connection, but will then disconnect again in 30 seconds.

**To Reproduce**
1. Open WI-FI Analyzer and simply wait approx 30 seconds.
2. WI-FI connection is lost after 30 seconds. It will auto reconnect after 5 seconds. After reconnection the WI-FI connection is lost again.
3. WI-FI connection remains solid at all times as long as the WI-FI Analyzer app is NOT launched.

**Expected behavior**
The expected behavior is that the WI-FI connection remains stable and does not lose the connection. I have never had this issue before until only the last WI-FI application update.

**Screenshots**
Not applicable at this time.

**Note**
![Screenshot_20190706_223538](https://user-images.githubusercontent.com/52615093/60763272-e6ac9f80-a03e-11e9-9c33-193dd8b5b076.jpg)

![Screenshot_20190706_222901_com vrem wifianalyzer](https://user-images.githubusercontent.com/52615093/60763210-984ad100-a03d-11e9-8f23-7020bc67dbf2.jpg)

**Additional context**
Not applicable at this time.

**Provide Device/Android OS information**
Huawei Mate 20 Pro, Android 9.

**Comment by VREMSoftwareDevelopment** [comment]
The fix will be available in the next release

**Comment by Dustyn69** [comment]
Thank you! :)
Were you successfully able to reproduce this?

**Comment by VREMSoftwareDevelopment** [comment]
@Dustyn69 

[Android Pie throttling Wi-Fi scanning](https://www.androidpolice.com/2019/05/29/android-started-heavily-throttling-wi-fi-scanning-in-pie-google-confirms-its-here-to-stay)

Some experimental code, that tries to solve the issue above, leaked into production without an ability to switch this feature on/off. The new release give the user full control over it.
