### ISSUE TITLE
Push updates to the Google Play Store

### ISSUE THREAD

**Issue by user8446** [VREMSoftwareDevelopment/WiFiAnalyzer#249]
I understand that the play store is held a v1.9.3 because there are users who don't want the location permission. However, users who do want the incremental updates, improvements, and bug fixes have to sideload every. single. time. there is an update or use another package manager such as F-DROID. 

It would be an improvement if this was reversed. Users who want to stay on v1.9.3 simply need to uncheck the "enable auto-update". One click and nothing else further to do.

Users who want the updates also wouldn't have to do anything as the play store would keep the app updated.
.
.
.
![Screenshot_20190708-211845](https://user-images.githubusercontent.com/18019245/60852619-69ac3200-a1c6-11e9-956e-e9a68dea01fe.png)

**Comment by VREMSoftwareDevelopment** [comment]
As was mentioned before in #237, there is no options in Play Store to offer multiple version of application for the same Version of Android OS. 

For now,  there is no plans to update Google Play Store and we do believe that F-Droid is excellent alternative for Android power users and open source supporters.
