### ISSUE TITLE
Distance calculation is wrong? calculateDistance does not consider TX power in Free-Space Path Loss equation 

### ISSUE THREAD

**Issue by Purple-Mouse** [VREMSoftwareDevelopment/WiFiAnalyzer#254]
I have some questions about the way that the `calculateDistance` function was implemented in `WiFiUtils.java`

The Free-space path loss equation, with distance in meters and frequency in megahertz, is:
<a href="https://www.codecogs.com/eqnedit.php?latex=P_{transmit}-P_{receive}=20log(Distance)&plus;20log(frequency)-27.55" target="_blank"><img src="https://latex.codecogs.com/gif.latex?P_{transmit}-P_{receive}=20log(Distance)&plus;20log(frequency)-27.55" title="P_{transmit}-P_{receive}=20log(Distance)+20log(frequency)-27.55" /></a>

Rearranging, distance is calculated as follows. We'll call this "Equation 1":
<a href="https://www.codecogs.com/eqnedit.php?latex=\mathcal&space;Distance&space;=&space;10^{\frac{(27.55-20log(frequency)&plus;(P_{transmit}-P_{receive}))}{20}}\&space;\&space;\&space;\&space;\&space;(1)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathcal&space;Distance&space;=&space;10^{\frac{(27.55-20log(frequency)&plus;(P_{transmit}-P_{receive}))}{20}}\&space;\&space;\&space;\&space;\&space;(1)" title="\mathcal Distance = 10^{\frac{(27.55-20log(frequency)+(P_{transmit}-P_{receive}))}{20}}\ \ \ \ \ \ \ \ \ \ (1)" /></a>

The `calculateDistance` function is written as:
`return Math.pow(10.0, (DISTANCE_MHZ_M - (20 * Math.log10(frequency)) + Math.abs(level)) / 20.0);`
where `level` traces back to the RSSI picked up by your receiving device. 

In other words, the implemented function calculates distance as follows:
<a href="https://www.codecogs.com/eqnedit.php?latex=\mathcal&space;Distance&space;=&space;10^{\frac{(27.55-20log(frequency)&plus;abs(P_{receive}))}{20}}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathcal&space;Distance&space;=&space;10^{\frac{(27.55-20log(frequency)&plus;abs(P_{receive}))}{20}}" title="\mathcal Distance = 10^{\frac{(27.55-20log(frequency)+abs(P_{receive}))}{20}}" /></a>

which is equivalent to the following. We'll call this "Equation 2":
<a href="https://www.codecogs.com/eqnedit.php?latex=\mathcal&space;Distance&space;=&space;10^{\frac{(27.55-20log(frequency)&plus;abs(0-P_{receive}))}{20}}&space;\&space;\&space;\&space;\&space;(2)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathcal&space;Distance&space;=&space;10^{\frac{(27.55-20log(frequency)&plus;abs(0-P_{receive}))}{20}}&space;\&space;\&space;\&space;\&space;(2)" title="\mathcal Distance = 10^{\frac{(27.55-20log(frequency)+abs(0-P_{receive}))}{20}} \ \ \ \ \ \ \ \ \ \  (2)" /></a>

Comparing Equation 1, which is what you would expect to see in the real world under ideal conditions, with Equation 2, which is what the code is implementing, it's clear that the code is effectively assuming that all transmitters are transmitting at 0dBm. It's impossible to know what the exact transmit value should be without more information, so it makes sense that `calculateDistance` makes some assumptions about the transmitter, but assuming 0dBm is strange.

So finally, we get to my question: Why does `calculateDistance` assume that the transmitter is transmitting at 0dBm? From what I've seen, most wireless chips will transmit at around 20dBm at 2.4GHz, and can go even higher depending on the power limit set by the country code. Assuming the average device transmits at 20dBm, the distance calculation would be wrong by a factor of 10 under ideal conditions, and even greater amounts if you're transmitting at above 20dBm.

Maybe `calculateDistance` was written under the assumption that your signal will be attenuated by external factors? You'd also expect to see some power losses depending on your transmission environment and antenna, like if you were transmitting through walls (not free-space), but I haven't spent the time to collect data on what losses are typical. If the loss through a single wall is conveniently 20dBm, then the math works out nicely, but that still means that calculated distance would be off in free space. Attenuation would also be different at different frequencies, and there's no real compensation for that either.

I plan to play around with the app a bit to see how close calculated and measured distances are, but on paper, the current implementation does not appear to be accurate. Perhaps it's possible to have a dynamic TX power by pulling from a database of known manufacturers using the MAC addresses? Or maybe a different assumed TX power would give better estimations? Does anybody else have any thoughts or experience with the subject?

**Comment by VREMSoftwareDevelopment** [comment]
Yes you are correct **estimated** distance calculation was written with the assumption that access point signal will be effected by external factors.
Looking forward to your findings and will be waiting for PR.

Regards,

VREM Development Team

**Comment by hues0** [comment]
Android 9+ uses [wifi RTT](https://developer.android.com/guide/topics/connectivity/wifi-rtt) to measure distance.
