### ISSUE TITLE
Unexpected behaviours after a screen orientation change (reported by activity)

### ISSUE THREAD

**Issue by dlicse1** [VREMSoftwareDevelopment/WiFiAnalyzer#255]
I developed an automatic test case generation tool and it detected these problems in your app.
I would like to know if you consider them as failures and, if not, why. Thanks for your collaboration.

1) When I change the orientation of the device screen, MainActivity changes its state. Below there are different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...

-- first case --
The size of the TextView changes and becomes bigger
![2019-07-22 20-54-44_before](https://user-images.githubusercontent.com/53469180/62286550-43418580-b458-11e9-8684-0beb1ae61e5f.png)
![2019-07-22 20-54-44_after](https://user-images.githubusercontent.com/53469180/62286551-43418580-b458-11e9-9300-5ecf3b979736.png)

-- second case --
Tiks of the X axis appear
![2019-07-22 19-25-18_before](https://user-images.githubusercontent.com/53469180/62286552-43418580-b458-11e9-9e89-70a11177725c.png)
![2019-07-22 19-25-18_after](https://user-images.githubusercontent.com/53469180/62286553-43418580-b458-11e9-966a-a469844baecd.png)

2) When I change the orientation of the device screen, the Dialog disappears in AboutActivity
![2019-07-22 15-27-46_before](https://user-images.githubusercontent.com/53469180/62286505-23aa5d00-b458-11e9-8738-1c19115d73c2.png)
![2019-07-22 15-27-46_after](https://user-images.githubusercontent.com/53469180/62286506-2442f380-b458-11e9-873e-0e4535f6ac21.png)

**Comment by VREMSoftwareDevelopment** [comment]
Duplicate #36, #77 & #78

- Android creates a new view when switching orientation. It is intended. 
- Low Priority bug.
- It would be great if you can provide a pull request to fix it.

Btw, thanks for reporting :+1:
