### ISSUE TITLE
A small GUI correction - Access Point in the Polish language version

### ISSUE THREAD

**Issue by olekstomek** [VREMSoftwareDevelopment/WiFiAnalyzer#257]
The name "Punkty"  in the Polish language version is aligned to the left which looks less good than the name would be centered to the location of the WiFi icon.
App version: 2.0.8. - 49GS(9-28)

![Screenshot_2019-08-31-21-25-17-403_com vrem wifianalyzer](https://user-images.githubusercontent.com/26818304/64080529-c5da9080-ccf5-11e9-81a5-03e7c18482a6.png)

**Comment by VREMSoftwareDevelopment** [comment]
@olekstomek 

The actual text is "Punkty Dostępu", sometime the full text is not displayed.

Reference: [Long text cutting off in BottomNavigationView](https://github.com/material-components/material-components-android/issues/139)

**Comment by ldmpub** [comment]
Needing more room for text under icons or automaticaly add "..." when label is hidden?
