### ISSUE TITLE
Don't update versioncode/name on cleaning

### ISSUE THREAD

**Issue by krt16s** [VREMSoftwareDevelopment/WiFiAnalyzer#26]
Running `gradle clean` updates version information. I don't think that is supposed to happen?

**Comment by VREMSoftwareDevelopment** [comment]
`gradle clean` update **version_build** number in the **build.properties**. **version_build** is not used in the version information for the release.
`gradle release` updates **version_patch** and **version_store** numbers, they are used in the version information. That why there is discrepancy between version numbers.

Need to investigate further what can be done to automate F-Droid build.
Maybe just creating a different version tag for F-Droid.

**Comment by VREMSoftwareDevelopment** [comment]
Create two tags:
one for google play store
second one for F-Droid
