### ISSUE TITLE
v2.0.8 not updated on F-Droid

### ISSUE THREAD

**Issue by user8446** [VREMSoftwareDevelopment/WiFiAnalyzer#263]
2.0.8 released on 8/31 but as of today 9/9 the version still shows 2.0.7 on F-Droid

**Comment by VREMSoftwareDevelopment** [comment]
@user8446 
As release published in the GitHub, we submit request to F-Droid.
We do not have control over F-Droid publishing timelines.

**Comment by user8446** [comment]
Just adding this for others that may come across this. 
The issue why the updates were not showing up in F-Droid was because I had originally installed through the play store. This causes a certificate issue so you either have to completely uninstall and reinstall or click "include incompatible versions" through F-Droid.

**Comment by VREMSoftwareDevelopment** [comment]
@user8446 duplicate #99
