### ISSUE TITLE
2:1 screen

### ISSUE THREAD

**Issue by userkilled** [VREMSoftwareDevelopment/WiFiAnalyzer#264]
![Screenshot_2019-09-11-23-18-14-000_com vrem wifianalyzer](https://user-images.githubusercontent.com/39238592/64732009-e0c5b580-d4ea-11e9-9b67-eb292df3a887.png)
[How to report a bug](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Feedback)

**Please search issues (open and closed) to see the issues has already been reported.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Note**
Some behaviour only occurs on certain devices or versions of Android 8.1, MIUI 10.3.1.0, please provide the following screenshots/information Device/Android OS (Settings →

**Additional context**

**Provide Device/Android OS information**

**Comment by VREMSoftwareDevelopment** [comment]
Duplicate  #257
