### ISSUE TITLE
Current version not available in F-Droid-Store

### ISSUE THREAD

**Issue by Krawei** [VREMSoftwareDevelopment/WiFiAnalyzer#266]
Dear team,

when I take a look in the Google Playstore, the app's current version is 2.0.9, in F-Droid the current version is 2.0.8 .

What's the reason for this difference? Is there a bug in the building process? Please fix that.

Kind Regards,

Krawei

**Comment by VREMSoftwareDevelopment** [comment]
There was an issue in deploying Version 2.0.8 to Play Store.

**Comment by Krawei** [comment]
@VREMSoftwareDevelopment The APP still stalls at v2.0.8 in F-Droid. Habe you solved the F-Droid deployment issue in the meantime?
