### ISSUE TITLE
Missing WPA3 filter and security icon.

### ISSUE THREAD

**Issue by Jon8RFC** [VREMSoftwareDevelopment/WiFiAnalyzer#267]
**Describe the bug**
WPA and WPA2 are shown appropriately and with RSN-PSK-CCMP appended after the WPA2 listing, but WPA3 is missing itself and only shows RSN-AEA-CCMP. Wireless settings in Android settings for the network properly show the security standard as "WPA3-Personal", so it's working correctly there and I'm sending this bug report while connected to it. I have all other wifi security standards disabled. 

**To Reproduce**
1. View a network with WPA3-Personal enabled with CCMP-128.
2. Notice that WPA3 is not shown even when connected. 

**Expected behavior**
I expected the security standard of WPA3 to be displayed.

**Additional context**
Netgear r7800 with DD-WRT on 5ghz spectrum.

**Provide Device/Android OS information**
Pixel 3a
Android 10 build QP1A.191005.007

**Comment by VREMSoftwareDevelopment** [comment]
Currently there are not devices available to us that support WPA3.

Here are a few options:
- create PR with the code fix
- provide more information (i.e. screen shot, etc)
- provide WPA3 device or access to WPA3 device 

Regards,

VREM Development team

**Comment by Jon8RFC** [comment]
Sure, I can help and share some screenshots!
Here's a set of WPA2 and WPA3 enabled:
https://imgur.com/a/OaFGYf9

Here's a set of only WPA3 enabled:
https://imgur.com/a/dgqg5sx

I'm not a software developer, so please forgive me if this is incorrect information, but I googled and found this, which looks like it may be how you can implement support to detect WPA3:
https://source.android.com/devices/tech/connect/wifi-wpa3-owe

**Comment by VREMSoftwareDevelopment** [comment]
Can you please provide Access Points screenshot from the WiFi Analyzer Application clearly showing the access point with WPA3 enabled?

**Comment by Jon8RFC** [comment]
There are three images in each set I linked to, with the second image being a screenshot from the application.  Is there something else I'm not understanding that you're needing?

**Comment by VREMSoftwareDevelopment** [comment]
Sorry, did not see images below

WPS, WEP, WPA and WPA2 have a clear definition in security description.

WPA3 does not
- RSN-PSK+SAE-CCMP
- RSN-SAE-CCMP

**Comment by VREMSoftwareDevelopment** [comment]
Can you please enable WiFi verbose logging in developer options - android settings and upload screenshot of WiFi in android settings (WiFi detail information)?

**Comment by VREMSoftwareDevelopment** [comment]
The fix will be available in next release.

**Comment by Jon8RFC** [comment]
Thanks for sharing the background info.  It's always interesting to hear that stuff.  Thanks for the fix, too!

**Comment by Jon8RFC** [comment]
I was peeking at the commits and thought it might be helpful to show that the RSA line being shown might just be an Android 10 thing (can't remember about 9 since I was only on it for a few weeks):
https://imgur.com/a/mSRpbIf

**Comment by huajianjiang** [comment]
> Sure, I can help and share some screenshots! Here's a set of WPA2 and WPA3 enabled: https://imgur.com/a/OaFGYf9
> 
> Here's a set of only WPA3 enabled: https://imgur.com/a/dgqg5sx
> 
> I'm not a software developer, so please forgive me if this is incorrect information, but I googled and found this, which looks like it may be how you can implement support to detect WPA3: https://source.android.com/devices/tech/connect/wifi-wpa3-owe

Hi, according to your router configuration capabilities, may u post more pics about different WAP configuration sets?
BTW, I am developing a more advance and modern Wi-Fi apps.
Thanks advance.

**Comment by Jon8RFC** [comment]
@huajianjiang you can use a third party firmware on a wide variety of routers to gain access to different and additional configurations.
Openwrt, ddwrt, tomato, and others.

**Comment by huajianjiang** [comment]
@Jon8RFC Unfortunately, my purchased WiFi 6 router(Netgear RAX20) recently doesn't support flash any third-part firmware.
