### ISSUE TITLE
Does WiFiAnalyzer Provide Information of Wifi Mode g/n/ac?

### ISSUE THREAD

**Issue by ariefcfa** [VREMSoftwareDevelopment/WiFiAnalyzer#268]
Hi, i tried to compare WiFiAnalyzer for android and WiFi Analyzer on Windows PC.

In Windows, i can see the wifi mode, but in WiFiAnalyzer for android i can see:
signal strenght
channel widht
radio band
security
wifi vendor name
my ip address
network speed
xx.xm -> i don't know what is this

does WiFiAnalyzer provide wifi mode?

thanks in advance.
cheers :)

**Comment by VREMSoftwareDevelopment** [comment]
Application relies on the information provided by Android API.
https://developer.android.com/reference/android/net/wifi/ScanResult
Currently scan result do not provide WiFi mode.
If you are aware any other functionality in Android API that can provide the information you are looking for, please provide links,
