### ISSUE TITLE
Labels in the tabbed menu do not scale nicely when using Android native scaling

### ISSUE THREAD

**Issue by o-l-a-v** [VREMSoftwareDevelopment/WiFiAnalyzer#271]
**Describe the bug**
Labels in the tabbed menu do not scale nicely when using Android native scaling. The label turns into multiline, where 2nd lind and beyond gets hidden. Been like this for multiple releases back in time.

**To Reproduce**
Scale Android system to more than 100%.

**Expected behavior**
Labels should either scale or stay the same size. They should not be cut of/ missing, like the screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/6450056/70376215-d4dd6a00-1906-11ea-99cb-5050a1eb9372.png)

**Note**
App v2.1.1

**Additional context**

**Provide Device/Android OS information**
OnePlus 6 with Oxygen OS 10.0.1 (Android 10), no mods.

**Comment by VREMSoftwareDevelopment** [comment]
Application is using library provided by Android API to display bottom navigation.
Current issue in the library: [Long text cutting off in BottomNavigationView](https://github.com/material-components/material-components-android/issues/139)

Here are a few solution that are possible:
- Do not use scaling
- Wait until Android will fix the library
- Do not display text, display only icons
- Make display text shorter
- Create custom navigation view

Would you like to help with this? It would be great to add new contributors to this project.

Duplicate #257, #264

**Comment by VREMSoftwareDevelopment** [comment]
Google has update the library, this update will be available in the next release.

**Comment by Rikk** [comment]
New version cuts even more titles on my little resolution. Only difference may be the "..." on the cut part (not helpful at all).
