### ISSUE TITLE
Make filter for SSID not case sensitive

### ISSUE THREAD

**Issue by o-l-a-v** [VREMSoftwareDevelopment/WiFiAnalyzer#272]
Filter for SSID is case sensitive. Please change it to not be case sensitive.

In this example, my SSIDs are "OL" and "OL-Guest".
![Filter - Name](https://user-images.githubusercontent.com/6450056/70376418-2ab31180-1909-11ea-853c-4917159c69f5.gif)

**Comment by VREMSoftwareDevelopment** [comment]
It's technically more elegant to have SSID filter to be case sensitive. Correct behavior can differ from locale to locale, so to have correct case insensitive behavior across all languages is actually quite tricky. So being case sensitive makes solution much easier.

[How to use SSID filter?](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/issues/125)
