### ISSUE TITLE
Filter on encryption (WPA2 for instance) does not work.

### ISSUE THREAD

**Issue by o-l-a-v** [VREMSoftwareDevelopment/WiFiAnalyzer#273]
**Describe the bug**

Filter for encryption does not work. All networks around me is WPA2. When choosing WPA2 all networks disappear.

**To Reproduce**

* Reset filters.
* Make sure you have networks with WPA2 around you.
* Filter to show WPA2 only.
* All networks disappear.

**Expected behavior**
WPA2 networks should remain.

**Screenshots**
![Filter - Encryption](https://user-images.githubusercontent.com/6450056/70376460-a8771d00-1909-11ea-8b08-9bb966a3aa24.gif)

**Note**

App version 2.1.1.

**Provide Device/Android OS information**

OnePlus 6 with OxygenOS 10.0.1 (Android 10). No mods.

**Comment by o-l-a-v** [comment]
If I choose WPA2 and WPA3, even though there are none WPA3 networks around me, some of the networks appear in the list.

**Comment by VREMSoftwareDevelopment** [comment]
There are WPA3 networks.
Reference: [Missing WPA3 filter and security icon.](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/issues/267)

**Comment by Jon8RFC** [comment]
Very odd.  For me, the filters work as expected in the graphs and AP list on both spectrums.

app 2.1.1 51GS (10-29)
Pixel 4 (google store version)
Android 10 Dec 2019 update (QQ1B.191205.012.A1)

**Comment by VREMSoftwareDevelopment** [comment]
The fix will be available in next release.
