### ISSUE TITLE
Access point alias

### ISSUE THREAD

**Issue by ddkgit** [VREMSoftwareDevelopment/WiFiAnalyzer#274]
Not a bug, but a feature request. Tried to do this via google groups link but it says 'no such group'.
It would be REALLY helpful if you could add an alias feature ie. allow me to provide an alias for a given AP. Currently I have several by same manufacturer so only way to tell them apart on the AP list is by the mac, which is a bit painful. Great app, thanks.

**Comment by VREMSoftwareDevelopment** [comment]
Please use provided templates to report bugs or request features.
