### ISSUE TITLE
Extension channel offset by 2

### ISSUE THREAD

**Issue by Sanduxy** [VREMSoftwareDevelopment/WiFiAnalyzer#275]
The app (version 2.1.1 - 51GS(10-29)) shows the extension channel offset by 2.
Instead of 3+7 it shows 3+5.
Instead of 13+9 it shows 13+11.

**Comment by VREMSoftwareDevelopment** [comment]
Please use provided templates to report bugs or request features.

Take a look at [FAQ](https://vremsoftwaredevelopment.github.io/WiFiAnalyzer/#faq) sections on our website specifically "How channel graph displays 20/40/80/160 MHz channel width?".
