### ISSUE TITLE
Wi-Fi is not spelled the same way in each language

### ISSUE THREAD

**Issue by Meteor0id** [VREMSoftwareDevelopment/WiFiAnalyzer#276]
I just noticed that there where two commits to make the spelling of Wi-Fi consistent, these commits also overwrite languages other than English.

This is a mistake. The word Wi-Fi is spelled in different way across languages. decisions about spelling should be left to volunteers who localize the software. I recommend to revert those two commits for any language other than English.

In Dutch the word is spelled 'wifi'. In German it is 'wlan' (which is derived from the English acronym for wireless local area network).

**Comment by VREMSoftwareDevelopment** [comment]
"Wi‑Fi" is a registered trademark of the non-profit Wi-Fi Alliance. 
This is a reason to change name in every language to "Wi-Fi" to respect the trademark.

Reference: [Wi-Fi](https://en.wikipedia.org/wiki/Wi-Fi)

**Comment by Meteor0id** [comment]
Yes the trademark is spelled Wi-Fi, but whether or not a language adopts the trademark as the word for wireless network connection is language specific. In Germany and China the word Wi-Fi is not used at all, in many languages the governments are forced by law to follow national recognized spelling, which often is wifi or WiFi not Wi-Fi.

**Comment by VREMSoftwareDevelopment** [comment]
Update will be available in next release.
