### ISSUE TITLE
 Group Virtual Access Points

### ISSUE THREAD

**Issue by bobpaul** [VREMSoftwareDevelopment/WiFiAnalyzer#279]
Modern access points can often host multiple SSIDs simultaneously from a single radio. This is frequently used to support different network credentials for guests, make it easier for clients to force a connection to 5GHz, etc. Vendors usually support this by incrementing the hardware Mac address (BSSID). Because they're Virtual, they're on the same channel as the primary SSID.

So looking at my scan results I see just from my own router in the living room:
* Channel 3
** MyHouse - 01:23:45:67:89:D8
** MyHouseGuest - 01:23:45:67:89:D9
** MyHouseIoT - 01:23:45:67:89:DA
* Channel 36
** MyHouse - 01:23:45:67:89:DC
** MyHouseGuest - 01:23:45:67:89:DD
** MyHouse5G - 01:23:45:67:89:DE

My several of my neighbors have similar configurations with 1 or more guest networks. Because of crowding, some of my neighbors are on the same channels as my access points.

Currently there's no grouping option for this. While I can group by channel, that puts my access points into the same bin with neighbors. I can group by SSID, but that splits my access point into several bins.

This also causes problems with the channel rating, as rating is determined by SSID on a channel when it should really be unique radios. 

--- 

I would like to see an option like 
[ ]  Group Virtual Access Points

This would combine access points that have different SSIDs but consecutive BSSIDs. This group should be treated as a single access point in the channel rating.

**Comment by VREMSoftwareDevelopment** [comment]
This is an interesting idea for a feature. 
Unfortunately all current contributors are busy with other work. 
When we don't have an opportunity to implement a feature, we encourage developers to become a contributors. 
It would be great to add new contributors to this project.
 
Please next time use feature request template.

Thank you,
The VREM Development Team

**Comment by bderleta** [comment]
@bobpaul Do you know the reliable method to distinguish whether a group of MAC addresses is a single radio or different radios? I'd like to try implementing it, but I think we should not rely on just observation that MAC address is being incremented, unless this is proven and backed by some document.

**Comment by VREMSoftwareDevelopment** [comment]
@bobpaul 
**This also causes problems with the channel rating, as rating is determined by SSID on a channel when it should really be unique radios.**

Application channel rating algorithm takes in account Virtual Access Points 
Duplicate #31

**Comment by VREMSoftwareDevelopment** [comment]
@bderleta 
The following could be a good point to start:
- https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/blob/feature/app/src/main/java/com/vrem/wifianalyzer/wifi/model/ChannelRating.java
- https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/blob/feature/app/src/main/java/com/vrem/wifianalyzer/wifi/model/ChannelRating.java#L63

**Comment by bderleta** [comment]
@VREMSoftwareDevelopment ok, it looks like all I need for that...

**Comment by ersabine** [comment]
Thank you for the open source project. 

Could you please describe the main principle behind the channel rating? It could be great if you provide any document related to channel rating and best channel selection.

**Comment by VREMSoftwareDevelopment** [comment]
@ersabine channel rating code is available for a anyone review, see above links

**Comment by VREMSoftwareDevelopment** [comment]
will be available in next release.
