### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by VREMSoftwareDevelopment** [VREMSoftwareDevelopment/WiFiAnalyzer#28]
Translate provided text to Spanish
[English.zip](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/files/253926/English.zip)

**Comment by GreenLunar** [comment]
I suggest to enumerate, in title, the strings or words to translate

**Comment by VREMSoftwareDevelopment** [comment]
Current release V1.5.4 Play Store.
This feature will be available in the next release
