### ISSUE TITLE
Set language isn't used in WiFiAnalyzer 2.1.1

### ISSUE THREAD

**Issue by Anonymous123456789012** [VREMSoftwareDevelopment/WiFiAnalyzer#281]
Good day

Firstly, I want to thank you very much for creating "WiFiAnalyzer"!
It's awesome software!

I found regression in WiFiAnalyzer 2.1.1, which didn't exist in WiFiAnalyzer 2.0.8.
When I change language of WiFiAnalyzer 2.1.1 in settings, set language isn't used. 

STR:
1. Go to "Settings"
2. Change "Language" preference from "Polish" to "English" (in my case) or from "English" to other language

and see that language of WiFiAnalyzer didn't change to set language in settings.

Bad:
https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/releases/tag/V2.1.1-F-DROID

Good:
https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/releases/tag/V2.0.8-F-DROID

I'm using WiFiAnalyzer 2.1.1 on Android 6.0.1 on Sony Xperia Z3 Compact and LG Spirit.

Best regards

**Comment by VREMSoftwareDevelopment** [comment]
We are not able to reproduce the issue that you are reporting. Please try to re-install the application.

Also do not forget:
- to use provided templates to report issues (Default or Bug report template) or request features (Feature request template).
- to fill all questions/topics in the templates.

**Comment by Anonymous123456789012** [comment]
I'm want to add that issue is not fixed and it is still reproducible in WiFiAnalyzer 2.1.2.
To easily reproduce this issue just change you Android language to Polish, start WiFiAnalyzer, change WiFiAnalyzer language from Polish to English, restart WiFiAnalyzer and see that it's still using Polish language instead of English one. Could you @VREMSoftwareDevelopment reproduce it maybe with these additional steps? If not, it could be maybe specific Android version issue.
