### ISSUE TITLE
Last part of text on some visible and on many selected items ("Access Points", "Channel Rating", "Channel Graph", "Time Graph") aren't shown

### ISSUE THREAD

**Issue by Anonymous123456789012** [VREMSoftwareDevelopment/WiFiAnalyzer#283]
Good day

Firstly, again, and again, I want to thank you very much for creating "WiFiAnalyzer"!
It's awesome software!

In WiFiAnalyzer 2.1.1 and older: WiFiAnalyzer 2.0.8, WiFiAnalyzer 2.0.7, WiFiAnalyzer 2.0.5,
"Access Points", "Channel Rating", "Channel Graph", "Time Graph" items from menu were also added as shortcuts to newly created bottom menu.
Last part of text on some visible items and on many selected items aren't shown.

STR:
1. Press "Channel Rating" item in bottom menu
and see only "Channel" text on "Channel Rating" item

In other languages, e.g. "Polish",
"Access Points" (ENG) = "Punkty dostępu" (PL)
are shown as only "Punkty".

I'm using WiFiAnalyzer 2.1.1 on Android 6.0.1 on Sony Xperia Z3 Compact and LG Spirit.

Best regards

**Comment by VREMSoftwareDevelopment** [comment]
Please use provided templates to report issues (Default or Bug report template) or request features (Feature request template). 
Please do not forget to fill all questions/topics in the templates.

Duplicate #271, #257, #264

**Comment by Anonymous123456789012** [comment]
I'm confirming that issue is fixed in WiFiAnalyzer 2.1.2.
Thank you very much!
