### ISSUE TITLE
WPS selector doesn't work

### ISSUE THREAD

**Issue by 532910** [VREMSoftwareDevelopment/WiFiAnalyzer#285]
With clean filter it shows:
![image](https://user-images.githubusercontent.com/14617699/75387285-2a1c8c80-58f4-11ea-9eaf-34fa59f31ba7.png)

but when I select WPS:
![image](https://user-images.githubusercontent.com/14617699/75387002-afec0800-58f3-11ea-8fcc-924e9e73b900.png)

it shows nothing(only currently connected network):
![image](https://user-images.githubusercontent.com/14617699/75387103-dca01f80-58f3-11ea-88d0-669f48dcea97.png)

WiFiAnalyzer 2.1.1 51S (9-28) from F-Droid, LineageOS 16.0 Android 9 OP3t

**Comment by VREMSoftwareDevelopment** [comment]
- Please use provided templates to report issues (Default or Bug report template).
   - Do not forget to fill all questions/topics in the templates.
   - This help us to investigate and response to the issue faster.
- [How to report a bug](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Feedback)
- Do not forget to search issues (open and closed) to see if the issue has been reported previously.

Duplicate #273
