### ISSUE TITLE
Android 9+ WiFi scan throttling on Android v10  Huawei Pro

### ISSUE THREAD

**Issue by GegeApl** [VREMSoftwareDevelopment/WiFiAnalyzer#290]
**Describe the bug**
Values are not refreshed and are never updated 
On Android v10 (huawei p30 pro) 

**To Reproduce**
1. Go to '...' history - display values
2. Click on '....' refresh
 Values are not refreshed  : always the same

**Expected behavior**
Scroolling of Life data 

**Screenshots**
Freezed valued
![Screenshot_20200329_140003_com vrem wifianalyzer](https://user-images.githubusercontent.com/12157067/77848900-34b69400-71c8-11ea-806c-a1d2ff80f227.jpg)

**Note**
Some behaviour only occurs on certain devices or versions of Android, please provide the following screenshots/information Device/Android OS (Settings → About Phone) 
![Screenshot_20200329_142114](https://user-images.githubusercontent.com/12157067/77848984-adb5eb80-71c8-11ea-9e3b-fdafb711d1ae.jpg)

and WiFi Analyzer version (Menu -> About)
![Screenshot_20200329_142402](https://user-images.githubusercontent.com/12157067/77849029-fb325880-71c8-11ea-993a-c536b2673408.jpg)

**Additional context**
Expected work in background
![Screenshot_20200329_142645_com huawei systemmanager](https://user-images.githubusercontent.com/12157067/77849116-84e22600-71c9-11ea-9ec6-59828cb5e3d5.jpg)

But wifi values are freezed

**Provide Device/Android OS information**
Android v10
Huawei P30 pro

**Comment by VREMSoftwareDevelopment** [comment]
Please take a look at [FAQ](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer#faq) section: Android 9+ throttling Wi-Fi scanning

Duplicate #278, #269, #242, #231
