### ISSUE TITLE
Do not turn off in wifi if I am connected

### ISSUE THREAD

**Issue by wuniversales** [VREMSoftwareDevelopment/WiFiAnalyzer#295]
I find the option to turn off WiFi very useful when exiting the application, however, if I am connected to a WiFi network ... Why turn it off?

That option is fine in certain situations, but it really bothers when for example you are checking the channel of your Wi-Fi network, you exit the app and the WiFi turns off.

In my opinion it would be better to add one more option that allows "do not turn off in wifi if I am connected"

**Comment by VREMSoftwareDevelopment** [comment]
This is an interesting idea for a feature.
Unfortunately all current contributors are busy with other work.
When we don't have an opportunity to implement a feature, we encourage developers to become contributors.
It would be great to add new contributors to this project.

When requesting a feature, please use feature request template.
