### ISSUE TITLE
We found 1 test flaky

### ISSUE THREAD

**Issue by shaker-project** [VREMSoftwareDevelopment/WiFiAnalyzer#298]
We run your test cases for 50 times and found that the following test is flaky [1] (i.e., they pass or fail non-deterministically):

- testNavigation

We ran these tests on a generic Android Emulator (AVD) with Android API version 28.

To reproduce failures on these tests, please run the following script on gist:
https://gist.github.com/shaker-project/aa36af5d1be2638caf8f6e2e50768864
If you didn't understand any point of the script we can explain.

We require that stress-ng is installed. If not, run $> sudo apt-get install stress-ng.

If you confirm this behavior, our suggestion is to add the annotation @TestFlaky on these tests. See https://developer.android.com/reference/androidx/test/filters/FlakyTest

If you wish for a repair proposal, please let us know.

[1] https://hackernoon.com/flaky-tests-a-war-that-never-ends-9aa32fdef359

**Comment by VREMSoftwareDevelopment** [comment]
Can you please explain what fails in the above test `testNavigation`, since it does not have any assertions?
