### ISSUE TITLE
Filter unencrypted networks broke in 2.1.2

### ISSUE THREAD

**Issue by Tetrix42** [VREMSoftwareDevelopment/WiFiAnalyzer#299]
[How to report a bug](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Feedback)

**Please search issues (open and closed) to see the issues has already been reported.**
I belive it is related to issue #273, but it has been closed

**Describe the bug**
The bug appeared in version 2.1.2
I have an unencrypted network near by.
I see it if i do not apply filters, but if i apply the filters to show only unencrypted networks, no networks will show.

Interestingly if i only disable WPA3, unencrypted networks also wont show, while WPA2 are still shown.

**To Reproduce**
1. Have unencrypted network near by
2. Set filter to show only unencrypted networks
3. network will not show

**Expected behavior**
the network filters should be applicable selectively.

**Screenshots**

**Note**

**Additional context**

**Provide Device/Android OS information**
Sony Xperia Z5c
Android 7.1.2
LineageOS 14.1

**Comment by VREMSoftwareDevelopment** [comment]
Will investigate unencrypted network filter.

WPA3/WPA2 issue please take a look at [Missing WPA3 filter and security icon.](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/issues/267)

**Comment by VREMSoftwareDevelopment** [comment]
unencrypted network filter fix will be available in next release.
