### ISSUE TITLE
*** signal mirrors my own network

### ISSUE THREAD

**Issue by chriswaddler** [VREMSoftwareDevelopment/WiFiAnalyzer#300]
[How to report a bug](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Feedback)

**Please search issues (open and closed) to see the issues has already been reported.**

**Describe the bug**
I've split my ssid's and on both my main router and access point. My access point's (tp link c6) network is being mirrored by another signal across both 2.4 GHz and 5Gz signals, which shows as *** - see pics. I'm guessing it's being broadcast by my access point and would like to know whether I need to change a setting to remove it or if this second mirror signal will cause interference.

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_20200609-104014](https://user-images.githubusercontent.com/66672534/84133391-06162e80-aa3f-11ea-867b-b84f35376091.png)
![Screenshot_20200609-104006](https://user-images.githubusercontent.com/66672534/84133393-07475b80-aa3f-11ea-995a-a0cb6ef2dab1.png)

**Note**
Some behaviour only occurs on certain devices or versions of Android, please provide the following screenshots/information Device/Android OS (Settings → About Phone) and WiFi Analyzer version (Menu -> About)

**Additional context**

**Provide Device/Android OS information**

**Comment by chriswaddler** [comment]
Sorry, I think this is a router issue not related to wifi analyzer

**Comment by VREMSoftwareDevelopment** [comment]
SSID with *** or *hidden* means it is hidden. 
Check you router settings, specifically wireless settings and option: `Hide SSID`
