### ISSUE TITLE
Improve Access Points width display in the Channel Graph

### ISSUE THREAD

**Issue by IRainman** [VREMSoftwareDevelopment/WiFiAnalyzer#302]
There is an error in the application - the spectral width of the channels is incorrect. Should be 20 MHz (16.25 real) for 20 MHz channels and 40 MHz (33.75 real) for 40 MHz channels, etc. for wider channels. In the Wikipedia data about this already correct https://en.wikipedia.org/wiki/2.4_GHz_radio_use#Wi-Fi  

The channels in the application are less wide than in reality!

For example, the networks S2k and MGTS_GPON_2100 are overlapping in frequencies in reality (Channel 13 and 11).

![Screenshot_20200715-125146](https://user-images.githubusercontent.com/3396559/87697735-28683e00-c79b-11ea-800b-5bd7bb7af2a5.jpg)

For comparison I add a screen of another analyzer with correct frequency bandwidth. 

![wi-fi-fine](https://user-images.githubusercontent.com/3396559/87697742-2aca9800-c79b-11ea-9463-8922be6f69e8.PNG)

**Comment by VREMSoftwareDevelopment** [comment]
@IRainman  please provide the following:
- screenshot from the application: access points screen with full details per access points in question.
- screenshots or information Device/Android OS (Settings → About Phone) and WiFi Analyzer version (Menu -> About)

Please use provided templates next time when reporting an issue (Default or Bug report template) or request a feature (Feature request template). Please do not forget to fill all questions/topics in the templates.

**Comment by IRainman** [comment]
![Screenshot_20200719-154553](https://user-images.githubusercontent.com/3396559/87875137-be88a800-c9d7-11ea-969e-8865fb81272c.jpg)
![Screenshot_20200719-154601](https://user-images.githubusercontent.com/3396559/87875138-bfb9d500-c9d7-11ea-8773-003766308d6d.jpg)
![Screenshot_20200719-154616](https://user-images.githubusercontent.com/3396559/87875139-c0526b80-c9d7-11ea-8cf8-0f098773acec.jpg)
![Screenshot_20200719-154631](https://user-images.githubusercontent.com/3396559/87875140-c0eb0200-c9d7-11ea-853b-cc3baab60876.jpg)

**Comment by VREMSoftwareDevelopment** [comment]
@IRainman 
- S2k primary channel 13 (2472Mhz) width 20Mhz (2462 - 2482 Mhz)
- MGTS_GPON_2100 primary channel 1 (2412Mhz) width 20Mhz  (2402 - 2422 Mhz)

The above information is from the screenshots you have provided. 
Both access points have 20Mhz width.

**Comment by IRainman** [comment]
The problem is in the spectral width, for other example: Onlime2 is working on the ch. 8 and 6. and occupy channels from 2 to 10, but in WiFiAnalyzer show this network only from 3 to 9.

**Comment by VREMSoftwareDevelopment** [comment]
We would assume that you are referring to channel graph display.
Top of every access point graph shows 2 channels less, looking at the graph at the bottom of the display shows all the channels that are occupied by the access point. This is done to make the access point graph display visually appealing to the eye (not to show rectangle view). 

"Onlime2" occupies channels 2 to 10 and by looking at WiFi channel axis at the bottom of the graph shows channels 2 to 10.

**Comment by IRainman** [comment]
Yes, the problem is in the channel graph display, but the visual appeal does not represent the reality of the signal spectrum. After all, the application is an analyzer, not a drawing of beautiful pictures. In the first message I added a picture from another application with the correct spectrum display. For other example I add other picture with the spectrum analyzer.
[first](https://hsto.org/webt/ks/k3/rc/ksk3rcj7m0yze7qcflo5h8y4h_c.jpeg)
[second](https://hsto.org/webt/ho/3u/hk/ho3uhkvjv2c4ustm6svdgm2xmvs.png)

**Comment by VREMSoftwareDevelopment** [comment]
We will not have an opportunity to implement this feature in the near future, since  all current contributors are busy with other work. 

When we don't have an opportunity or time to implement a feature, we encourage developers to fork the project and become a contributor. It would be great to add new contributors to this project.

**Comment by VREMSoftwareDevelopment** [comment]
will be available in next release.
