### ISSUE TITLE
DFS channel support in South Korea 

### ISSUE THREAD

**Issue by horim80** [VREMSoftwareDevelopment/WiFiAnalyzer#305]
Please add 5GHz DFS scanning when region is South Korea.

-----------------------
**Please search issues (open and closed) to see the issues has already been reported.**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**How I can help**
A clear and concise description of what you can do to help.

**Additional context**

**Provide Device/Android OS information**

**Comment by VREMSoftwareDevelopment** [comment]
Please use provided templates to request features and do not forget to fill all questions/topics in the templates.

[How to provide Feedback](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer#feedback)
