### ISSUE TITLE
Where to find an explanation for the terms primary channel and center channel?

### ISSUE THREAD

**Issue by Tronde** [VREMSoftwareDevelopment/WiFiAnalyzer#309]
Hello there,
Since the [google group](https://groups.google.com/forum/#!forum/wifi-analyzer-open-source) doesn't seem to exist anymore or access is restricted I'd like to ask my question, here.

What is the meaning of the terms primary channel and center channel?

I found these terms in issue [#64](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/issues/64) but I don't understand their meaning. An explanation or a hint where to find one would be great.

Regards,  
Tronde

**Comment by VREMSoftwareDevelopment** [comment]
**Google groups require GMail account**

Here are few links **"What is the meaning of the terms primary channel and center channel?"**
- [http://www.revolutionwifi.net/revolutionwifi/2013/03/80211ac-channel-planning.html](http://www.revolutionwifi.net/revolutionwifi/2013/03/80211ac-channel-planning.html)
- [https://documentation.meraki.com/MR/Radio_Settings/Channel_Bonding](https://documentation.meraki.com/MR/Radio_Settings/Channel_Bonding)
