### ISSUE TITLE
Remove Guest Access Points from Channel Rating

### ISSUE THREAD

**Issue by ralfbergs** [VREMSoftwareDevelopment/WiFiAnalyzer#31]
Hi guys.

Thanks for this great open-source tool. :-)

I think the channel rating tool may have a small quirk (or maybe I don't fully understand it?):

I fortunately operate the only AP on the 5 GHz band in range. I've set my OpenWrt router to spawn two SSIDs on the same radio, one which is my "main" SSID, then a guest SSID. Both SSIDs are obviously on the same channel, as they are provided by the same radio.

In this case WiFiAnalyzer should not recommend me to move to a different channel, as it should detect it's the same AP (same channel, same BSSID). But it seems to do so, as it always indicates the channel my AP is set to as "average" (yellow) or even "bad" (red), and shows "Best Channels: <all the channels I'm not using>".

Is that a corner-case you didn't consider?

Kind regards,

Ralf

**Comment by VREMSoftwareDevelopment** [comment]
Hi Ralf, 

Channel Rating is used to identify crowded channels. The algorithm uses number of access points and their signal strength to rate each channel (including your own Access Points). 

Are you suggesting to add a new feature: to be able to exclude some Access Points from Channel Rating?

Having different SSID, same BSSID and same channel number is not enough to guaranty that it is the same Access Points. Some router software, which includes TomatoUSB, AdvancedTomato, OpenWRT, DD-WRT and others allow users to customize BSSID.

Thanks for you input,

VREM Software Development

**Comment by VREMSoftwareDevelopment** [comment]
Current release V1.5.3 Play Store / V 1.5.4 F-Droid
This feature will be available in the next release

**Comment by ralfbergs** [comment]
Thanks!
