### ISSUE TITLE
Add Privacy Policy to the project

### ISSUE THREAD

**Issue by bepstein** [VREMSoftwareDevelopment/WiFiAnalyzer#310]
I've not seen this feature request in previous issues.

I would like to see WiFiAnalyzer made available to K-12 schools so that students can use it on their school provided Chromebooks with access to the Google Play store.  This would allow them to determine where the deadzones are in their houses and find the best place to work.

School districts are very cautious about which Apps are allowed on their school provided devices.  Having a clear policy document on privacy and specifically student privacy would make it easier to request this app to be added to the list of approved apps for K-12 schools.

I would like for a PRIVACY.md file placed into the root of the GitHub project describing how this project does not collect any data for use or resale.  This could be similar to the paragraph on the Google Play store which talks about user privacy.

"Users' privacy and security is a huge concern these days and WiFi Analyzer (open-source) is designed to use as few permissions as possible. It asks for just enough to perform the analysis. Plus, it is all open source so nothing is hidden! Most notably, this application does not require access to internet, so you can be sure it does not send any personal/device information to any other source and it does not receive any information from other sources."

I have spoken with school administrators and pointed out that the paragraph above exists.  Although it is helping, having a clear document in the GitHub repository would make that policy seem more official.  Changes to the policy would require a documented change control event if it were modified in the future.

I would be glad to fork the repo to try to write the policy.  However, I've not read through the code to ensure that no data collection is going on (although I'm sure that is true).  It may be better coming from the authors themselves.

The school also suggested getting the application certified through https://ikeepsafe.org/certification/ferpa/ .  I would be glad to look into it, but wanted to get feedback from the authors about the desire to add a privacy statement before I went any further.

Definitely appreciate everyone's time and effort into this great application.  I think that it could really help a lot of students out there struggling to get good reliable connections during the current pandemic, and would ensure that it is available to them in the case of a recurrence in the future.

Thanks,
Brian

**Comment by VREMSoftwareDevelopment** [comment]
New contributors are always welcome to the project. 
Please submit PR with the your changes **"privacy statement"**  for a review.
