### ISSUE TITLE
Display WPA3 & PMF

### ISSUE THREAD

**Issue by jbacksch** [VREMSoftwareDevelopment/WiFiAnalyzer#311]
[How to report a bug](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Feedback)

**Please search issues (open and closed) to see the issues has already been reported.**
done

**Describe the bug**
WiFiAnalyzer does not show WPA3 and PMF flags in the Access Points menue. 

**To Reproduce**
1. Go to 'Access Points'

**Expected behavior**
Show WAP3 and PMF flags like WPA3, PSK, and so on

**Screenshots**
Mssing WPA3 % PMF flags in https://lh3.googleusercontent.com/YRscuij--IUjnpz3Fmrvbhmaw4HLDxpUhp_gbaEdK-sZVV6j_nrPKViFDGQmpUv2Hg=w1440-h620

**Note**
Android 11, Pixel 3 & Pixel 4

**Additional context**
none

**Provide Device/Android OS information**
Android 11 Pixel 3 & Android 11 Pixel 4

**Comment by VREMSoftwareDevelopment** [comment]
Please use provided templates to report a bug or request features and do not forget to fill all questions/topics in the templates.

[How to provide Feedback](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer#feedback)

**Comment by VREMSoftwareDevelopment** [comment]
@jbacksch the information that was provided is not enough to investigate the issue.
Please fill all questions/topics in the templates to help us to investigate and solve reported issue.

**Comment by jbacksch** [comment]
Questions have been updated in template format. See above.

**Comment by VREMSoftwareDevelopment** [comment]
@jbacksch 

Based on the information you have provided, it looks like Access Points that are available to you do not support WPA3.

Also please take a look at #267 

Which version of the application are you using?

**Comment by jbacksch** [comment]
APs are fully supporting WPA3 - has been verified with other STAs:
- 
- WPA3 SAE (CCMP) on AP shown as [RSN-SAE-CCMP][ESS] in WiFiAnalyser
- WPA3 802.1X (CCMP) an AP shown as [RSN-EAP_SUIT E_B_192-CCMP][ESS] in WiFiAnalyser

Version: 3.0.1 - 53GSL (11-30) lastest from Google Play Store

**Comment by VREMSoftwareDevelopment** [comment]
@jbacksch you have not provided a screen shoot from your device/phone.

**Comment by jbacksch** [comment]
![WAP3](https://user-images.githubusercontent.com/9435513/96588386-e0017480-12e3-11eb-8b6a-82a3c35db77c.png)
![WAP3 802 1x](https://user-images.githubusercontent.com/9435513/96588404-e394fb80-12e3-11eb-9e66-5f3c576733be.png)

**Comment by VREMSoftwareDevelopment** [comment]
Application correctly display WPA3 Access Points support.
It is not clear to us what is the issue exactly?

**Comment by jbacksch** [comment]
Sorry, but the string WPA3 is only included in the SSID (eg. "backschues.NET - WPA3"). 
WPA3 is not shown in the AP's characteristics.

**Comment by VREMSoftwareDevelopment** [comment]
The section that displays information is called **capabilities** and is provided by Android API.
Application does not change this information when it is displayed.
Reference:
[ScanResult](https://developer.android.com/reference/android/net/wifi/ScanResult.html#capabilities)

Maybe mapping of **capabilities** feature will be added in the future release

**Comment by VREMSoftwareDevelopment** [comment]
Translated capabilities will be available in next release.
