### ISSUE TITLE
Statement about WiFi Analyzer by olgor.com

### ISSUE THREAD

**Issue by dbrgn** [VREMSoftwareDevelopment/WiFiAnalyzer#313]
I recently installed this app by the developer "olgor.com" from the Play Store:

https://play.google.com/store/apps/details?id=abdelrahman.wifianalyzerpro

I've been using some version of WiFi Analyzer back in the Android 4 days ([this one?](https://play.google.com/store/apps/details?id=com.farproc.wifi.analyzer) I'm not sure...) and had in mind that it was open source. The version I installed (linked above) is now showing advertising. Additionally, I just got a popup about a sale, offering the app for 2$ instead of 4$.

I'm generally happy to support app developers, so I thought about buying it, but first I wanted to ensure that this is an official version. When searching for other versions of the app, I found this repository, which seems to be the original version of WiFi Analyzer, is that correct? (Or is this a fork as well? Commit history seems to go back to 2016.)

In any case, if the app provided by "olgor.com" in the Play Store is a fork, then it must also be licensed under the GPL license. However, I cannot find any mention in the app itself, it only attributes some libraries used, but doesn't declare the license for the app itself.

A statement would be great. If this is something official, I'm happy to support, but if it's a fork in violation of the GPL license then I don't want to support it.

**Comment by ldmpub** [comment]
It looks like it's an other App because if screens are similar they aren't exactly the same.
Maybe some code has been forked / copied and your question needs are more detailed answer.

**Comment by VREMSoftwareDevelopment** [comment]
@dbrgn

This application is open source with many contributors and was started from scratch.

We are not aware that the applications that you are referring are open source or are clones or copies of our open source application.

If you would like to support open source project, you can find all the necessary information on our [Github](https://vremsoftwaredevelopment.github.io/WiFiAnalyzer) page, such as: links to the application in Google Play and F-Droid store, how to contribute and etc.

**Comment by dbrgn** [comment]
Great, thanks for your reply. I'll request the source code from the other app author, according to the GPL he needs to send it to me. Otherwise you could file a license violation request with the Play Store, in case you're interested in that. (Forks are fine, asking money for them is OK as well if there are additional features, but making money without attribution is not OK.)

**Comment by VREMSoftwareDevelopment** [comment]
@dbrgn when you get the code, we would be interested to have a look at it also.

**Comment by VREMSoftwareDevelopment** [comment]
@dbrgn any luck on getting the code?

**Comment by dbrgn** [comment]
@VREMSoftwareDevelopment oh, sorry, I forgot about this. will try to remember to request the code next week! (By the way, according to the GPL any user that installed the application can request the source code, including all modifications.)

**Comment by VREMSoftwareDevelopment** [comment]
@dbrgn 
Sorry, did not find any reference of the applications being open source and using GPL3 license.
