### ISSUE TITLE
France and ETSI region wrong channel in WiFiAnalyzer

### ISSUE THREAD

**Issue by mrintrepide** [VREMSoftwareDevelopment/WiFiAnalyzer#316]
**Describe the bug**
In ETSI (Europe), channel 144 is not available (only UK use it) and 169 & 173 is available.

**To Reproduce**
With location set in France.

**Expected behavior**
Disable 144 and enable 169 & 173 channel for ETSI region

**Screenshots**
Wrong channel list
![Screenshot_20201108-141258](https://user-images.githubusercontent.com/40322493/98466379-6ddbcb80-21cf-11eb-8ba5-bdcd45e85bdd.png)
Enabled 144 channel
![Screenshot_20201108-141247](https://user-images.githubusercontent.com/40322493/98466385-73391600-21cf-11eb-8600-c9d5ae7bb623.png)
169 and 173 disabled
![Screenshot_20201108-141250](https://user-images.githubusercontent.com/40322493/98466386-746a4300-21cf-11eb-9592-cded31dffee4.png)
Can't see my wireless network with channel 169 or 173
![Screenshot_20201108-144522](https://user-images.githubusercontent.com/40322493/98466736-b6948400-21d1-11eb-8291-ced412d78b03.png)
![Screenshot_20201108-144617](https://user-images.githubusercontent.com/40322493/98466739-b85e4780-21d1-11eb-88d3-7907d408c130.png)

**Note**
![Screenshot_20201108-141554](https://user-images.githubusercontent.com/40322493/98466366-61577300-21cf-11eb-9213-31378e09ba01.png)
![Screenshot_20201108-141558](https://user-images.githubusercontent.com/40322493/98466367-63b9cd00-21cf-11eb-9a22-ae06921131e8.png)
![Screenshot_20201108-141610](https://user-images.githubusercontent.com/40322493/98466369-65839080-21cf-11eb-92ae-8ffd0555fdad.png)

**Provide Device/Android OS information**
Google Pixel 3a XL with stock Android 10 and 11

**Comment by VREMSoftwareDevelopment** [comment]
Application uses [List of WLAN channels](https://en.wikipedia.org/wiki/List_of_WLAN_channel)s as reference which channels are available in which region.
Application does not control or changes the channels, it is only displays available information provided by Android API.
Please submit PR with required fix and links to reference official documentation.

**Comment by mrintrepide** [comment]
Your english Wikipedia link say : 144, 169 and 173 is available for "Europe".

Linux kernel wireless-regdb for [France](https://git.kernel.org/pub/scm/linux/kernel/git/sforshee/wireless-regdb.git/tree/db.txt#n573) and [Germany](https://git.kernel.org/pub/scm/linux/kernel/git/sforshee/wireless-regdb.git/tree/db.txt#n447) cut frequency at 5725 MHz or 144 channel use 5710-5730 MHz. It allow frequency up to 5875 MHz, 173 use 5855-5875 MHz

OpenWrt with FR and DE country code disable 144 and enable 169 and 173.

I can't submit a PR with code.
