### ISSUE TITLE
WPA2 incorrectly displayed as WPA3

### ISSUE THREAD

**Issue by Jon8RFC** [VREMSoftwareDevelopment/WiFiAnalyzer#318]
**Describe the bug**
v3.0.2 displays access points as having WPA3 when they don't.

The string "RSN" is associated with WPA3 but it should be "SAE" as SAE replaced PSK in WPA3.  Currently, when it sees RSN-* (which is not necessarily WPA3, but could be), it tags it as WPA3.  RSN is used with both WPA2 and WPA3, but SAE is used only with WPA3.

**Screenshots**
![wpa3_bug](https://user-images.githubusercontent.com/12204953/98673519-10559500-231d-11eb-866d-386ac16ad488.png)

**Additional context**
This doesn't account for WPA3 Enterprise, but the app currently doesn't account for WPA/WPA2 Enterprise (yet), either.
I looked at making a pull request (not a software developer), but got very confused with certain parts and don't know if I can just swap every instance of RSN for SAE.

**Provide Device/Android OS information**
Pixel 5
Android 11
RD1A.201105.003.C1

**Comment by VREMSoftwareDevelopment** [comment]
@Jon8RFC replacing all RSN with SAE should work.
Clicking on access point in the access point list or graphs will open an popup window with more details?
Can you please create a couple of screenshots with popup window information for WPA2 and WPA3? (Version 3.0.2 only)
Thanks

**Comment by Jon8RFC** [comment]
I added one in at the bottom with 802.11r Fast Transition enabled, which I don't think I've seen other apps display in a concise manner, like how 3.0.2 cleanly shows just "WPA2", for example.

![screenshots](https://user-images.githubusercontent.com/12204953/99095860-443dee00-259b-11eb-9ee0-eb1f26f4d64e.png)

**Comment by VREMSoftwareDevelopment** [comment]
will be available in next release.

**Comment by Jon8RFC** [comment]
I don't understand it all, but is FT being included as an identifier of WPA3?
Just wanted to be sure--it's an independent protocol for roaming between different access points and is not necessarily related to a particular method of authentication or encryption.

I just thought it'd be handy to have an additional indicator, such as [FT] or [802.11r] to go alongside [WPA2], for example, since no other apps show things cleanly like yours does.

**Comment by VREMSoftwareDevelopment** [comment]
Android API scan capabilities information is used only identify security WPS, WPA, WPA2 and WPA3(SAE).
Wi-Fi protocol standard is part on Android 11 API only.
Reference: [ScanResult](https://developer.android.com/reference/android/net/wifi/ScanResult)
If you wish to help and need FT/802.11r,  please create pull request for this new feature.
