### ISSUE TITLE
ignore/group virtual AP

### ISSUE THREAD

**Issue by jedi7** [VREMSoftwareDevelopment/WiFiAnalyzer#323]
Real wifi AP can have also multiple virtual APs. These virtual AP have the same BSSID and channel as the real one.

So from my point of view will be good to group them together and show them as 1 entity.
Also should be usable to hide own APs from the graph (or do not count it negative)  

**How I can help**
testing.

**Provide Device/Android OS information**
WifiAnalyzer: 3.0.2
Android: 9

**Comment by VREMSoftwareDevelopment** [comment]
Please use provided templates to report a bug or request features and do not forget to fill all questions/topics in the templates.

[How to provide Feedback](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer#feedback)

Duplicate #279
