### ISSUE TITLE
mysterious numbers next to AP names in Time Graph

### ISSUE THREAD

**Issue by PontiacCZ** [VREMSoftwareDevelopment/WiFiAnalyzer#325]
In Time Graph there are strange unexplained numbers displayed next to APs names. What is that? I expected to find these numbers in "Access Points" list so I could understand them but they are not there.

How about to add some sort of "help" to the "Time Graph" screen for users to understand what these numbers mean.

![image](https://user-images.githubusercontent.com/9153595/100659639-30430c00-3351-11eb-8952-77a9942e1ad3.png)

**Comment by Sharabaddin** [comment]
@PontiacCZ Example your first item  "Machine 5G 36(42)" 36 - chanel, (42) - i dont now but I think it reserv chanel or chanel has before

**Comment by VREMSoftwareDevelopment** [comment]
These are primary and center channel, you can find them in Access Points, Channel Graph and Time Graph.
Explanation is available in [FAQ](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer#faq) section under **"How channel graph displays 20/40/80/160 MHz channel width?"** and issues #64 and #309.
