### ISSUE TITLE
Incorrect band frequency range 

### ISSUE THREAD

**Issue by huajianjiang** [VREMSoftwareDevelopment/WiFiAnalyzer#327]
**Describe the bug**
2.4 GHz and 5 GHz frequency range is not the same as [wikipedia ](https://en.wikipedia.org/wiki/List_of_WLAN_channels)described

**To Reproduce**
Open WiFiChannelsGHZ2.java and WiFiChannelsGHZ5.java

**Expected behavior**
2.4 GHz should be 2401 ~ 2495 MHz
5 GHz should be 4910 ~ 5875 MHz

**Screenshots**
![2ghz](https://user-images.githubusercontent.com/12984573/102578498-47497280-4135-11eb-8341-491a5ac93a04.jpg)
![5ghz](https://user-images.githubusercontent.com/12984573/102578502-49abcc80-4135-11eb-9b8f-abd93888eb48.jpg)

**Comment by VREMSoftwareDevelopment** [comment]
Please explain what does not work in the application based on your statement:
> 2.4 GHz and 5 GHz frequency range is not the same as Wikipedia described

**Comment by huajianjiang** [comment]
I have not found any application problems caused by this, but theoretically this is an implicit problem. 
What I am confused about is why you define it as not based on Wikipedia.

**Comment by VREMSoftwareDevelopment** [comment]
All current contributors are busy with other work or other projects.
Currently there is no one available to investigate theoretical issue.
When there is no an opportunity to implement/investigate the request, we encourage developers to become contributors.
It would be great to add new contributors to this project.

**Comment by huajianjiang** [comment]
OK, thank you for your great project.
By the way, anyone who know why can tell me , thanks advance.
Peace.
