### ISSUE TITLE
Android 6

### ISSUE THREAD

**Issue by Rikk** [VREMSoftwareDevelopment/WiFiAnalyzer#329]
1. [Question] I've moved from a phone with Android 5 to another with 6. I know some time ago (v2.0.2 onwards) Location started being required (https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Location-Service-Permission-Requirements). Despite of that, version 1.9.3 works fine on my Android 6.0.1 (Samsung J500M).
Now, my questions: Are there other Android 6 devices where app doesn't work without Location enabled? Could you add exceptions to those not requiring it?

2. [Feature suggestion] New option "Location off on exit" (similar "wifi off on exit"), because sometimes we need to enabled it only for using the app and forget to turn it off.

3. To repro: Open the app with Location disabled, don't enable Location when system screen appears, press Back key. Now it seems like the system screen entered in loop and doesn't go back to app nor quit it. This seems not a friendly behavior. It's ok the app requiring Location, but it isn't nice to lock the user into a looping system screen. I think better would be: 1) show only the explanatory message on the app screen, or 2) exit app if location is not enabled.

4. [Feature suggestion] Option to display full form of "API capabilities" instead of the short form introduced in v3.0.2.

Thanks sirs

**Comment by VREMSoftwareDevelopment** [comment]
@Rikk
- Please use provided feature request/bug report templates.
- Please use one template per feature request/bug report.
- Do not forget to fill all required information in the templates.
- The information provided in the templates helps to resolve issues faster.

**Comment by Rikk** [comment]
Won't happen. If you don't care to read, I won't care to waste time making huge reports for small things.

**Comment by VREMSoftwareDevelopment** [comment]
Very interesting, you are not wiling to spend 5 minute per feature request, but you want someone else to spend days/weeks to implement it. Probably, the feature requested is not important.

**Comment by Rikk** [comment]
Observation: some closed 'issues' on this repository are real problems or good suggestions that were simply disregarded by the developers.
