### ISSUE TITLE
Known/saved network(s) identification

### ISSUE THREAD

**Issue by TGWGitHub** [VREMSoftwareDevelopment/WiFiAnalyzer#330]
[How to report a bug](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Feedback)

**Describe the bug**
There used to be a visual cue to easily identify already-known-networks (saved networks), it was a "happy face" IIRC, and it was useful in certain cases, but it seems to be missing in the newer versions of WiFi Analyzer, any clues?

**Provide Device/Android OS information**
Samsung A500H running Android 6.0.1

WiFi Analyzer v3.0.3 (GitHub)

**Comment by VREMSoftwareDevelopment** [comment]
This functionality was deprecated in Android API level 29.
[Reference documentation](https://developer.android.com/reference/android/net/wifi/WifiManager.html#getConfiguredNetworks())
