### ISSUE TITLE
In order to scan nerby wifi network it needs gps on android 10

### ISSUE THREAD

**Issue by giuseppemilella** [VREMSoftwareDevelopment/WiFiAnalyzer#331]
Hi, I have an andoid 10 OS, and I'm searching for an apk to scan the nearby wi-fi network. The problem is that the app needs to activate the GPS, and unfortunatelly I can't have GPS actived on the device because it is a very important bound of the univiersity project that I'm doing right now.

Could you fix this minor bug?
Giuseppe

**Comment by VREMSoftwareDevelopment** [comment]
[FAQ section](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer#faq) Location Service Permission Requirements
