### ISSUE TITLE
explanation of wireless security

### ISSUE THREAD

**Issue by dzidek23** [VREMSoftwareDevelopment/WiFiAnalyzer#333]
When using your app we can see that certain wireless security is used by the AP. 
WPA2 RSN K V in the example below.

The only thing is that I couldn't find what the K and V stand for.

![Screenshot_20210104_105601_com vrem wifianalyzer](https://user-images.githubusercontent.com/70292029/105974455-d6776d80-6085-11eb-9488-175847b3759f.jpg)

App: 3.0.3 - 55G (10-29)
Android 10

**Comment by VREMSoftwareDevelopment** [comment]
The information is called Wi-Fi scanning capabilities and is provided by Access Point via Android API.
Please take a look at the Access Point (Ruckus Wireless) documentations/specifications to see what all the information means.

Also here are links that may explains [K] and [V]:

- [IEEE 802.11k-2008](https://en.wikipedia.org/wiki/IEEE_802.11k-2008)
- [IEEE 802.11v](https://en.wikipedia.org/wiki/IEEE_802.11vl)
