### ISSUE TITLE
Site Survey Blank

### ISSUE THREAD

**Issue by talkinggoat** [VREMSoftwareDevelopment/WiFiAnalyzer#335]
I have a ulefone Armor X5 on Android 10 kern 4.9.190 and I can't seem to get any of the scan features working, there is simply no data. I have tried disabling throttling, but that did not help. 

https://i.imgur.com/nG8CsHa.png
https://i.imgur.com/wQvouEI.png

**Comment by VREMSoftwareDevelopment** [comment]
Based on the images that you have provided, `**filters**` are enabled, please reset **`filters`** and provide Access Points list image.


Please use provided bug report templates, do not forget to fill all required information in the templates. The information provided in the templates helps to resolve issues faster.
