### ISSUE TITLE
Feature about choosing best wifi channel 

### ISSUE THREAD

**Issue by Edfgdz** [VREMSoftwareDevelopment/WiFiAnalyzer#337]
Hello developer I have some thoughts about choosing best wifi channel function in this app.

When I open wifi channel chart in this app, it shows me this one.

![Screenshot_2021-02-20-09-39-46-637_com vrem wifianalyzer](https://user-images.githubusercontent.com/26460124/108582108-0efc2580-736c-11eb-84fd-8240c9f98def.jpg)

And this is its channel recommendation page.

![Screenshot_2021-02-20-09-39-50-201_com vrem wifianalyzer](https://user-images.githubusercontent.com/26460124/108582118-1de2d800-736c-11eb-9bdd-43414b5bb9dc.jpg)

But I find this app in Google play store, and it shows me this wifi signal heat histogram chart. 

https://play.google.com/store/apps/details?id=com.helgekeck.wifitool&hl=en_US&gl=US&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dcom.helgekeck.wifitool&pcampaignid=APPU_1_030wYPXuK5ml5NoPuY67yA0 
https://play.google.com/store/apps/details?id=com.helgekeck.wifitool&hl=en_US&gl=US&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dcom.helgekeck.wifitool&pcampaignid=APPU_1_030wYPXuK5ml5NoPuY67yA0

![Screenshot_2021-02-20-09-45-55-869_com helgekeck wifitool](https://user-images.githubusercontent.com/26460124/108582173-67332780-736c-11eb-9653-1acd36d24b91.jpg)

In this chart I think wifi channel area is in lowest area in this heat histogram and when user choose best wifi channel area in this histogram I think maybe user need to consider about their router wifi channel width too. 

I don't know if second histogram is better to let user pick best wifi channel when It is compared to this app wifi channel choosing method.

**Comment by VREMSoftwareDevelopment** [comment]
It is not clear to us what exactly you are asking, and  we can not comment on the behavior of other applications. This application channel rating code is available for a anyone review.

You are welcome to create a pull request with the implementation of your idea, it would be great to add new contributors to this project.

**Please use provided templates to request features and do not forget to fill all questions/topics in the templates.**

**Comment by Edfgdz** [comment]
ok
