### ISSUE TITLE
WiFi Coverage map

### ISSUE THREAD

**Issue by nicopace** [VREMSoftwareDevelopment/WiFiAnalyzer#338]
It would be great for the app to be able to build a coverage map of a certain SSID.

This map could be indoors or outdoors.
It would start by selecting the network you want to make the coverage map of.
Once that is done, you could choose if it is an indoor or outdoor map.

If it is an outdoor map, it would sample the signal level of the selected network every certain time, and save together with the level the gps coordinates.
This info could be shown in a map, or exported in csv/kml.

If it is indoor, the user should be able to draw a map of the place that it is being sampled or import an existing image of the map.
Then, the user should be able to move to each sampling location and manually locate in the map where the sample is being taken.

**Comment by steelman** [comment]
@VREMSoftwareDevelopment, any reason why you don't want to implement this feature?
