### ISSUE TITLE
802.11ax 160mhz  channels graphed incorrectly?

### ISSUE THREAD

**Issue by Swap-File** [VREMSoftwareDevelopment/WiFiAnalyzer#339]
**Describe the bug**
802.11ax 160mhz wide channels do not appear to graph correctly.  Looks like the center channel is incorrect.

Phone: OnePlus 8 Pro

**Screenshots**
WiFiAnalyzer Screenshot (unexpected graph):
![image](https://user-images.githubusercontent.com/3854710/109647456-ebc93700-7b1e-11eb-91ee-4408ed45f060.png)
(Bar overhangs to the left of 36 and stops at channel 56, center at 42(?))

Netspot Screenshot (expected graph):
![image](https://user-images.githubusercontent.com/3854710/109647501-f84d8f80-7b1e-11eb-971d-b94e027b1d6a.png)
(Bar goes from 36 to 64, with a center at 50)

**Comment by VREMSoftwareDevelopment** [comment]
Currently we do not have hardware that support 802.11ax 160mhz to test the issue you are having.

Can you please provide us with additional information to help resolve the issue:
- Application About screenshot
- Access point (in question) detail information screenshot
- Android WiFi connection list screenshot with enabled WiFi verbose logging

[How to enable WiFi verbose logging](https://internet-access-guide.com/enable-wifi-verbose-logging)

Please make sure that you are running the latest version of the application

Thanks

**Comment by Swap-File** [comment]
About:
![image](https://user-images.githubusercontent.com/3854710/110210437-551ab400-7e57-11eb-8cc8-eba59e6c6e9e.png)

Router:  Asus RT-AX88U
![image](https://user-images.githubusercontent.com/3854710/110210421-403e2080-7e57-11eb-91d4-5791e06378e6.png)

Wifi Connection:
![image](https://user-images.githubusercontent.com/3854710/110210521-a0cd5d80-7e57-11eb-80af-3e5f2bf648a1.png)

**Comment by VREMSoftwareDevelopment** [comment]
A few more screenshots please:
- Access point (in question) detail information screenshot from application (WiFi analyzer access point list)
- Access point (in question) detail information screenshot from Android (WiFi connection list with enabled WiFi verbose logging)

Thanks

**Comment by Swap-File** [comment]
![image](https://user-images.githubusercontent.com/3854710/110211600-f5270c00-7e5c-11eb-92b3-f312c21a39b7.png)


![image](https://user-images.githubusercontent.com/3854710/110211663-40411f00-7e5d-11eb-8540-c9c25148a514.png)

**Comment by VREMSoftwareDevelopment** [comment]
Sorry I think there is a slight misunderstanding on the last screenshot.
Android provides the list of all available WiFi connections. 
It is the screenshot that you have provided previously, the part that has a list of all available WiFi connections in Android.
Please do not cover the Access Point in question, all the detailed information that is provided there is needed.

If you are worried about leaking any private information, please email screenshot.

**Comment by VREMSoftwareDevelopment** [comment]
@Swap-File 
Please provide missing information (there is no need to provide SSID or BSSID)

![wifi-list-missing-info](https://user-images.githubusercontent.com/6217364/110239466-fddb1900-7f14-11eb-880b-ecff0c8e014c.png)

**Comment by Swap-File** [comment]
The top connected access point is the 160mhz one, the rest are other networks, or my neighbors networks.

![image](https://user-images.githubusercontent.com/3854710/110240466-a1c2c580-7f11-11eb-8c71-8edf8413e608.png)

There is another page of nearby networks if you need to see them all.

**Comment by VREMSoftwareDevelopment** [comment]
The fix will be available in next release.
