### ISSUE TITLE
App won't load on Android 11 OneUI 3.0

### ISSUE THREAD

**Issue by tegutistgut** [VREMSoftwareDevelopment/WiFiAnalyzer#340]
[How to report a bug](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Feedback)

**Please search issues (open and closed) to see the issues has already been reported.**

**Describe the bug**
I start the app and it stays on this loading screen: https://ibb.co/84VPn1r

**To Reproduce**
Open the App on a Samsung phone running Android 11 (OneUI 3.0)

**Expected behavior**
The app should work normal

**Screenshots**
https://ibb.co/84VPn1r

**Note**
WiFi Analyzer: Version 3.0.3 55G (11-30)

**Additional context**
The app worked fine under android 10 (oneui 2.5)

**Provide Device/Android OS information**
Samsung Galaxy A51, Android 11, OneUI 3.0, no root, the app was granted access to my location, developer settings are off, i cleared all data from the app to test it again

**Comment by VREMSoftwareDevelopment** [comment]
@tegutistgut  the problem is related to Android 9+ Wi-Fi scan throttling.
Please take a look at [FAQ](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer#faq), specifically Android Pie throttling Wi-Fi scanning section

Duplicate #278, #269, #242, #231
