### ISSUE TITLE
Support for Wi-Fi 6E in 6 GHz band

### ISSUE THREAD

**Issue by timg11** [VREMSoftwareDevelopment/WiFiAnalyzer#341]
The current version (3.0.3-55G) is able to display an SSID in the 6 GHz band, but the channel graphs do not include that band.

**Describe the solution you'd like**
Add additional pages of Channel Graphs to support 6 GHz band.
Note that the channel numbering in 6 GHz is non-unique compared to 2.4 and 5 GHz bands.  6 GHz channels start over with channel 1 and go up to 233. 

**How I can help**
I have a Samsung S21 with 6E support if beta testers are needed.

**Provide Device/Android OS information**
Samsung S21 Ultra G998U1    Android 11   OneUI 3.1

**Comment by VREMSoftwareDevelopment** [comment]
Please provide WiFi 6E specifications (documentation or links)

**Comment by rbrouwer** [comment]
I believe [this link](https://www.litepoint.com/blog/wi-fi-6e-standard-and-channels/) would be helpful here. That article contains a graph with all channels in 6E.

**Comment by VREMSoftwareDevelopment** [comment]
@rbrouwer @timg11 

The code is updated with [Alpha Wi-Fi 6e support](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/compare/feature) and available for testing.

**Comment by olekstomek** [comment]
This feature is available on version 3.0.6 (I updated beta version app from Google Play).

**Comment by VREMSoftwareDevelopment** [comment]
Will be available in next release (Version 3.0.6)
