### ISSUE TITLE
SIM Card signal strength

### ISSUE THREAD

**Issue by anishmittal2020** [VREMSoftwareDevelopment/WiFiAnalyzer#342]
It will be nice if we could get SIM Card Signal Strength depending on 4G, 3G, 2G, along with the signal rating such as given in [ASU value - measure and interpret signal strength](https://www.lte-anbieter.info/technik/asu.php)

Android OS: Android 10

**Comment by VREMSoftwareDevelopment** [comment]
Request is not core WiFi Analyzer functionality.
