### ISSUE TITLE
Beep for signal strength

### ISSUE THREAD

**Issue by innovation-plantation** [VREMSoftwareDevelopment/WifiAnalyzer#346]
To help test antennas with some sort of audible feedback, it would be really helpful if the app could make some "beep" or tone indicating the signal strength from the antenna being tried. It's a hassle trying to connect or adjust an antenna or device, then go check the signal farther away to get a reading and come back to the device and adjust again. So if it could beep you could listen while making adjustments.

Even better would be to communicate with several nearby phones that report the signal strength at each of their locations and let you know the strength of each of them - maybe how loud or frequent the beep is would indicate signal strength, and the tone would indicate which remote phone, then a musical chord (multiple tones added together) might beep indicating the overall signal strength detected by the combined listeners. But that's probably too much to ask.

I'm using an Android device, most often PixelXL or uleFone.

**Comment by VREMSoftwareDevelopment** [comment]
Please use provided feature report template, do not forget to fill all required information in the template. The information provided in the template helps to resolve issues faster.

All current contributors are busy with other work. When we don't have an opportunity or time to implement a feature, we encourage developers to fork the project and become a contributor. It would be great to add new contributors to this project.

Duplicate #93

**Comment by Valdnet** [comment]
As much as possible, a function should be implemented that would have:

1. Analog meter showing the level of the selected signal.
2. A beep sound (the stronger the signal, the higher the beep frequency).
3. Enable and disable the beep sound by the user.

The function can be useful for tracing the propagation of the Wi-Fi signal and setting the directionality of the Wi-Fi antenna.

I think that the application would be more attractive and increase the number of users.

**Comment by JamesRayn** [comment]
As I remember, this was a useful function at an older, no more functional wifi analyzer app (https://play.google.com/store/apps/details?id=com.farproc.wifi.analyzer)
