### ISSUE TITLE
Pressing Port Authority menu item opens play store instead of app

### ISSUE THREAD

**Issue by bendev25689** [VREMSoftwareDevelopment/WiFiAnalyzer#349]
Upon pressing the PortAuthority button in the app, it will open the play store even if port authority is already installed.

1. Ensure Port Authority is installed
2. Open the menu from top left of Wifi Analyser
3. Press PortAuthority
4. Play store opens

**Expected behavior**
If PortAuthority is already installed, the button should open the PortAuthority app instead of the play store.

Device:
Samsung Galaxy A70
Android 11

**Comment by VREMSoftwareDevelopment** [comment]
We have tested the issue reported and we are not able to reproduce this on any of the devices available to us.

**Comment by bendev25689** [comment]
I have allowed all permissions, and I am running the latest version of both apps (wifi analyzer 3.0.4 and port authority 2.4.1).
Is there a log file which would be useful?

**Comment by VREMSoftwareDevelopment** [comment]
The issue that you are seeing maybe related to new Android 11 feature: [Package visibility filtering on Android](https://developer.android.com/training/package-visibility)

**Comment by bendev25689** [comment]
yep, looks like that is the issue,
adding <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/> to AndroidManifest.xml fixes the issue

**Comment by VREMSoftwareDevelopment** [comment]
the fix will be available in the next release
