### ISSUE TITLE
Channel rating should not be affected by channel used by yourself 

### ISSUE THREAD

**Issue by cdysthe** [VREMSoftwareDevelopment/WiFiAnalyzer#350]
The channel rating isn't really useful as long as the channel you are using yourself affects the result. Let's say channel 11 is recommended for me and I set that channel next time I check channel 11 will not be recommended but that's because I am now using it. 

In ares with a lot of networks this is not a big problem but if there are fewer networks you will almost always be recommended another channel because the one you are on are occupied by yourself.

**Comment by VREMSoftwareDevelopment** [comment]
Please use provided bug/feature report templates, do not forget to fill all required information in the templates. The information provided in the templates helps to resolve issues faster.

The channel rating algorithm is working as expected. 

The algorithm uses different criteria to rate, such as:
- The number of the access points on the same channel
- Currently connected channel
- etc

You are welcome to review the algorithm.
