### ISSUE TITLE
Exports results directly to a file

### ISSUE THREAD

**Issue by skinkie** [VREMSoftwareDevelopment/WiFiAnalyzer#354]
**Please search issues (open and closed) to see the issues has already been reported.**

#353 

**Is your feature request related to a problem? Please describe.**

In order to use the app in war driving / site survey context one would have te press "Export" manually, and each time select where.
 
**Describe the solution you'd like**

With GPS exports being available, it makes sense to not to have to press "export" of the current scan results, instead storing all the results presented. I can imagine an option to "enable logging" where the user is informed about the location by a toast.

**How I can help**

Continue with the #353 code.

**Comment by VREMSoftwareDevelopment** [comment]
It is not clear how this new feature benefits / enhances WiFi Analyzer core functionality.  This feature probably requires a brand new application that only does site survey.

Please add a clear and concise description on how this new feature enhances WiFi Analyzer core functionality.

**Comment by skinkie** [comment]
The core use of the application is not limited _temporally_. The user estimates how the network behaves while moving. It is clear that storing the results from a temporal perspective would allow to do a site survey to review the results at a later stage.

**Comment by frankier** [comment]
I agree that this could be useful. The idea is that the program would just be used to get data, and then it could be processed later.
