### ISSUE TITLE
Move text

### ISSUE THREAD

**Issue by aha999** [VREMSoftwareDevelopment/WiFiAnalyzer#355]
[How to report a bug](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Feedback)

**Please search issues (open and closed) to see the issues has already been reported.**

**Describe the bug**
The text Wifi channels is too close to the numbers .

**Expected behavior**
There should be a little more space above the text (circled in the screenshot)

**Screenshots**
![Screenshot_20210812-154353252_1.jpg](https://user-images.githubusercontent.com/50620416/129208683-389e8a2c-e535-475a-b706-135708f84d89.jpg)

**Provide Device/Android OS information**
Asus zenfone 6, android 11 stock

**Comment by VREMSoftwareDevelopment** [comment]
Application is using the [GraphView](https://github.com/jjoe64/GraphView) library to display Graphs and the information display is fully controlled by it.  This issue probably needs to be reported in that project.
