### ISSUE TITLE
Application Id Change

### ISSUE THREAD

**Issue by Nephys222** [VREMSoftwareDevelopment/WiFiAnalyzer#357]
When "application id" is changed, the Signal Strength level values changes abnormally. For example:
if changed from the original: "com.vrem.wifianalyzer" to "com.vrem.wifistations" signal values fluctuates with higher variance.

Device/Android OS

**Comment by VREMSoftwareDevelopment** [comment]
We have tested the application with changes that were recommended and we are not seeing the issue you are reporting.

Please use provided templates to report issues and do not forget to fill all questions/topics in the templates.
