### ISSUE TITLE
Test failure: com.vrem.wifianalyzer.wifi.band.WifiChannelCountryTest.testFindCorrectlyPopulatesCountryCodeAndName fails depending on the OS language

### ISSUE THREAD

**Issue by jswolf19** [VREMSoftwareDevelopment/WiFiAnalyzer#358]
I'm getting a failure on the test `testFindCorrectlyPopulatesCountryCodeAndName`, specifically the [assertion](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/blob/a0dde92089defc37ab0c4b29a1d742466ec54b73/app/src/test/kotlin/com/vrem/wifianalyzer/wifi/band/WiFiChannelCountryTest.kt#L91) that `expected.displayCountry` does not equal `actual.countryName(expected)`.

I'm not sure what is expected with this assertion (or why it is necessary to test), nor do I know why it does not behave as expected in my environment.

I'm running Windows 10 20H2 19042.1266, android studio 2020.3.1 Patch 2, adoptopenjdk 11.0.12.7-hotspot

**Comment by jswolf19** [comment]
It seems that my OS language being Japanese is also relevant. When I switch it to English, the test passes.

**Comment by jswolf19** [comment]
I can see three options.

1. Leave it as is. While not what I would prefer (as I'm affected by this), it would seem that either current contributors are not affected, or they don't consider it an issue.
2. Remove the assertion. Only a guess, but it's likely just there to show that the country name is in the locale provided and not the display locale.
3. Change the expected value to `expected.getDisplayCountry(Locale.ENGLISH)`.
4. Use `Locale.setDefault(Locale.ENGLISH)` to enforce that the display locale is not dependent on the environment. If tests are done in parallel, this could cause trouble elsewhere as this is changing global state.

**Comment by VREMSoftwareDevelopment** [comment]
Fixed
