### ISSUE TITLE
Scrollable View changes position on Device Rotation

### ISSUE THREAD

**Issue by reverse-unina** [VREMSoftwareDevelopment/WiFiAnalyzer#36]
When I perform this sequence of events, the scroll view on screen goes back to the top:
1. Open Side Drawer
2. Click on About
3. Scroll Down
4. Orientation Change

**Comment by VREMSoftwareDevelopment** [comment]
- Android creates a new view when switching orientation. It is intended. 
- It is on the **About Screen** of the Application - Low Priority
- It would be great if you provide a pull request to fix it.

Btw, thanks for reporting :+1:
