### ISSUE TITLE
applicationId change

### ISSUE THREAD

**Issue by Nephys222** [VREMSoftwareDevelopment/WiFiAnalyzer#360]
**Describe the bug**
In order to use WiFiAnalyzer in another open-source project, we forked and built on Android Studio. When we change "applicationId" on module level gradle file or in 'Project Structure' from 'com.vrem.wifianalyzer' to any different name such as: 'com.vrem.wifisignal', the scanned wi-fi values fluctuate rapidly and regress to **-100dBm**. It could be seen in all tabs such as: 'Access Points', 'Channel graph' etc.

**To Reproduce**
1. Go to 'Fork the project and built on Android Studio'
2. Click on 'applicationId' on module level gradle file and change "com.vrem.wifianalyzer" to "com.vrem.wifisignal"
3. Click on 'built the app and install on any device'
4. Scroll down to 'Access Points or Channel Graph'

**Expected behavior**
It is expected to show wi-fi signals as in its first built.

**Note**
Device/Android OS and WiFi Analyzer version (Menu -> About)

**Comment by eakteam** [comment]
@Nephys222 How did you solve that issue?

**Comment by eakteam** [comment]
@VREMSoftwareDevelopment any idea why this is happening please?

**Comment by eakteam** [comment]
@Nephys222 Why you close that issue? It is still happening and no solution to it?!
