### ISSUE TITLE
Mesh with 3 satellites appears as 3 APs.

### ISSUE THREAD

**Issue by OneOfMany07** [VREMSoftwareDevelopment/WiFiAnalyzer#361]
**Describe the bug**
Was looking at my local channel usage and realized my 3 Netgear MR60s (mesh router kit) are appearing like 3 separate networks (APs).  Makes the channel usage graph look worse than it truly is (or maybe I don't understand all the details there...seems like 3 separate coordinated sources could overlap usage without issue and have the same interference potential as 1 high power AP).

**To Reproduce**
Scan when have all 3 devices included with Negear MR60 kit are enabled/live.
Will see 3 devices using whatever channels they're set to (one setting for 2.4, and one for 5GHz appear on my device...router is wifi6 capable though, I believe, and phone isn't).

**Expected behavior**
I can't set each of the 3 devices to separate channels, so I'd assume these should appear like 1 AP in your app.

**Provide Device/Android OS information**
Samsung A71
One UI version 3.1
Android 11
Kernel version 4.19.125-22171684
Build number RP1A.200720.012.A717VSQU4DUG3

WiFiAnalyzer 3.0.5 - 57G (11-30)

**Comment by VREMSoftwareDevelopment** [comment]
Works as expected

A few helpful articles:
- [Guidelines for mesh networks](https://commotionwireless.net/docs/cck/networking/guidelines-for-mesh/)
- [Is your mesh meshing with you](https://www.plume.com/homepass/blog/is-your-mesh-meshing-with-you)
