### ISSUE TITLE
i18n: Change attribute of text strings

### ISSUE THREAD

**Issue by Valdnet** [VREMSoftwareDevelopment/WiFiAnalyzer#363]
I believe that the following text strings should also be translated into other languages:

https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/blob/de97d5be7e126c4e0dc4e32b75855cc91aefd5b7/app/src/main/res/values/strings.xml#L170
https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/blob/de97d5be7e126c4e0dc4e32b75855cc91aefd5b7/app/src/main/res/values/strings.xml#L172
https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/blob/de97d5be7e126c4e0dc4e32b75855cc91aefd5b7/app/src/main/res/values/strings.xml#L174
https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/blob/de97d5be7e126c4e0dc4e32b75855cc91aefd5b7/app/src/main/res/values/strings.xml#L176
https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/blob/de97d5be7e126c4e0dc4e32b75855cc91aefd5b7/app/src/main/res/values/strings.xml#L178

You should remove the `translatable="false"` attribute so that translators know that the text string should also be translated.

**Comment by VREMSoftwareDevelopment** [comment]
This is not considered an urgent or required translations.
Please create a PR with translation for all supported languages.
It would be great to add new contributors to this project.
