### ISSUE TITLE
static scan results on android 12

### ISSUE THREAD

**Issue by bughit** [VREMSoftwareDevelopment/WiFiAnalyzer#364]
**Describe the bug**
- the scan results don't change
- the time graph is a straight flat line
- scan throttling is off
- worked on android 11
- other scan apps are working (https://play.google.com/store/apps/details?id=abdelrahman.wifianalyzerpro)
- wifi analyzer 3.0.5
- stock android 12 2021-12 SQ1A.211205.008

**To Reproduce**
1. set scan interval to 1 or 3 secs
2. open the time graph

**Expected behavior**
When working, the signal strength fluctuates with every scan

**Comment by VREMSoftwareDevelopment** [comment]
Please provide the following screenshots Device/Android OS (Settings → About Phone) and WiFi Analyzer version (Menu -> About)

**Comment by bughit** [comment]
Sure, let me get my SSN too. What specifically are you asking for? I already posted versions.

**Comment by VREMSoftwareDevelopment** [comment]
We are not able to reproduce the problem that you are seeing, using devices available to us.
