### ISSUE TITLE
Ability to check how long time the found devices work - Beacon frame

### ISSUE THREAD

**Issue by olekstomek** [VREMSoftwareDevelopment/WiFiAnalyzer#365]
In the Beacon frame that is sent by devices via WiFi, information is sent how long time the device works. The field is 8 bytes long and the value shown is expressed in microseconds.
![image](https://user-images.githubusercontent.com/26818304/147497400-2b74567b-d39b-47a5-8178-2967482d1aec.png)
This can be useful additional information about found WiFi networks in application.
More details you can read [here](https://mrncciew.com/2014/10/08/802-11-mgmt-beacon-frame/).

Note that some devices (e.g. managed by ISP operators) may have their timestamp always set to 0, so then you should also handle this case.

**Comment by VREMSoftwareDevelopment** [comment]
Please use provided feature report template, do not forget to fill all required information in the template. The information provided in the template helps to resolve issues faster.

All current contributors are busy with other work. When we don't have an opportunity or time to implement a feature, we encourage developers to fork the project and become a contributor. It would be great to add new contributors to this project.

**Comment by olekstomek** [comment]
> Please use provided feature report template, do not forget to fill all required information in the template. The information provided in the template helps to resolve issues faster.

OK, it's done below.

**Please search issues (open and closed) to see the issues has already been reported.**
My feature is new in issues.

**Is your feature request related to a problem? Please describe.**
Not applicable.

**Describe the solution you'd like**
Ability to check how long time the found devices work. In the Beacon frame that is sent by devices via WiFi, information is sent how long time the device works. The field is 8 bytes long and the value shown is expressed in microseconds. This can be useful additional information about found WiFi networks in application.
More details you can read [here](https://mrncciew.com/2014/10/08/802-11-mgmt-beacon-frame/).
Note that some devices (e.g. managed by ISP operators) may have their timestamp always set to 0, so then you should also handle this case.

**Describe alternatives you've considered**
Not applicable.

**How I can help**
I can answer additional questions and ambiguities.

**Additional context**
![image](https://user-images.githubusercontent.com/26818304/147497400-2b74567b-d39b-47a5-8178-2967482d1aec.png)

**Provide Device/Android OS information**
This is a new idea so the specific version of Android does not matter.

**Comment by VREMSoftwareDevelopment** [comment]
will be available in the next release
