### ISSUE TITLE
PortAuthority not found

### ISSUE THREAD

**Issue by kri164** [VREMSoftwareDevelopment/WiFiAnalyzer#368]
When click on Menu -> PortAuthority get error unable to find app, even the PortAuthority is installed from F-Droid.

**Comment by VREMSoftwareDevelopment** [comment]
Please use provided issue report template, do not forget to fill all required information in the template. The information provided in the template helps to resolve issues faster.

[How to report a bug](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Feedback)

**Comment by kri164** [comment]
**Describe the bug**
When click on Menu -> PortAuthority I get error "No such app found"

**To Reproduce**
Steps to reproduce the behavior:
1. Click on click Menu -> PortAuthority
3. See error "No such app found"

**Expected behavior**
App Port Authority will launch.

**Additional context**
App Port Authority (com.aaronjwood.portauthority) ver 2.4.1 is installed from F-Droid app store.
App WifiAnalyzer (com.vrem.wifianalyzer) ver 3.0.6 is installed fron F-Droid app store.

**Provide Device/Android OS information**
Redmi Note 9 Pro
Android 11
LineageOS 18.1

**Comment by VREMSoftwareDevelopment** [comment]
will be available in the next release
