### ISSUE TITLE
Please add d0:59:19, 44:fb:5a and 98:00:6a`s vendor info

### ISSUE THREAD

**Issue by Gurbuzguven** [VREMSoftwareDevelopment/WiFiAnalyzer#369]
[How to report a bug](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Feedback)

**Please search issues (open and closed) to see the issues has already been reported.**

**Describe the bug**

Please add d0:59:19, 44:fb:5a and 98:00:6a vendor info as ZTE CORPORATION, thank you!

**To Reproduce**
1.Go to vendors tab
2.Search for d0:59:19, 44:fb:5a and 98:00:6a

**Expected behavior**

See ZTE CORPORATION as their vendor info

**Screenshots**

Not needed.

**Note**
Some behaviour only occurs on certain devices or versions of Android, please provide the following screenshots/information Device/Android OS (Settings → About Phone) and WiFi Analyzer version (Menu -> About)

**Additional context**

**Provide Device/Android OS information**

Wifi Analyzer version 1.9.3

**Comment by VREMSoftwareDevelopment** [comment]
Version 1.9.3 was released on Aug, 2018. It is an old version and is not maintain anymore.

The current version is 3.0.6 and was  released on Jan, 2022.

Please update to the latest version before reporting any issues or requesting any new features.

**Comment by Gurbuzguven** [comment]
Sorry, I have downloaded it through Google`s Play Store and haven`t noticed it was an old version. Latest version have them all and thanks for amazing support! I will donate some money when i got my paycheck!
