### ISSUE TITLE
Only displays Preferred Scanning Channels (PSC) in 6 GHz Band

### ISSUE THREAD

**Issue by timg11** [VREMSoftwareDevelopment/WiFiAnalyzer#378]
In the 6 GHz band, PSC's are defined as one of every 4 channels (one per 80 MHz), to speed up scanning.  Ch 37, 53, 69, 85, etc. 
Operation on any channel is allowed though. 
If the AP is operating on a non-PSC channel, WiFiAnalyzer does not see it. Even if the phone is connected to that non-PSC channel. 

Testing with WiFiAnalyzer 3.0.6-58G (12-31)

**To Reproduce**
1) Set Wi-Fi 6E Access Point to Channel 73   (a non-PSC channel)
2) Open WiFiAnalyzer channel graph, set to 6 GHz band, and ch 65-93 range.
3) Wait for something to display on the graph.
4) Connect the phone to the AP operating on channel 73.
5) Observe that WiFiAnalyzer still does not display the SSID even while phone is connected to AP on Ch 73.
6) Set Wi-Fi 6E Access Point to Channel 85 (a PSC channel)
7) Observe that WiFiAnalyzer immediately displays the SSID

**Expected behavior**
WiFiAnalyzer should display SSIDs on any valid 6 GHz channel. 

**Provide Device/Android OS information**
Tested on Samsung Galaxy S21 Ultra 5G, SM-998U1 with Android 12, OneUI 4.1, Baseband G998U1UEU5CVDC

**Comment by VREMSoftwareDevelopment** [comment]
Application displays information provided by Android API.
Application does not change the information provided by Android API.
The issue probably is hardware. (AP or phone)

![WiFiChannle73](https://user-images.githubusercontent.com/6217364/171688360-2c2a8327-1cce-417d-a875-9ef843b3bedd.JPG)
