### ISSUE TITLE
Xiaomi Poco F3 no showing as WiFi 6 enabled in "About" submenu

### ISSUE THREAD

**Issue by vatonbero** [VREMSoftwareDevelopment/WiFiAnalyzer#379]
**Describe the bug**
Xiaomi Poco F3 device not showing as WiFi 6 enabled so user cannot be sure if WiFi 6 scanning is working or not.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'hamburger menu'
2. Click on 'About'
3. Scroll down to 'Device info'

**Expected behavior**
This is Snapdragon 870 powered phone so it has support for Wifi 6. First, there should be a green tick next to phone model in "About". If i need to provide you with any data to whitelist device, please do tell.

Second, maybe more important, do not expose 6GHz data in "Channel graph" on non-supported devices. So hide all Wifi 6 related stuff if device is not supporting that tech. It is simple: now i cannot conclude if my device is not supported by the program or it is but there are no WiFi 6 networks around me.

I have another Android 11 device which has snapdragon 730 and I can open WiFi 6 related stuff even tho that chipset is not supporting that technology.

**Provide Device/Android OS information**
Android 12, Miui 13.0.6.0
WiFiAnalyzer `3.0.6 - 58S` (11-30) from F-Droid

**Comment by VREMSoftwareDevelopment** [comment]
Snapdragon 870 does not support Wi-Fi 6E (6 GHz), it support only Wi-Fi 6 (802.11ax) on 5 GHz

https://www.qualcomm.com/products/application/smartphones/snapdragon-8-series-mobile-platforms/snapdragon-870-5g-mobile-platform

```
Wi-Fi/Bluetooth System: Qualcomm® FastConnect™ 6800
Peak Speed: 1.774 Gbps
Standards: Wi-Fi 6 (802.11ax), Wi-Fi 5, 802.11a/b/g/n
Wi-Fi Spectral Bands: 2.4 GHz, 5 GHz
Peak QAM: 1024 QAM
Wi-Fi Features: OFDMA (Uplink and Downlink), WPA3 security support, Dual-band simultaneous (DBS), 8x8 sounding, 1024 QAM
```
