### ISSUE TITLE
white theme does not run

### ISSUE THREAD

**Issue by emingote** [VREMSoftwareDevelopment/WiFiAnalyzer#380]
**Describe the bug**
white theme does not run since the last app update to 3.0.7 version

**To Reproduce**
1. Go to Configuration
2.  Click on Theme
3. Select White option

**Expected behavior**
Theme should change to white but it remains dark

**Provide Device/Android OS information**
Samsung Tab S7 / Android 12

**

**Comment by VREMSoftwareDevelopment** [comment]
will be available in the next release
