### ISSUE TITLE
V3.0.9-F-DROID missing in Store

### ISSUE THREAD

**Issue by derflasher** [VREMSoftwareDevelopment/WiFiAnalyzer#382]
[How to report a bug](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Feedback)

**Please search issues (open and closed) to see the issues has already been reported.**

**Describe the bug**
You published v3.0.9 on June 29. Since then, I expect to download the latest release on f-droid. Unfortunetly WiFiAnalyzer is on the "no update check"-list (https://monitor.f-droid.org/builds/noupdatecheck)

**To Reproduce**
1. Go to https://f-droid.org/de/packages/com.vrem.wifianalyzer/ and check version (3.0.7)
2. Go to https://monitor.f-droid.org/builds/noupdatecheck and check if WiFiAnalyzer is on the list

**Expected behavior**
Latest downloadable version on f-droid is 3.0.9.

May you put WiFiAnalyzer back on the auto-build list?

**Comment by VREMSoftwareDevelopment** [comment]
Done
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11495

**Comment by derflasher** [comment]
Thank you so much!
I downloaded the latest version on f-droid, moments ago.
