### ISSUE TITLE
Android 10 Wi-fi scans sometimes don't change

### ISSUE THREAD

**Issue by qxqxq** [VREMSoftwareDevelopment/WiFiAnalyzer#387]
**Describe the bug**
I'm constantly walking around, and the wifi scans often stay the same for seconds.

**Expected behavior**
I'm constantly walking around, and the wifi scan changes every second.

**Screenshots**
![51664334178_ pic](https://user-images.githubusercontent.com/44389330/192678516-067259b9-cd77-4585-b294-1e3cb1094786.jpg)
![71664334916_ pic](https://user-images.githubusercontent.com/44389330/192679508-2f55ffb3-2fe8-4278-a4a5-d782d5c2a190.jpg)

**Note**
Some behaviour only occurs on certain devices or versions of Android, please provide the following screenshots/information Device/Android OS (Settings → About Phone) and WiFi Analyzer version (Menu -> About)

![41664334109_ pic](https://user-images.githubusercontent.com/44389330/192678414-7a97433b-5c79-44c9-9e0d-412442c933ec.jpg)

**Provide Device/Android OS information**
Redmi 9A 
Android 10
MIUI 12.0.16

**Comment by qxqxq** [comment]
I want the wifi scan to change every second, is that technically possible?

**Comment by VREMSoftwareDevelopment** [comment]
Application will request the WiFi Scan information from Android OS using the APIs as per scan frequency specified in application settings.

Here are possible issues:
- Android OS API will not response per requested scan frequency 
- Device hardware will not response per scan frequency specified
- Access Point software will not response per scan frequency specified
- Access Point hardware will not response per scan frequency specified

The software and hardware that we use to test does not have the issue you are describing.

**Comment by k79e** [comment]
On my system scan period setting only work when I plug in the charge cable.
Is this normal?

**Comment by k79e** [comment]
Mine is not android 10 but old v8
I find 1s only work when I charge from usb port(pc)
If I charge from the charger it won't work.

**Comment by k79e** [comment]
I noticed the system's wifi signal level changed but this app don't. Is this normal!???
