### ISSUE TITLE
v3.0.9 on LineageOS 18.1 shows only one AP

### ISSUE THREAD

**Issue by Geremia** [VREMSoftwareDevelopment/WiFiAnalyzer#388]
WifiAnalyzer version 3.0.9 shows only one access point, the one I'm connected to. I never had this problem in the past.

**Comment by VREMSoftwareDevelopment** [comment]
Please use provided bug/feature report template, do not forget to fill all required information in the template. The information provided in the template helps to resolve issues faster.

Have you tried the following:
- [FAQ](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer#faq)
  - [Android Wi-Fi scanning throttling](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Android-WiFi-scanning-throttling)
  - [Location Service Permission Requirements](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Location-Service-Permission-Requirements)
 - Install Version [3.0.6](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/releases/tag/V3.0.6-F-DROID) or [3.0.7](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/releases/tag/V3.0.7-F-DROID) and see if it works

**Comment by Geremia** [comment]
@VREMSoftwareDevelopment  3.0.7 works for me, but not 3.0.9.

**Comment by VREMSoftwareDevelopment** [comment]
Very strange

Here are difference between both versions

https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/compare/V3.0.7-F-DROID...V3.0.9-F-DROID

As you can see there are no major changes

**Comment by Geremia** [comment]
@VREMSoftwareDevelopment It's not [this diff](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/compare/V3.0.7-F-DROID...V3.0.9-F-DROID#diff-b9a7570bc6a0342d18de9026012e721d2f0342b5ac768922a677627405f36215)?

**Comment by VREMSoftwareDevelopment** [comment]
This is a test code:  `VendorServiceTest.kt`

**Comment by Geremia** [comment]
@VREMSoftwareDevelopment I updated to 3.0.9 after having downgraded to 3.0.7 and now it works. Strange.
