### ISSUE TITLE
The WiFi network time shown in the app is incorrect

### ISSUE THREAD

**Issue by olekstomek** [VREMSoftwareDevelopment/WiFiAnalyzer#391]
A feature https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/issues/365 has been added to the app. This shows how long the WiFi network has been operating for. However, the time is not correct. Here are the screenshots from the application:
![1665701596658](https://user-images.githubusercontent.com/26818304/195727184-1bedef81-bfc9-4635-b8d3-ac810c5fc733.jpg)
![1665701596663](https://user-images.githubusercontent.com/26818304/195727188-3459df96-787b-42ab-890d-80e9a9ec0238.jpg)
![1665701596671](https://user-images.githubusercontent.com/26818304/195727192-6b2efa67-a646-4988-b18f-0db49cc4a833.jpg)
![1665701596678](https://user-images.githubusercontent.com/26818304/195727195-a0b3868f-983b-4d12-a5e3-5ce1adedd267.jpg)

In the screenshots you can see the networks:
_HUAWEI P10 lite_ (this network has only been working for a minute, why is the value `0:11:00:980`?)
_GigaLan_siecdomowa_14_EXT_ (not my network) and the _OpenWrt_ networks have almost the same value: `0:07:19.XXX` (this is impossible - my _OpenWrt_ network has a different uptime and it will be below)
_LEDE MiFi_ - has a value of `0:07:24.437`, this network was launched for testing, it was launched a short time ago.

Uptime for _OpenWrt_ network:
![1665701596654](https://user-images.githubusercontent.com/26818304/195728502-bf75be38-bb50-402a-a2be-a481d982683b.jpg)
You can see that the network is operational 6 days 22 hours 55 minutes. Where does the `0:07:19:998` value in the app come from?

I am enclosing what times can be seen from the router (which broadcasts _LEDE MiFi_ network) panel (GUI [MiFi ](https://eko.one.pl/?p=mifi) based on [OpenWRT](https://github.com/openwrt/openwrt)) which also has the option of displaying the operating time of a given WiFi network. The times are correct:
![1665701596684](https://user-images.githubusercontent.com/26818304/195728836-dccf52fa-75b1-4a4f-991a-7a06a13ac882.jpg)
You can see difference. Correct uptime for my networks _HUAWEI P10 lite_ is one minute, _OpenWrt_ is 6 days 22 hours and some minutes. 

Smartphone: Xiaomi Mi 9, Android 11
App version: 3.0.10 - 62G (11-30)

**Comment by VREMSoftwareDevelopment** [comment]
Timestamp is provided by Android API

Documentation Reference:
 https://developer.android.com/reference/android/net/wifi/ScanResult#timestamp

Application does not change the value, it only formats it

Code reference:
https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/blob/b662b1d16b878b96fec5319960a1d1e980fb2685/app/src/main/kotlin/com/vrem/wifianalyzer/wifi/accesspoint/AccessPointDetail.kt#L165

**Comment by olekstomek** [comment]
Okay, the network uptime is set differently for the solution in the router with OpenWrt (Beacon frame) and differently in the WiFiAnalyzer application (API from Android).

I think this might be a related problem: https://issuetracker.google.com/issues/37123392
