### ISSUE TITLE
Better format for representing the uptime of the WiFi network

### ISSUE THREAD

**Issue by olekstomek** [VREMSoftwareDevelopment/WiFiAnalyzer#392]
Reference to https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/issues/365
Maybe it's better to go without insignificant milliseconds and seconds and show the duration of the selected WiFi network in days, hours, and minutes.
In the case of a long WiFi network operation time, it will be difficult to understand how much 500h is, it is better to show it as 19 days 23h 20 minutes (more readable and more comfortable).

**Comment by VREMSoftwareDevelopment** [comment]
Removing scan results timestamp when this result was last seen, since the value is not stable.
Android API produces different results using different hardware.

Reference: https://issuetracker.google.com/issues/37123392
