### ISSUE TITLE
GitHub release v3.0.10

### ISSUE THREAD

**Issue by PeterKW** [VREMSoftwareDevelopment/WiFiAnalyzer#393]
https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/releases/tag/V3.0.9-F-DROID

I believe the version on GitHub is currently v3.0.10? Is there a link available to a github release for this version?

Thank you very much!
@VREMSoftwareDevelopment

**Comment by VREMSoftwareDevelopment** [comment]
Where is v3.0.10 in Github?
https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/commits/master
