### ISSUE TITLE
Feature Request: Add ability to add friendly names to access points

### ISSUE THREAD

**Issue by johnddx** [VREMSoftwareDevelopment/WiFiAnalyzer#396]
When any more than Few APs come into view, some of which may share AP names, it can be difficult to tell them apart, especially as different APs come and go.  The ability to assign friendly names to each unique entity would help immensely. 

The feature would include an edit option when opening an access point to look at its details.  The AP friendly name would be remembered by Mac address and major band.

It might actually be useful enough to just have friendly labels for Mac addresses and ignore the wireless frequency.  This would suggest adding subscripts to different APs with the same Mac address.   The core problem could be summarized as lack of recognizability of Mac addresses.

Having the ability to assign a label to an arbitrary combination of AP traits would be very nice, but would also be more complex.

**Comment by VREMSoftwareDevelopment** [comment]
Duplicate #116, #149, #274, #303, #351

**Comment by cweiske** [comment]
There once was a patch for this: https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/pull/359
