### ISSUE TITLE
Broken by Android update

### ISSUE THREAD

**Issue by kurahaupo** [VREMSoftwareDevelopment/WiFiAnalyzer#402]
I tried to use the app today to find the best position to set up a client device in a room with marginal wifi coverage, and discovered that the app no longer shows any AP except the one that I'm currently signed into (or none at all), and the AP timeline is completely empty.

Given that it's been completely reliable in the past I can only assume that there's something in a recent Android update that blocks it from functioning correctly.

This is on an Oppo Reno 2z (CPH1951 hw rev 11) running ColorOS 11.1 (rebranded Android 11.1)

I've checked and it has location permission and wifi internet access enabled; what else does it need?

_edit: if the answer to the question above does not resolve the problem, then of course there will need to be a longer dialogue, and perhaps I will need to submit a patch._

**Comment by VREMSoftwareDevelopment** [comment]
[FAQ](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer#faq)

- [Android Wi-Fi scanning throttling](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Android-WiFi-scanning-throttling)
- [Location Service Permission Requirements](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Location-Service-Permission-Requirements)

**Comment by kurahaupo** [comment]
Yes scan throttling is disabled.

**Comment by kurahaupo** [comment]
On the same device I can run the ["farproc" Wifi Analyzer](https://play.google.com/store/apps/details?id=com.farproc.wifi.analyzer) app, and it doesn't have any problems showing all the access points. Only this ["vrem" Wifi Analyzer](https://play.google.com/store/apps/details?id=com.vrem.wifianalyzer) app fails.

As I mentioned before, I've granted all permissions that have been asked for, and disabled wifi scan throttling, so it would appear that ColorOS 11.0 or  11.1 has added some new permission factor that has to be requested by the manifest to make this app work.

I really want to support open source projects so if there's anything I can do to help, please let me know.

**Comment by kurahaupo** [comment]
reopen

**Comment by kurahaupo** [comment]
I've also tried uninstalling and re-installing, just to make sure. Still no go.

**Comment by VREMSoftwareDevelopment** [comment]
Please provide WiFi Analyzer version

**Comment by VREMSoftwareDevelopment** [comment]
[Changes between 3.0.9 and 3.0.11](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/compare/V3.0.9-F-DROID...V3.0.11-F-DROID)

**Comment by kurahaupo** [comment]
3.0.11

**Comment by VREMSoftwareDevelopment** [comment]
The only suggestion we can provide is to try an older version of WiFi Analyzer.

Older versions are available [here](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/releases) or [F-Droid](https://f-droid.org/en/packages/com.vrem.wifianalyzer/)

It does look like an issue with phone OS.

Please note that `"farproc" Wifi Analyzer app` was not updated since 2018.

**Comment by kurahaupo** [comment]
Ok, I downloaded the 3.0.9 APK and it displays all the Access Points without any problem, so I'll keep looking through the diffs between 3.0.9 and 3.0.11 and let you know if I find anything.

**Comment by kurahaupo** [comment]
@VREMSoftwareDevelopment I think I've found the culprit: https://developer.android.com/guide/topics/connectivity/wifi-permissions

Under Android 10 or older, or under SDK version 32 or older, the [`ACCESS_FINE_LOCATION`](https://developer.android.com/reference/android/Manifest.permission#ACCESS_FINE_LOCATION) is interpreted as including access to the list of nearby WiFi access point names.

SDK version 33 adds the new [`NEARBY_WIFI_DEVICES`](https://developer.android.com/reference/android/Manifest.permission#NEARBY_WIFI_DEVICES) permission, and Android 11 then enforces the requirement for that permission when under SDK version 33.

(I don't know for certain that the enforcement changed between Android 10 and Android 11, but it seems likely since that's when it failed for me.)

**Comment by VREMSoftwareDevelopment** [comment]
Will be available in the next release
