### ISSUE TITLE
Wrong signal (dBm) when trying to compile custom app

### ISSUE THREAD

**Issue by eakteam** [VREMSoftwareDevelopment/WiFiAnalyzer#408]
The app builds and execute correctly when trying to create custom apk but signal dBm shows wrong values when changing Application ID from `com.vrem.wifianalyzer` to `something else`
Any idea how to solve that?

**Comment by eakteam** [comment]
Same issue is happening at:  https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/issues/360

**Comment by VREMSoftwareDevelopment** [comment]
Duplicate
