### ISSUE TITLE
Paid for version with tracking and anti-features - possible code stolen from your repo?

### ISSUE THREAD

**Issue by accessiblepixel** [VREMSoftwareDevelopment/WiFiAnalyzer#410]
I was looking for WiFiAnalyzer and kind of realised I'd been had by a version with usertracking/anti features and ads.

I did a search in the issues and found https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/issues/313

I notice in that issue that the interface was considered different, but having used both applications, it would seem to share identical features and layout to your open source app without attribution or links to the source-code (their company website apparently being an app design service).

I'm not sure what to do, any advice would be appreciated - I'd hate to see legitimate open source contributions being taken advantage of.

Thank you.

**Comment by VREMSoftwareDevelopment** [comment]
@accessiblepixel 

As was mentioned before, we are not aware that the applications that you are referring to are open source or are clones or copies of our open source application.

If you would like to support open source project, you can find all the necessary information on our [Github](https://vremsoftwaredevelopment.github.io/WiFiAnalyzer) page, such as: links to the application in Google Play and F-Droid store, how to contribute and etc.
