### ISSUE TITLE
RNS pairwise cipher GCMP is displayed as None

### ISSUE THREAD

**Issue by Avamander** [VREMSoftwareDevelopment/WiFiAnalyzer#412]
**Describe the bug**
RNS pairwise cipher GCMP is displayed as None. GCMP-256 and CCMP are detected correctly.

**To Reproduce**
1. Create an access point that allows the GCMP RNS pairwise cipher
2. View the access point list

**Expected behavior**
GCMP is displayed instead of None

**Additional context**
Linux `iw` utility shows it correctly as `Pairwise ciphers: 00-0f-ac:9 CCMP GCMP` (GCMP-256 just doesn't have a label in this case).

**Provide Device/Android OS information**
Device: Xiaomi Mi 9
Android: 11

**Comment by VREMSoftwareDevelopment** [comment]
Please provide Access Point details information.
Can be found in the app - Access Point details.
Please note that WPA3 requires Simultaneous Authentication of Equals (SAE) handshake to be enabled.

**Comment by Avamander** [comment]
> Please note that WPA3 requires Simultaneous Authentication of Equals (SAE) handshake to be enabled.

It is enabled.

> Please provide Access Point details information.

Tapping on it it doesn't show much besides `[NONE WPA3]`, `Wi-Fi 802.11ax` and `RSN-SAE-GCMP-256+CCMP+None` (when it should be `RSN-SAE-GCMP-256+GCMP+CCMP`).

**Comment by VREMSoftwareDevelopment** [comment]
Application does not control or change the following `RSN-SAE-GCMP-256+CCMP+None`.
This information is provided by Android API.
Most likely the issue is in Device/Android OS/API implementation (Xiaomi Mi 9).

**Comment by Avamander** [comment]
Does that string come directly from Android?

Some type of workaround would still be nice though. Maybe this is an even wider Android problem?

**Comment by VREMSoftwareDevelopment** [comment]
> Does that string come directly from Android?

Yes, from Android API

> Some type of workaround would still be nice though.

Will take a look if it possible

**Comment by VREMSoftwareDevelopment** [comment]
Possible fix in the next release
