### ISSUE TITLE
2.4 Ghz band keeps disappearing in App so many times 

### ISSUE THREAD

**Issue by Batman2814** [VREMSoftwareDevelopment/WiFiAnalyzer#413]
**Describe the bug*: 
My network for the 2.4 Ghz band keeps disappearing at radom times and then comes back at radom times.

**To Reproduce**
1. Go to 'open the app
2. Click on  channel graph and go to 2.4ghz band
3.) Refresh the screen by pulling down to update status

**Expected behavior**
5ghz and 6ghz band never disappears so the 2.4 ghz band should always be seen because my devices are connected to 2.4ghz band while this happens in the app.
**Screenshots**
If allll

![Screenshot_20230402_085924_WiFiAnalyzer.jpg](https://user-images.githubusercontent.com/96619913/229358000-2a13f0d5-d9e3-4ec1-8459-1a0c1df96737.jpg)

![Screenshot_20230402_085858_WiFiAnalyzer.jpg](https://user-images.githubusercontent.com/96619913/229358001-925c04d0-597f-45ba-84d9-f67fa63c3db7.jpg)

Device: samsung Galaxy Phone

Android version: 13 One Ui version 5.1

**Comment by VREMSoftwareDevelopment** [comment]
Please provide application version you are running

>  Refresh the screen by pulling down to update status

Probably Android API or Device can not response fast enough to the 2.4ghz current connection request

**Comment by Batman2814** [comment]
Application Version 3.0.11

I have done that by pulling down the page to update the status. It just completely disappears. I have to just come back to it at a later date when it's back showing again.

**Comment by VREMSoftwareDevelopment** [comment]
We have tried the reproduce the steps on the devices available to us.
Sorry to say that none of the devices show the same behavior.
Let's see if next upcoming release will fix this issue for you.

**Comment by Batman2814** [comment]
I do use Adguard Adblocker for Android on my device. Maybe the app isn't compatible with that Adguard Adblocker for Android.
