### ISSUE TITLE
Clarification on Exported Reports 

### ISSUE THREAD

**Issue by jpearson0525** [VREMSoftwareDevelopment/WiFiAnalyzer#414]
I enjoy using your package and especially the EXPORT report function.

I would appreciate a clarification on two columns in the report:

Distance - after some reading this appears to be a distance calculation based on the RF Signal level through open space (air) with no obstacles, walls, etc.   Is this true?

The Timestamp column (not the first Time Stamp column) is a number around 1513425932899.  Can you tell me what it is based on?   Origin date, units of measure.   I have not been able to convert it to a date/time close to the Time Stamp column?

Thank you , Jim.

**Comment by VREMSoftwareDevelopment** [comment]
> Distance - after some reading this appears to be a distance calculation based on the RF Signal level through open space (air) with no obstacles, walls, etc. Is this true?

Please take a loot at [How is distance calculated to Access Point](https://en.wikipedia.org/wiki/Free-space_path_loss)

> The Timestamp column (not the first Time Stamp column) is a number around 1513425932899. Can you tell me what it is based on? Origin date, units of measure. I have not been able to convert it to a date/time close to the Time Stamp column?

Please take a loot at https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/issues/392
