### ISSUE TITLE
Measuring an area - time for the app to settle down.

### ISSUE THREAD

**Issue by jpearson0525** [VREMSoftwareDevelopment/WiFiAnalyzer#415]
Many times, I use your app to take signal and Wifi measurements in a room, apartment, hallway.   Since I would like to move along take the measurements, export the data, and go to the next point.  I would like to know how long does it normally take the app to settle back down after the move.  I have the scan timer set to 1.    Do I need to turn off wifi and then back on to help speed up the remeasurment and settling down?   Do I need to restart the app?  Suggestions?

Jim.

**Comment by VREMSoftwareDevelopment** [comment]
Application has a setting `Cache off`.  When enabled, application will try to display exact results from Android API.
