### ISSUE TITLE
Distance for WiFi 2,4GHz and 5GHz is different for the same device

### ISSUE THREAD

**Issue by olekstomek** [VREMSoftwareDevelopment/WiFiAnalyzer#423]
In one the same device I have one network which is mixed for 2,4Ghz and 5Ghz. why the difference in the distance to the same device is as much as 3 meters? I check it half a meter from the router with the network visible in the screenshot.
![1683399324073](https://user-images.githubusercontent.com/26818304/236642346-4f4fa678-0126-4592-b2d9-98fc205ec0fc.jpg)

**Comment by VREMSoftwareDevelopment** [comment]
Please take a look at:
[How-to](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer#how-to)
[How is distance calculated to Access Point](https://en.wikipedia.org/wiki/Free-space_path_loss)
