### ISSUE TITLE
Connect this app to other system

### ISSUE THREAD

**Issue by andrew123-12** [VREMSoftwareDevelopment/WiFiAnalyzer#426]
I want to connect WiFi analyzer to my system. How can I connect it?That means my systems can use the function of wifi analyzer directly. Or, may I get the SDK file to combine my project?Thank you so much!

**Comment by VREMSoftwareDevelopment** [comment]
[WiFi Analyzer License](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer#license)
