### ISSUE TITLE
Channel rating appears to rate used and siblings channels identically

### ISSUE THREAD

**Issue by Thannoy** [VREMSoftwareDevelopment/WiFiAnalyzer#429]
_When you use an already used wifi channel, both networks attempts to politely share the frequency to avoid colision (time sharing). This is not perfect (performance decreases at least) but a real benefit over using sibling channels in which case both networks fails to cooperate and clearly perturbates each other._ 

**To Reproduce**
1. Find a location where there is only one 2.4 GHz wifi channel used
2. Join "Signal quality" view
3. Used wifi channel have a given rating
4. Sibling channels have the same rating

**Expected behavior**
I expected sibling/colliding channels (chan-2..chan+2) to have a lower score than used channel

**Screenshots**
Below is the wifi channels rating view when only channel 6 is used (by two networks):
![image](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/assets/3501742/0c66ce23-d624-4db8-a9e7-2d3711908069)
I expected channels 4, 5, 7, 8 to be rated lower than channel 6.

**Additional context**
I tried to find the wanted algorithm in the source code without getting it clearly, hence this ticket is a guess (and a subjective point of view/feeling). It is also possibole I misunderstand channels rating goal. 

Also, despite I think sibling channels should be given a penalty or clamp, I have no idea of how their value.

**Provide Device/Android OS information**
Running on Android 10

**Comment by VREMSoftwareDevelopment** [comment]
The channel rating algorithm is working as expected.

The algorithm uses different criteria to rate, such as:

- The number of the access points on the same channel
- Currently connected channel
- etc

[Channel rating code](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/blob/feature/app/src/main/kotlin/com/vrem/wifianalyzer/wifi/model/ChannelRating.kt)
