### ISSUE TITLE
WPA3-Enterprise network shown as unencrypted

### ISSUE THREAD

**Issue by duament** [VREMSoftwareDevelopment/WiFiAnalyzer#430]
**To Reproduce**
1. Set up an AP on OpenWrt with WPA3-EAP encryption
2. Open the APP

**Expected behavior**
Should be WPA3 instead of NONE

**Screenshots**
![Screenshot_20230720-215307](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/assets/30264485/1bffe7dd-4573-40fd-a2a4-cebd4dd20824)

**Provide Device/Android OS information**
Pixel 7
Android 13 with July 5 security update

**Comment by duament** [comment]
[getSecurityTypes()](https://developer.android.com/reference/android/net/wifi/ScanResult.html#getSecurityTypes()) (API level >= 33) might be useful

**Comment by VREMSoftwareDevelopment** [comment]
Fix should be available in the next release.
