### ISSUE TITLE
Only shows the network it is connected to, if any, else shows no networks

### ISSUE THREAD

**Issue by fpoto** [VREMSoftwareDevelopment/WiFiAnalyzer#440]
Used to work for years on my Sony Xperia with Android 10. Today I used it, one month after last usage, and no network is shown, the graphs are empty.
If the phone is connected to a wifi network, that one only is shown, but the graphs are still empty, both the time graph and the channel graph.

I unistalled and reinstalled the app and rebooted the phone, but nothing changes. I installed a similar analyzer by olgor.com (one of the first choices on the Google store) and it works as expected (and as WiFiAnalyzer used to).

WiFiAnalyzer 3.0.12 - 64G (10-29)

Sony Xperia X compact
model H8324
Android 10
build 52.1.A.3.49

**Comment by VREMSoftwareDevelopment** [comment]
Please make sure to enable the following:

- [Android Wi-Fi scanning throttling](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Android-WiFi-scanning-throttling)
- [Location Service Permission Requirements](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Location-Service-Permission-Requirements) - specifically enable ACCESS_FINE_LOCATION [section](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Location-Service-Permission-Requirements#android-10-api-level-29-and-higher-wi-fi-scanning-permissions-requirements)

**Comment by mx1up** [comment]
I can confirm the app works as expected on a Sony Xperia XZ2 compact running Android 10 as I have the same device.

Maybe check your filters and reset them.

**Comment by fpoto** [comment]
> I can confirm the app works as expected on a Sony Xperia XZ2 compact running Android 10 as I have the same device.
> 
> Maybe check your filters and reset them.

Thanks. There was a filter set on SSID name. No idea how I had put it there.

But what baffles me is that I uninstalled and reinstalled the app and then reboot the device, but the filter stayed there. Shouldn't a reinstall clear it?

**Comment by fpoto** [comment]
Sorry if this is obvious, but again, why the filter stayed there even after uninstalling and reinstalling the app? shouldn't it clean up all configuration upon deinstallation or upon reinstallation? or at least provide a factory reset functionality?

**Comment by fpoto** [comment]
Sorry if this is obvious, but again, why did the filter stay there even after uninstalling and reinstalling the app? shouldn't it clean up all configuration upon deinstallation or upon reinstallation? or at least provide a factory reset functionality?

**Comment by VREMSoftwareDevelopment** [comment]
All devices available to us reset saved application data after uninstall and install.

**Comment by mx1up** [comment]
> Sorry if this is obvious, but again, why did the filter stay there even after uninstalling and reinstalling the app? shouldn't it clean up all configuration upon deinstallation or upon reinstallation? or at least provide a factory reset functionality?

@fpoto it's a feature of the Android system: https://developer.android.com/guide/topics/data/autobackup
it is stored in your google drive: https://drive.google.com/drive/u/0/backups

I guess, if you want to clear the settings, you can do it through the android settings -> apps -> wifi analyzer -> clear storage / cache

**Comment by fpoto** [comment]
Thank you, and sorry for my ignorance.
I tried to check it, but after setting a filter, reboot, uninstall and reinstall the filter was gone, so I cannot reproduce the problem :(

Thank you for your work on this wonderful app.
