### ISSUE TITLE
WiFi Analyzer App does not show hotspots with 6 GHz however tablet will connect to them

### ISSUE THREAD

**Issue by codezero10101** [VREMSoftwareDevelopment/WiFiAnalyzer#443]
I have OUZRS 2022 M3 Max Pro with MT8183 cortex A73+ processor & Android 12.
The tablet supports 6GHz wifi.
WiFi Analyzer App does not show hotspots with 6 GHz however tablet will connect to them.

WiFi Analyzer -> About
shows:
incar - OUZRS - M3
green check for 2.4 GHz
green check for 5 GHz
red check for 6 GHz

Anything to suggest to remedy the problem?
List of tablets WiFiAnalyzer known to be compatible with 6 GHz?

**Comment by VREMSoftwareDevelopment** [comment]
`red check for 6 GHz` this information is displayed directly from Android API

Reference:
- [WiFiManager](https://developer.android.com/reference/android/net/wifi/WifiManager)
- [is6GHzBandSupported](https://developer.android.com/reference/android/net/wifi/WifiManager#is6GHzBandSupported())
