### ISSUE TITLE
Highlight currently connected access point in the graphs

### ISSUE THREAD

**Issue by michalmiddleton** [VREMSoftwareDevelopment/WiFiAnalyzer#45]
In Time Graph section, It would be great to highlight or make otherwise obvious to which AP is my device connected. It could be used to monitor handovers between APs based on signal strength.  (Wifi Insight app does it in a nice way).
Thanks guys!

**Comment by VREMSoftwareDevelopment** [comment]
Connected Access Point line on the Channel & Time graphs will have double thickness vs regular lines.

Current release V1.5.7
This feature will be available in the next release
