### ISSUE TITLE
Scanning message remains on the screen

### ISSUE THREAD

**Issue by rboxlon** [VREMSoftwareDevelopment/WiFiAnalyzer#454]
When using the software, the "scanning" message and the update message about scan throttling do not go away. This occurs when I use the software on a Samsung Galaxy S21 Ultra. I tried resolving by rebooting the phone, closing and reopening the app, uninstall the app and reinstall, but the problem persists.

**Comment by VREMSoftwareDevelopment** [comment]
**Some behavior only occurs on certain devices or versions of Android, please provide the following screenshots/information:**
- Device/Android OS (Settings → About Phone) 
- WiFi Analyzer version (Menu -> About)

**Is Android Wi-Fi scanning throttling disabled?**
The following links maybe helpful:
- [FAQ](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer#faq)
- [Android Wi-Fi scanning throttling](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Android-WiFi-scanning-throttling)

**Comment by CornelisJ** [comment]
I have the same problem here after the WiFi Analyzer app was updated to version 3.1.1 - 66G (13-33)
Device: Google Pixel 4a
Android version: 13

I don't know how to enable/disable WiFi scanning throttling, but I did not change this setting. When I opened the  Play Store app I noticed that an update of WiFi Analyzer was available. Then after the update was installed I opened the app, and I got the Scanning message and the message about Wi-Fi scan throttling that covers almost have of the screen. Screenshot is shown below.

![Wifi_Analyzer_screenshot](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/assets/59809764/c3a4fe91-48e2-4736-a8aa-13b01028b433)

**Comment by VREMSoftwareDevelopment** [comment]
@CornelisJ 

Please read provided links above (https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/issues/454#issuecomment-1873026630)
You will find explanations on how to: configure on-device developer options and  enable/disable WiFi scanning throttling,

**Comment by CornelisJ** [comment]
@VREMSoftwareDevelopment 
The information in the provided link about Wi-Fi Scanning throttling is not accurate. It says that for Android 10 and higher, Developer Options can be entered via Settings > Developer Options.  However on my Pixel4a with Android 13, there is no Developer Options under Settings.

After some googling I found that you first need to enable developer options via Settings > About this phone > Build number.  Then you need to tap build number several times, then enter the pincode of your phone, and only then Developer Options is enabled. After enabling Developer Options, this option was still not there in the Settings menu. The correct location appears to be Settings > **System** > Developer Options. After disabling wifi scanning throttling, WiFi Analyzer is indeed working.

I suggest that you update the information about where to find the WiFi scanning throttling option. First explain how to enable Developer Options, and than provide the correct information about where to find the Developer Options menu.

I still wonder why earlier version of WiFi Analyzer were working OK without disabling WiFi scanning throttling explicitly.

**Comment by VREMSoftwareDevelopment** [comment]
@CornelisJ 

> I suggest that you update the information about where to find the WiFi scanning throttling option. First explain how to enable Developer Options, and also provide the correct information about where to find the Developer Options menu.

Just below that there is a link on how to configure on-device developer options:
![image](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/assets/6217364/b77e6974-bd71-4b3b-89df-4aae597835a6)

Please fell free to update this page and help us to improve it. It would be great to add new contributors to this project.

Reference Link: [Android Wi-Fi scanning throttling](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Android-WiFi-scanning-throttling)

> I still wonder why earlier version of WiFi Analyzer were working OK without disabling WiFi scanning throttling explicitly.

Earlier version of WiFi Analyze were not working correctly without disabling WiFi scanning throttling explicitly.

![image](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/assets/6217364/1d12e841-3a7f-4e32-afb8-d550c2a32894)

**Comment by VREMSoftwareDevelopment** [comment]
Update message to be less intrusive.
It is available in the latest release.
