### ISSUE TITLE
make it clear that network shown on top is currently connected network

### ISSUE THREAD

**Issue by mx1up** [VREMSoftwareDevelopment/WiFiAnalyzer#456]
**Is your feature request related to a problem? Please describe.**
Related to https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/issues/441#issuecomment-1848678419 .
While I was filtering networks, it was not immediately apparent to me that the network shown at the top, is the currently connected network, regardless of filters. (see #441 for more context)

**Describe the solution you'd like**
Add some context to the tile like for example: 
<img width="418" alt="image" src="https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/assets/178714/20ec4cdc-5108-44ee-9395-655a62dc3ab5">

**How I can help**
I can make PR

**Comment by VREMSoftwareDevelopment** [comment]
Sure

On suggestions, instead of "Currently connected network", please use "Current connection"
