### ISSUE TITLE
Default theme should be system

### ISSUE THREAD

**Issue by inson1** [VREMSoftwareDevelopment/WiFiAnalyzer#466]
When I first open the app there should be selected system theme. Now on 3.1.2 I got dark theme.

**Provide Device/Android OS information**
Xiaomi redmi note 8 pro
Android 11

**Comment by VREMSoftwareDevelopment** [comment]
Please use provided feature report template, do not forget to fill all required information in the template. The information provided in the template helps to resolve issues faster.

Application uses **Dark** theme as default.
The user can change the theme after to any choice available in the application settings.
