### ISSUE TITLE
List all 2.4/5 GHz APs on the list simultaneously.

### ISSUE THREAD

**Issue by igsol** [VREMSoftwareDevelopment/WiFiAnalyzer#48]
Is it possible to see all 2.4/5 GHz APs on the list simultaneously without switching band?
There is another "WiFi Analyzer" in the Play which can do it.

Also, it would be great to group visually several APs not just with the same SSID, but which are used in corporative network as one virtual AP (i.e. with transparent routing).

**Comment by VREMSoftwareDevelopment** [comment]
Could you please split this into two feature request?
Also would you be able to elaborate in more detail on when and why you would use this option? 
We're curious to understand where you're coming from.

Thank you,
The VREM Development Team

**Comment by arafey** [comment]
I wondered about the first part of this issue as well. It could be helpful to group all APs with the same SSID under one entry, regardless of frequency. Under the current implementation, my one network's APs are split across multiple screens.

**Comment by VREMSoftwareDevelopment** [comment]
Next release will have 2.4/5 GHz listed simultaneously in the access points view. Current release V1.7.4  Play Store.

**Comment by arafey** [comment]
Just tested this out by building from the feature branch. Looks good!

**Comment by VREMSoftwareDevelopment** [comment]
@arafey Thanks
