### ISSUE TITLE
When will the new version released?

### ISSUE THREAD

**Issue by NewFuture** [VREMSoftwareDevelopment/WiFiAnalyzer#481]
I'm looking for the feature supporting K/V/R. And I found the #459 #468 are already merged but not released.

When will the new feature be released? 🤩

**Comment by VREMSoftwareDevelopment** [comment]
- Official releases are done in January and July of each year
- Critical issue are released as soon as they a fixed
- Beta releases are available as artifacts on each Android CI workflow
