### ISSUE TITLE
You can't exit the app using back if you have WiFi turned off

### ISSUE THREAD

**Issue by olekstomek** [VREMSoftwareDevelopment/WiFiAnalyzer#482]
[How to report a bug](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Feedback)

**Please search issues (open and closed) to see the issues has already been reported.**

**Describe the bug**

**To Reproduce**

1. Turn off WiFi
2. Open WiFiAnalyzer app
3. Click back button to close app
4. You are not able to close app, you see message that you should turn on WiFi

**Expected behavior**
I should be able to close app when WiFi module is disabled.

**Screenshots**
https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/assets/26818304/1268bfcd-3c37-45b7-8ecb-e9af6da6a7b1

**Note**
Some behaviour only occurs on certain devices or versions of Android, please provide the following screenshots/information Device/Android OS (Settings → About Phone) and WiFi Analyzer version (Menu -> About)
WiFiAnalyzer version 3.1.3 - 68G (14-34)

**Additional context**
I'm beta tester in Google Play. 

**Provide Device/Android OS information**
Android 11 on Xiaomi Mi 9, 
Android 14 on Samsung Galaxy A52 5G

**Comment by VREMSoftwareDevelopment** [comment]
Expected back button behavior in the Android WiFi Setting.

![settings](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/assets/6217364/2ed550a2-282a-441d-ac75-3c6c91567c4c)
![WiFiAnalyzer](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/assets/6217364/23763c8c-782f-4910-85ba-3dd003f7fa54)

**Comment by olekstomek** [comment]
So it means that there is no way to close app by back button without enabling WiFi module. 
Better could be: first click on back button shows option for enabling WiFi module (the same behavior like now), second click on back button close app.
