### ISSUE TITLE
Heatmap

### ISSUE THREAD

**Issue by ddieffen** [VREMSoftwareDevelopment/WiFiAnalyzer#493]
**Is your feature request related to a problem? Please describe.**
In order to easily set frequencies on a network with multiple AP, it would be nice to have a heatmap feature.

**Describe the solution you'd like**
Enable the user to import an image (jpg or other) that represents the floor plan. Once selected, enable the user to zoom, pan, move the floorplan image. Display a target on top of the floorplan representing where the user is located within the building.
One long press starts a scan of the AP Mac addresses and strengths of the skids, bands and frequencies. By moving all over the place we can then build a list of signal strength over the floorplan.
Once done, enable the user to save that "job" in an sqlite database so that a new scan can be added later on.
Find an algorithm capable of building a heatmap per ssid from the measurement and calculate barycenters of max signal strength. Mark the barycenters with a target, the channels, bandwidth, and last 4 digits of the Ap Mac.
Enable the use to export an image of the floorplan and heatmap per ssids.

**Describe alternatives you've considered**
Pay a service to have it done by professional 

**How I can help**
I can provide a dataset example, code in python, algorithm for building the map, and a floorplan. I have made a simple app 10 years ago but I've lost my edge on android dev

**Provide Device/Android OS information**
Any

**Comment by VREMSoftwareDevelopment** [comment]
There are a few applications available that do this already.
Currently there is no plans to do this work.
