### ISSUE TITLE
What does it mean when all signal drop below -90 dBm? 

### ISSUE THREAD

**Issue by drjasonharrison** [VREMSoftwareDevelopment/WiFiAnalyzer#494]
[How to report a bug](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Feedback)

**Please search issues (open and closed) to see the issues has already been reported.**

**Describe the bug**
I don't think this is a bug, but a question. 
When watching the time graph u see moments when all access point signal strength drops to -90 dBm. As if every access point is trying a new channel or there has been a collision that makes my phone believe all access points have silenced their radios. 

**To Reproduce**
Be in a location with many wireless networks (20, 39, or more) 
Enable developer tools 
Disable Wi-Fi scan throttling 
Launch Wi-Fi analyzer 
Select the time graph 
Observe that sometimes all of the signal strengths drop to -90 dBm 
![Screenshot_20240902-222529](https://github.com/user-attachments/assets/93a58c36-77dd-4b98-91a8-0268574414f9)
![Screenshot_20240902-222127](https://github.com/user-attachments/assets/dbc658cb-31e8-4dc0-83c0-027a6893398f)
![Screenshot_20240902-221902](https://github.com/user-attachments/assets/270ec9ee-f105-40f9-8847-88063ec33bd0)
![Screenshot_20240902-221859](https://github.com/user-attachments/assets/c60593d6-fd5e-4564-8d2f-0e461233db0b)

**Expected behavior**
Accurate signal strength reporting 
![Screenshot_20240902-225036](https://github.com/user-attachments/assets/39425e79-9cec-4885-b673-0641378e7ad9)
![Screenshot_20240902-225017](https://github.com/user-attachments/assets/2f952fad-de40-4740-983f-c689ee373890)

**Screenshots**
Attached for both Wi-Fianalyser and wifi analyser 

**Note**
Some behaviour only occurs on certain devices or versions of Android, please provide the following screenshots/information Device/Android OS (Settings → About Phone) and WiFi Analyzer version (Menu -> About)

**Additional context**

**Provide Device/Android OS information**

**Comment by VREMSoftwareDevelopment** [comment]
The WiFi scan results are provided by Android API.
Application does not change these values.

Please note we provide support only for this application.
