### ISSUE TITLE
Graphview Upgrade

### ISSUE THREAD

**Issue by VREMSoftwareDevelopment** [VREMSoftwareDevelopment/WiFiAnalyzer#50]
Switch to new version of GraphView 4.2.X

**Comment by JJWatMyself** [comment]
Problem 1: I noticed that pre 1.6.2 that a 2.4Ghz 40Hz SSID was displaying -1 channel of the actual and now on 1.6.2 it is -2 channels of the actual.

Problem 2: Both versions are displaying width greater than actual also. It appears to show 60Hz which is not the case. Should have width that is -2. E.g. SSID using 11 and 9 should display 8 to 12 at the top of the graph and 7 to 13 at the base.

**Comment by VREMSoftwareDevelopment** [comment]
Thank you for your feedback.

Can you please create a new issue and provide some sample screen shots, since we believe is it not relevant to the GraphView upgrade?

Thank you,
The VREM Development Team

**Comment by arafey** [comment]
A 40 MHz network wouldn't use 11+9. It would use 11+7. 9 is the center of the two channels. Some wireless APs will show 11+9 but they're telling you the primary channel and the center channel.

**Comment by JJWatMyself** [comment]
Thanks for the replies.  I  created a new issue.

**Comment by VREMSoftwareDevelopment** [comment]
Current release V1.6.4 Play Store.
This feature will be available in the next release.
