### ISSUE TITLE
Simplified Chinese translation error

### ISSUE THREAD

**Issue by pinoren** [VREMSoftwareDevelopment/WiFiAnalyzer#505]
In Simplified Chinese language（简体中文）
目前連接
It should be:
目前连接

![微信图片_20241215155618](https://github.com/user-attachments/assets/de625a5c-daef-4de8-b2e2-5aa6f097cddd)
![微信图片_20241215155613](https://github.com/user-attachments/assets/317b2837-64a9-4fa2-8b09-cf5e76fd15b2)

**Comment by VREMSoftwareDevelopment** [comment]
@pinoren 
Please submit PR
Thanks

**Comment by pinoren** [comment]
in street file，
Fixed typo in zh-CN translation. 
4 months ago

have this log。

**Comment by VREMSoftwareDevelopment** [comment]
References:
- When will the new version released? #481 
- Update strings.xml #497
