### ISSUE TITLE
2.4GHz channel plan for Australia is incorrect 

### ISSUE THREAD

**Issue by b0inger** [VREMSoftwareDevelopment/WiFiAnalyzer#51]
Channels 12 and 13 are not valid for Australia however show under "Available Channels" tab

**Comment by b0inger** [comment]
Also under "Channel Ratings".

**Comment by VREMSoftwareDevelopment** [comment]
Thanks.

**Comment by VREMSoftwareDevelopment** [comment]
This feature will be available in the next release
