### ISSUE TITLE
IP gets squashed on some devices.

### ISSUE THREAD

**Issue by DazzaJay** [VREMSoftwareDevelopment/WiFiAnalyzer#53]
On some devices (this one is a MotoG (3rd Gen) ) the IP address gets squashed along the right side of screen, completely breaking the UI.

Two screenshots attached: https://goo.gl/photos/f3XNGhsfbce94Dv89

**Comment by VREMSoftwareDevelopment** [comment]
Thank you for your feedback.

**Comment by VREMSoftwareDevelopment** [comment]
This feature will be available in the next release
