### ISSUE TITLE
Add quick switch for 2.4/5GHz

### ISSUE THREAD

**Issue by lightonflux** [VREMSoftwareDevelopment/WiFiAnalyzer#54]
At the moment you just need to many taps to switch between 2.4GHz and 5GHz. I counted and need 5 taps. 
Here a suggestion that could reduce it to 3.

Inspiration via [Transportr](https://github.com/grote/Transportr)'s sidebar where you can change public transport networks:

![screenshot_20160922-050219](https://cloud.githubusercontent.com/assets/1377943/18735955/594f5206-8082-11e6-8c2b-8de9c79f9891.png)

Here a quick and dirty mockup:

![screenshot_20160922-050207](https://cloud.githubusercontent.com/assets/1377943/18736147/873fd094-8084-11e6-8f88-bbf63651c38e.png)

In the current implementation it could switch between 2.4 and 5 GHz but in the future if or when #48 is implemented it could enable/disable the frequencies separately.

If this was implemented the old settings option could be dropped because it is redundant.

**Comment by VREMSoftwareDevelopment** [comment]
Thank you for your feedback. This feature is already available and requires only one tap. We are working on improving the UI and UX for it.
Please take a look at [VREMSoftwareDevelopment/WiFiAnalyzer](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer) usage tips section.
> **Tap the title bar to switch between 2.4 and 5 GHz WiFi band.**

**Comment by lightonflux** [comment]
I am happy to see that it is already implemented. But have to say it is impossible to discover in a normal way. 

> We are working on improving the UI and UX for it.

Is there an issue or roadmap/board to follow?
