### ISSUE TITLE
HT/VHT Detection

### ISSUE THREAD

**Issue by arafey** [VREMSoftwareDevelopment/WiFiAnalyzer#56]
This is just a copy of my review on the Play Store. Let me know if you need any extra information.

This application works very well. However, it needs to differentiate between 20/40/80/160 MHz channel widths in the graph. As of right now, a WiFi network operating on multiple channels will only show up as a 20 MHz network operating on the primary channel, which makes the auxiliary channels appear free although they're actually not.

**Comment by VREMSoftwareDevelopment** [comment]
Would you be able to elaborate in more what is exactly missing in the application?

- Access Points list show center channel and channel width. 
- Channel Graph show the graph using channel width.
- Channel Rating takes in account the channel width.

Thank you,
The VREM Development Team

**Comment by arafey** [comment]
If that were the case, all these networks would perfectly overlap because they are both 80 MHz wide and the only difference is one of them is ch 149 with upper sideband up to ch 161, and the other is ch 161 with lower sideband down to ch 149.

The AP list shows the primary channel.

![screenshot_20160926-220355](https://cloud.githubusercontent.com/assets/7505951/18857849/3c31c2e2-8435-11e6-8334-5858f4874237.png)

![screenshot_20160926-220810](https://cloud.githubusercontent.com/assets/7505951/18857909/c15db250-8435-11e6-8270-da07ea36e5df.png)

**Comment by arafey** [comment]
Although you're right, it does show 80 MHz next to the primary channel in the AP list, it would be a bit more clear if it stated the center channel in parenthesis because that would indicate that the networks are overlapping completely. The width indicates the same thing but unless you already know that an 80 MHz network using a channel between 149-161 is occupying the same space, you'd be confused as to why the channel rating page shows all those channels as occupied.

**Comment by arafey** [comment]
With 40 MHz networks, the situation is a lot better. My only issue there is that it shows the primary channels 5 and 11 (center is 3 and 9, respectively). Instead of "CH 5 (40 MHz)", "CH 5+1" would be more clear to distinguish from "CH 5+9".

If you wanted to go really verbose, you could have "CH 5+1(3) - 40 MHz" (Primary+Auxiliary(Center) - width). With 5 GHz that would look like "CH 149+153+157+161(155) - 80 MHz", for an AP with primary channel 149. That could be a bit too much. These are just some possible implementations.

With 40 MHz networks, it looks like the graph and ratings are accurate.

![screenshot_20160926-223352](https://cloud.githubusercontent.com/assets/7505951/18858347/6964c864-8439-11e6-98ce-ce1936731090.png)
![screenshot_20160926-223403](https://cloud.githubusercontent.com/assets/7505951/18858346/696389fe-8439-11e6-9d98-fe9281472e90.png)
![screenshot_20160926-223315](https://cloud.githubusercontent.com/assets/7505951/18858348/6965f04a-8439-11e6-90b9-b5740e6b0a3a.png)

**Comment by VREMSoftwareDevelopment** [comment]
Thank you for your input, it is very helpfull.

**Comment by VREMSoftwareDevelopment** [comment]
Based on available information from Android API some of the information from this feature will be available in the next release.

**Comment by arafey** [comment]
Great, thanks for the quick turnaround! Any links to the relevant section(s) of the API?

**Comment by VREMSoftwareDevelopment** [comment]
New Version 1.6.2 is available in the Google play store.
[Developer Android API WiFi scan results](https://developer.android.com/reference/android/net/wifi/ScanResult.html)
You can switch API level to appropriate Android OS to see what is available:
- API Level 24 is Android OS 7
- API Level 23 is Android OS 6
- API Level 22 is Android OS 5.1

**Comment by arafey** [comment]
Just loaded the newest version and it's great. I'll update my review.
