### ISSUE TITLE
Android OS 4.4 Support

### ISSUE THREAD

**Issue by rbrito** [VREMSoftwareDevelopment/WiFiAnalyzer#57]
Is there any particular reason why the project does not support Android 4.x? In particular, I have only one device (my cell phone) that has an Android that is newer than 4.

Is there anything that the program uses that is intrinsically only supported in newer Android versions or is it just a matter of convenience?

Thanks for making this great app available also on F-Droid!

**Comment by VREMSoftwareDevelopment** [comment]
Thank you for your feedback.

When we started on this project we were considering only to support Android OS 6 and above.
Android OS 6 introduced very important information that is very relevant to help diagnose WiFi issues [HT/VHT Detection](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/issues/56).
We have settle on Android OS 5.1 and above, but reality is that anything below Android OS 6 will not give you a real picture of WiFi around you.

By any chance, do you have any knowledge in Android development? When we don't have an opportunity to implement a feature, we encourage developers to fork the project.

**Comment by VREMSoftwareDevelopment** [comment]
Current release V1.6.6 Play Store.
Will be available in the next release.
