### ISSUE TITLE
How channel graph displays 20/40/80/160 MHz channel width?

### ISSUE THREAD

**Issue by JJWatMyself** [VREMSoftwareDevelopment/WiFiAnalyzer#64]
Many thanks for the update to 1.6.4 yesterday.  On AT&T Samsung GS6 running 6.0.1 the control channel is now displaying correctly.  The width is not displaying correctly on 2.4GHz or 5GHz.  2.4GHz HT shows 60Hz instead of 40Hz, and 5GHz VHT shows 140Hz instead of 80Hz. Screenshots are below.  I believe the width issue was present on the previous version. Screenshot of that are on the bug report that you closed at the weekend.
![2-4ghz](https://cloud.githubusercontent.com/assets/22590445/19708618/f9649ac8-9aed-11e6-8628-5201eb7c4eef.png)
![2-4ghzcapture](https://cloud.githubusercontent.com/assets/22590445/19708620/fed104c4-9aed-11e6-96af-8e9bfb963fda.PNG)
![2-4ghzcapture1](https://cloud.githubusercontent.com/assets/22590445/19708622/00df32f4-9aee-11e6-9417-3a612ca08ac1.PNG)
![5ghz](https://cloud.githubusercontent.com/assets/22590445/19708627/05a4d0d2-9aee-11e6-84af-e870898530a4.png)
![5ghzcapture](https://cloud.githubusercontent.com/assets/22590445/19708628/08b9e140-9aee-11e6-8a62-bd8cb46487de.PNG)
![5ghzcapture1](https://cloud.githubusercontent.com/assets/22590445/19708631/0b6d2faa-9aee-11e6-8dc1-98ab81b6fc53.PNG)

**Comment by VREMSoftwareDevelopment** [comment]
**5MHz per channel**

- 20MHz width = 4 channels, -/+2 channels from center
- 40MHz width = 8 channels, -/+4 channels from center
- 80MHz width = 16 channels, -/+8 channels from center
- 160MHz width = 32 channels, -/+16 channels from center
 
**Your example:**
- hamster-n 11+9 with 40MHz width: Primary Channel 11, Center Channel 9. With center channel 9, covers channels 5(9-4) to 13(9+4)
- hamster-ac 132+138 with 80MHz width: Primary Channel 132, Center Channel 138. With center channel 138, covers channels 130(138-8) to 146(138+8)

Looks like channel graph is correct.

**Comment by JJWatMyself** [comment]
How right you are.  Sorry about that..  I'm was a bit confuded again.  :)

**Comment by jkdf2** [comment]
Please close this :)
