### ISSUE TITLE
add change log to fdroid

### ISSUE THREAD

**Issue by treakiandroid** [VREMSoftwareDevelopment/WiFiAnalyzer#67]
please add a link to changelog page to the fdroid repository. thanks

**Comment by VREMSoftwareDevelopment** [comment]
All releases are tagged and changelog is attached.

[https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/releases](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/releases)
