### ISSUE TITLE
Please add an option to customize the Y scale

### ISSUE THREAD

**Issue by Serveurperso** [VREMSoftwareDevelopment/WiFiAnalyzer#70]
Please add an option to customize the Y scale. -10dB is too huge and all received beacons are on the bottom of the spectrum view.

**Comment by VREMSoftwareDevelopment** [comment]
Changing graph maximum Y scale to -20dBm.
Current release V1.6.5 Play Store.
Will be available in the next release.

**Comment by VREMSoftwareDevelopment** [comment]
Next release will have ability to customize the top of the Y scale (range 0db to -50db)
Current release V1.7.1 Play Store.

**Comment by Serveurperso** [comment]
Thanks a lot for your work
