### ISSUE TITLE
Option to remove vendor specific information

### ISSUE THREAD

**Issue by mehakimz** [VREMSoftwareDevelopment/WiFiAnalyzer#72]
I'm using the app on CM-13.0 running on my Xperia device. The Broadcast Packets have some vendor specific information (is seen on Wireshark). Could it possible to remove such data or set a unique one?

This is a very useful app on F-Droid, Thank you.

**Comment by VREMSoftwareDevelopment** [comment]
Could you please be more specific what exactly are you seeing?
