### ISSUE TITLE
Dialogs disappear on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [VREMSoftwareDevelopment/WiFiAnalyzer#77]
When I perform this sequence of events the dialog on screen disappears
1. Open side drawer
2. Click on Settings
3. Click on settings item in list
4. Orientation change

**Comment by VREMSoftwareDevelopment** [comment]
- Android creates a new view when switching orientation. It is intended. 
- It is on the **Setting Screen** of the Application - Low Priority
- It would be great if you can provide a pull request to fix it.

Btw, thanks for reporting :+1:
