### ISSUE TITLE
Scroll View changes state on device rotation #2

### ISSUE THREAD

**Issue by reverse-unina** [VREMSoftwareDevelopment/WiFiAnalyzer#78]
When I perform this sequence of events, the scroll view on screen goes back to the top:

Open Side Drawer
Click on Settings
Scroll Down
Orientation Change

**Comment by VREMSoftwareDevelopment** [comment]
- Android creates a new view when switching orientation. It is intended. 
- It is on the **Setting Screen** of the Application - Low Priority
- It would be great if you can provide a pull request to fix it.

Btw, thanks for reporting :+1:
