### ISSUE TITLE
F-Droid can't build version 1.6.6

### ISSUE THREAD

**Issue by z751** [VREMSoftwareDevelopment/WiFiAnalyzer#79]
https://f-droid.org/wiki/page/com.vrem.wifianalyzer

**Comment by VREMSoftwareDevelopment** [comment]
There is no problem using Travis CI to build WiFi Analyzer version `V1.6.6-F-DROID`.
[https://travis-ci.org/VREMSoftwareDevelopment/WiFiAnalyzer/builds/182149002](https://travis-ci.org/VREMSoftwareDevelopment/WiFiAnalyzer/builds/182149002)

The problem in on F-Droid side, latest Android build tools are missing.
`You have not accepted the license agreements of the following SDK components:
  [Android SDK Build-Tools 25.0.1].`
