### ISSUE TITLE
Add Filters as an enhancement

### ISSUE THREAD

**Issue by Noki** [VREMSoftwareDevelopment/WiFiAnalyzer#81]
I like the WIFIAnalyzer! However it misses a feature to effectively filter long lists of accesspoints especially because long lists tend to change quickly. I travel a lot and for me it would be useful to get a quick overview with strong and open networks e.g. in a hotel.

Currently I can only filter for the 2.4 and 5 GHz accesspoints. I would love to have a single list and than add filters for:

- [ ] Type of Encryption / Features
- [ ] Strength of Accesspoints (eg. only show strong ones)
- [ ] Band (2.4 / 5 GHz)
- [ ] Channel

Maybe you can add this somewhen in the future but even without this it's already a great piece of software.

Best regards
Tobias

**Comment by VREMSoftwareDevelopment** [comment]
Hi Tobias,

> Strength of Accesspoints (eg. only show strong ones)

Setting->Sort by Access Points By->Signal Strength - this will show strongest first in the list.

Did you try export feature in a meantime?
Export Access Points List into Google Sheets, this will allow you to do any data manipulation/filtering.

Regards,

VREM Development Team

**Comment by naoaustin** [comment]
This is the best apps among similar apps. But, I also like the filtering feature. I understand to split 2.4G and 5G view for Channel Graph, but for Access Points and Time Graph, regardless of frequency, I want to simultaneously see only the access points which I am allowed to use.  Filtering by SSID is what I want.

Anyway, this is a gread app, and I will keep using. Thank you.

Regards,
Nao

**Comment by Noki** [comment]
Hi! 

Sorting does not really help if you are in an area with more than 50 APs around you. In that case you have to increase the scan interval, so you can actually go over the full list without changes interrupting you. And by doing so it takes forever to find the spot with the best reception to a specific wifi network.

I know that I can work around the filtering with the exports. But that is also a quite annoying workaround.

In my opinion filters would really improve the usability a lot. You can still have predefined filters like 2.4/5 GHz or one for the connected SSID or one for open Wifis. - All that would help.

Best Regards
Tobias

**Comment by fkoran** [comment]
Here's what the time graph looks like in my apartment. I'm trying to find the best spot to mount a repeater to share a connection with my neighbor. I like that the connected SSID is highlighted with a thicker line. If I could filter out all the other SSIDs that would be even better

![time graph](https://i.imgur.com/JGUk0N4.png)

**Comment by VREMSoftwareDevelopment** [comment]
Access Points list will have the following filters available in the next release:
-     Type of Encryption / Features
-     Strength of Access Points
-     Band (2.4 / 5 GHz)

Current release V1.7.4 Play Store.

**Comment by Noki** [comment]
Cool! Looking forward to it. :-)

**Comment by ljpasus** [comment]
WiFi Analyzer is a great app, but after the update with the filters, the Channel Graph has my channel only. The same happens in the AP list and in the Time Graph. The channel rating lists one channel used for channels 2 to 10, but those channels do not appear in the AP list.
Two or three days ago I changed the channel my AP uses because of the number of APs using the same channel, so it is very unlikely that there's only one channel in use now.
I tried to change the filters, but no filter config worked. Then I reset the filters.
Please help.

**Comment by VREMSoftwareDevelopment** [comment]
Hi @ljpasus 

**Can you please open a new issue and with your comment?**

The filter is available and effects only Access Points view. All other views do not have filters.

Please provide the following screenshots in-order to help you to solve the problems you are having.
- Access Points List 
- Access Points List with filter pop-up
- Channel Graph
- About Screen

Regards

VREM Development Team

**Comment by VREMSoftwareDevelopment** [comment]
Channel & Time graph will have the filter option available in the next release.
Current release V1.8.1 Google Play Store.
