### ISSUE TITLE
First 2 Networks Use Near Identical Blue Colors

### ISSUE THREAD

**Issue by dbareis** [VREMSoftwareDevelopment/WiFiAnalyzer#83]
A lot more care could go into selecting the colors, even better if the user could defined them

**Comment by VREMSoftwareDevelopment** [comment]
@dbareis Would you like to help us with picking better default colors?

The default colors are available in the following file [https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/blob/master/app/src/main/res/values/arrays.xml](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/blob/master/app/src/main/res/values/arrays.xml) under the section `<string-array name="graph_colors" translatable="false">`.

**Comment by VREMSoftwareDevelopment** [comment]
The ability for the user to define the colors will not be added to the application at this time. The default color set was re-arranged to give a better contrast. It does not guaranty that some colors will not clash, when there are a lot of networks in the area. This will be available in the next release.  Current release V1.7.1 Play Store.
