### ISSUE TITLE
Time Graph Loses Network And Data

### ISSUE THREAD

**Issue by dbareis** [VREMSoftwareDevelopment/WiFiAnalyzer#84]
If a network is lost for a period of time that should not make the network look like it's just been spotted when it comes back. The graph for it should be spotted, not start a fresh.

**Comment by VREMSoftwareDevelopment** [comment]
@dbareis Could you please explain in more details what do you mean "should be spotted"?

**Comment by dbareis** [comment]
If the network drops off and comes back its drawn as if its never been seen before (like a network seen for the first time) rather than one with gaps in the display.

**Comment by VREMSoftwareDevelopment** [comment]
Next release will have this fixed. The application will still require to drop not visible networks after some time. 
Current release V1.7.1 Play Store.
