### ISSUE TITLE
Support for multiple WiFi interfaces - no longer exists ?

### ISSUE THREAD

**Issue by tapolyaip** [VREMSoftwareDevelopment/WiFiAnalyzer#86]
I believe an older version used to support multiple WiFi adapters. I have a Samsung Galaxy 4 Tab, where I use WiFiAnalyzer to find my access points. I think a while ago when I connected a USB WiFi adapter to my tablet, then the program listed all access points separately what the built in WiFi picked up and what the USB adapter WiFi adapter picked up. Right now I am not even sure it uses the USB adapter - only the built in one.

**Comment by VREMSoftwareDevelopment** [comment]
This WiFi Analyzer never had this feature. You are confusing some other application with this one.
