### ISSUE TITLE
Expanded network changes

### ISSUE THREAD

**Issue by MrFrumpy904** [VREMSoftwareDevelopment/WiFiAnalyzer#87]
When having networks sorted by SSID in AP
I can have 3 SSID listed with the second one being expaneded.  So 1 2 expanded and 3
A weak network shows up at the top of my list 0 1 2 and 3
Network 1 gets expanded and network 2 becomes collapsed.
This causes issues if weak signals are constantly showing up and disappearing.

**Comment by VREMSoftwareDevelopment** [comment]
To help us to determine your issue, can you please provide the following screenshots:
- About view
- Setting view
- Access Point views with the issue you are describing
