### ISSUE TITLE
Available Channels 2.4 GHz

### ISSUE THREAD

**Issue by s1awa** [VREMSoftwareDevelopment/WiFiAnalyzer#94]
1)
WiFiChannelCountryGHZ2.java needs to be more flexible like WiFiChannelCountryGHZ5.java
Currently it just sets channels 1-11 for defined countries and adds 12-13 to world.

2)
Here is a list of allowed channels in different countries:
https://www.juniper.net/techpubs/hardware/netscreen-appliances/5gtwireless/wireless_channels.pdf
Wikipedia is not a great place for that kind of information.

3)
e.g. Taiwan is in the default 1-11 list, but this is wrong. 
[Taiwan allows channels 1-13](https://zh.wikipedia.org/wiki/WLAN%E4%BF%A1%E9%81%93%E5%88%97%E8%A1%A8#.E4.BF.A1.E9.81.93.E5.88.97.E8.A1.A8) ([Specifications in Chinese](http://www.ncc.gov.tw/chinese/files/13010/1166_27418_130103_1.doc))
![tw](https://cloud.githubusercontent.com/assets/20663500/23847289/afdba0ae-080c-11e7-9401-a842a40cedca.png)
Google Translated:
![tw](https://cloud.githubusercontent.com/assets/20663500/23847449/52ab5432-080d-11e7-8467-bc66e4bc0217.png)

Also channel 14 is not there, but not allowed in most places anyway...

**Comment by VREMSoftwareDevelopment** [comment]
1) Would you like to help with this, it would be great to add another contributor to this project?

2) Wikipedia and a lot of open source projects (including WiFiAnalyzer) relies on the community and contributors to get correct information.

3) We will fix the issue with Taiwan channels in the next release.

Regards,

VREM Development Team
