### ISSUE TITLE
What is main logic behind  this app?

### ISSUE THREAD

**Issue by RelinnsTechnologies** [VREMSoftwareDevelopment/WiFiAnalyzer#95]
Hi,

I want to know what is main logic behind this app how this gets wifi name .This app is developed in android studio or any other Technic used.
Please tell  me i have problem to get wifi name, to get wifiname i needed to "ON" GPS of device.Rest owrking of my app is good but i dont know why i need GPS ON to get wifi name.Please help me.

Code :- 
            WifiManager manager1 = (WifiManager) this.getSystemService(Context.WIFI_SERVICE);
        
            List<ScanResult> results = manager1.getScanResults();
            for (ScanResult result : results) {
                wifiname=wifiname+result.BSSID+",";
                Log.d("MacAddr:",result.BSSID);
                Log.d("name:",result.SSID);
            }

**Comment by NeverMine17** [comment]
Did you read the README.md?

> Some users running Android OS 6 (Marshmallow) have reported that the location service must be enabled for the application to see WiFi networks. Marshmallow users may need to turn on the location service, even though WiFiAnalyzer does not explicitly require it. This appears to be attributed to Android OS 6 that requires location service in order to see WiFi networks.
