### ISSUE TITLE
AP view: sort by signal strength expands differently when refreshed

### ISSUE THREAD

**Issue by dave4445** [VREMSoftwareDevelopment/WiFiAnalyzer#97]
In AP list view, when sorted by signal strength and when multiple APs with the same SSID:  If you expand the APs (with the same SSID) that works and shows all APs with that SSID, however when the screen refreshes a different SSID may be expanded instead of the original one if the signal strength changes during refresh.

**Comment by VREMSoftwareDevelopment** [comment]
Next release will this bug fixed. 
Current release V1.8.2 Google Play Store.
