### ISSUE TITLE
Channel Graph: Show all 5Ghz channels on one screen

### ISSUE THREAD

**Issue by dave4445** [VREMSoftwareDevelopment/WiFiAnalyzer#98]
Please find a way to fit all the 5Ghz channels on one screen instead of 3 groups with lots of scrolling within.

**Comment by arafey** [comment]
Perhaps the best way to implement this would be to dynamically adjusting the range of the x-axis based on the channels that are detected. How difficult would it be to do this in practice?

**Comment by dave4445** [comment]
Other apps show the 5ghz by splitting the screen top/bottom to show half the channels on top and other half on bottom.  Also since there are no overlapping channels in 5ghz, only every 4th channel could be shown, the other 3 are unnecessary and waste space.

**Comment by ea4eoz** [comment]
Take a look on Wifiman application from Ubiquity in Google Play. I really love the way it shows the 5 GHz band and I would love to have that in WifiAnalyzer.
