### ISSUE TITLE
F-Droid Key Changed?

### ISSUE THREAD

**Issue by arafey** [VREMSoftwareDevelopment/WiFiAnalyzer#99]
I'm getting a message on F-Droid saying that I need to uninstall the app and reinstall it because it was signed by a different key. Was a different key used or was there a security breach?

**Comment by VREMSoftwareDevelopment** [comment]
We will assume that you have installed previous version of the application from Google Play store.
F-Droid and Google play store have different keys.
Since F-Droid build application from source, they use their own key.
Please do not install application from different stores.

**Comment by arafey** [comment]
I found out. It's because Google Play Store has 1.8.2 and F-Droid is at 1.8.3.
